stnolting/neorv32

.github/workflows/Implementation.yml, .github/workflows/Processor.yml, README.md
As discussed in #31, this PR adds a workflow named Implementation for generating the UPduino v3 bitstream using the open source tools. Precisely, a single container from [hdl/containers](https://github.com/hdl/containers) is used. That's why the job is named "All-in-one" (see https://hdl.github.io/containers/#_all_in_one_images). The bitstream, along with the yosys and nextpnr reports (logs) are uploaded as an artifact. However, the artifact is not published anywhere else. That is, users willing to download the bitstream/reports need to go to https://github.com/stnolting/neorv32/actions/workflows/Implementation.yml.
BTW, I renamed workflow "Processor Check" to "Processor" in order to reduce the width of the labels in the readme. Moreover, all workflows are checks in some sense, so I think …
=> Add GitHub Actions workflow 'Implementation'

Makefile
Close #33
In this PR, `git describe` is used for setting a unique revnumber for each commit. Since the container does not include git, a `docs/revnumber.txt` file is created outside. If it exists, it's used for overriding the revnumber attribute through the CLI. Otherwise, the revnumber set in the adoc sources is used.
=> [docs] set revnumber through git describe

Makefile
This PR implements one of the two solutions commented in https://github.com/stnolting/neorv32/commit/3ee1ac5df065237d6df22b701901737c052e21ca#commitcomment-51279169.
=> [ci] prevent tag 'nightly' being used in revnumber

.gitignore, Makefile
For some time, I wanted to learn how to use asciidoctor-diagram with wavedrom support, so I gave it a try.
For illustration purposes, in the last commit of this PR `wavedrom.adoc` is added and it is included in `content.adoc`. It shows a timing diagram, a bit-field diagram and a logic circuit, all generated through wavedrom. It also shows how to include a wavedrom figure from a JSON5 file, instead of writing the wave/diagram in the adoc source.
It works both for the HTML and the PDF outputs. See page 7 of [NEORV32.pdf](https://github.com/stnolting/neorv32/files/6529157/NEORV32.pdf).
Nevertheless, this PR is not ready to be merged because the `wavedrom.adoc` file is just a demo. @stnolting, let me know if you find this feature interesting. You can make a copy of the `wavedrom.adoc` file, …
=> Use asciidoctor-diagram with wavedrom support

docs/attrs.adoc, docs/attrs.main.adoc, docs/datasheet/index.adoc, docs/datasheet/main.adoc, docs/userguide/index.adoc, docs/userguide/main.adoc
This PR reduces the duplication of the frontmatter in the docs. `attrs.adoc` is included in all docs (either `index.adoc` or `main.adoc`). `attrs.main.adoc` is included in PDF docs only (`main.adoc`).
=> [docs] add attrs.adoc and attrs.main.adoc

.gitignore, setups/examples/neorv32_Fomu_BoardTop_Minimal.vhd, setups/examples/neorv32_Fomu_BoardTop_MinimalBoot.vhd, setups/examples/neorv32_Fomu_BoardTop_UP5KDemo.vhd, setups/examples/neorv32_UPduino_v3_BoardTop_MinimalBoot.vhd, setups/examples/neorv32_UPduino_v3_BoardTop_UP5KDemo.vhd, setups/osflow/devices/ice40/neorv32_dmem.ice40up_spram.vhd, setups/osflow/devices/ice40/neorv32_imem.ice40up_spram.vhd, setups/osflow/synthesis.mk, setups/radiant/UPduino_v2/neorv32_dmem.ice40up_spram.vhd, setups/radiant/UPduino_v2/neorv32_imem.ice40up_spram.vhd, setups/radiant/UPduino_v2/neorv32_upduino_v2_top.vhd, setups/radiant/UPduino_v3/neorv32_dmem.ice40up_spram.vhd, setups/radiant/UPduino_v3/neorv32_imem.ice40up_spram.vhd, setups/radiant/UPduino_v3/neorv32_upduino_v3_top.vhd
Although we've been using the sb_ice40_components source for UP5K devices only, some of those can be used with other ICE40 devices too. This PR renames the logical library name from `iCE40UP` to `iCE40`.
By the way, `.gitignore` is updated.
=> rename logical library 'iCE40UP' to 'iCE40'

.github/workflows/Processor.yml, riscv-arch-test/port-neorv32/framework_v1.0/riscv-target/neorv32/README.md, riscv-arch-test/port-neorv32/framework_v1.0/riscv-target/neorv32/device/rv32Zicsr/Makefile.include, riscv-arch-test/port-neorv32/framework_v1.0/riscv-target/neorv32/device/rv32Zifencei/Makefile.include, riscv-arch-test/port-neorv32/framework_v1.0/riscv-target/neorv32/device/rv32i/Makefile.include, riscv-arch-test/port-neorv32/framework_v1.0/riscv-target/neorv32/device/rv32im/Makefile.include, riscv-arch-test/port-neorv32/framework_v1.0/riscv-target/neorv32/device/rv32imc/Makefile.include, riscv-arch-test/port-neorv32/framework_v2.0/riscv-target/neorv32/README.md, riscv-arch-test/port-neorv32/framework_v2.0/riscv-target/neorv32/device/rv32i_m/C/Makefile.include, riscv-arch-test/port-neorv32/framework_v2.0/riscv-target/neorv32/device/rv32i_m/I/Makefile.include, riscv-arch-test/port-neorv32/framework_v2.0/riscv-target/neorv32/device/rv32i_m/M/Makefile.include, riscv-arch-test/port-neorv32/framework_v2.0/riscv-target/neorv32/device/rv32i_m/Zifencei/Makefile.include, riscv-arch-test/port-neorv32/framework_v2.0/riscv-target/neorv32/device/rv32i_m/privilege/Makefile.include, setups/vivado/arty-a7-test-setup/create_project.tcl, setups/vivado/nexys-a7-test-setup/create_project.tcl, sim/ghdl/ghdl_sim.sh, sim/neorv32_tb.simple.vhd, sim/uart_rx.simple.vhd, sim/uart_rx.vhd
In this PR, the Processor workflow is split in two jobs. The main reason is running the VUnit tests and the shell script tests in parallel. Moreover, the installation of the RISC-V toolchain in the VUnit job might be enhanced in the future by using a container.
Other than that, as done with the main testbench, `uart_rx` is copied to `uart_rx.simple.vhd`, and it is reverted to the version before self-checking was in place. Other sources/references are updated accordingly. In upcoming PRs, `uart_rx` will be modified for using VUnit features, while `uart_rx_simple` will be used for the simple testbench.
Last, one of the enhancements from #48 was cherry-picked here. That uses VUnit's features in uart_rx.
/cc @LarsAsplund
=> VUnit checking

.github/generate-job-matrix.py, setups/examples/Makefile, setups/examples/neorv32_iCESugar_BoardTop_Minimal.vhd, setups/osflow/devices/ice40/sb_ice40_components.vhd
Name Minimal may not be the most descriptive. The purpose of this PR is to modify the MinimalBoot example of the iCESugar for using the "external" clock from pin 35, instead of the internal oscillator.
On the Fomu, we could use SB_PLL40_CORE for instantiating the PLL, regardless of the clk input being internal or external. That is because of the bank where the clk input is located (`IOB_11b_G5	DPIO/GBIN	1	COMP_of_IOB_10a	F4`). On the iCESugar, that is `IOT_46b_G0	DPIO/GBIN	0		B3	35`. As explained in https://github.com/wuxx/icesugar/blob/master/doc/LatticeSemi/SBTICETechnologyLibrary201708.pdf, SB_PLL40_PAD needs to be used.
Therefore, SB_PLL40_PAD was added to `setups/osflow/devices/ice40/sb_ice40_components.vhd`. Compared to iCESugar MinimalBoot, this one (iCESugar Minimal) instantiates …
=> [setups/examples] add iCESugar Minimal

sim/neorv32_tb.vhd, sim/uart_rx.vhd
Close #48
This PR superseeds #48, but it needs to be merged after #80.
That is, @LarsAsplund's PR2 branch can be analysed/understood in three parts:
1. PR1 was already split and merged in previours PRs.
2. The software modifications for controlling UART verbosity are being handled in #80.
3. This PR adds VUnit loggers to the hardware testbench plumbing.
=> [sim] use custom VUnit loggers for better verbosity control 

sim/neorv32_tb.vhd, sim/uart_rx.vhd, sim/uart_rx_pkg.vhd
Collect all generics into a single handle generic. A single generic is easier to pass
around and makes it easier to update the VC without changing the user code.
Also using a `check_uart` procedure to raise the abstraction of the API.
=> Make uart_rx a VUnit verification component. Step 4.

sim/README.md
Subdir `sim/vivado` was removed in https://github.com/stnolting/neorv32/commit/6eff0dfea90e72d9ea5d60a61ba66060b182ae2d#diff-507a9a8be3d145a86daa9644b28bf42a8dc0720d8baeabdf0406c393692bf082, but the `sim/README.md` was not updated accordingly.
=> sim: update readme

.github/workflows/Documentation.yml, docs/Makefile, docs/userguide/content.adoc
Initially, we put the Makefile for building the docs in the root of the repo, because we expected to add entrypoints for other tasks in the same file. However, given how the rest of the repo evolved, that is probably not going to happen. We will probably have some orchestration/entrypoint in the root which wraps the different makefiles. Therefore, this PR moves the Makefile for building the documentation into subdir `docs`.
=> [docs] move Makefile from project root to subdir 'docs'

.gitignore, riscv-arch-test/run_riscv_arch_test.sh, setups/osflow/.gitignore
This is some cleanup of the `riscv-arch-test/run_riscv_arch_test.sh` script. It should be functionally equivalent, but easier to read/maintain.
Moreover, it seems that subdir `riscv-arch-test` is used just for simulation with GHDL. @stnolting, what do you think about moving it into `sim/riscv-arch-test`? That would keep the root of the project cleaner, while making it explicit that the riscv-arch-test are used for testing/verification. In the future, we might enhance `run_riscv_arch_test.sh` for using some VUnit features, or have it removed and handle these tests in the existing `sim/run.py` script.
=> riscv-arch-test script cleanup

docs/datasheet/software.adoc, docs/userguide/content.adoc, riscv-arch-test/run_riscv_arch_test.sh, sim/ghdl_sim.sh, sw/bootloader/makefile, sw/example/blink_led/makefile, sw/example/coremark/makefile, sw/example/demo_freeRTOS/makefile, sw/example/demo_neopixel/makefile, sw/example/demo_pwm/makefile, sw/example/demo_trng/makefile, sw/example/demo_twi/makefile, sw/example/demo_wdt/makefile, sw/example/demo_xirq/makefile, sw/example/floating_point_test/makefile, sw/example/game_of_life/makefile, sw/example/hello_world/makefile, sw/example/hex_viewer/makefile, sw/example/processor_check/makefile, sw/ocd-firmware/makefile
The riscv-arch-test uses variable `RISCV_PREFIX`, but the makefiles in `sw` use `RISCV_TOOLCHAIN` for the same purpose This PR makes them consistent by using `RISCV_PREFIX` only.
=> use RISCV_PREFIX instead of RISCV_TOOLCHAIN

riscv-arch-test/port-neorv32/framework_v2.0/riscv-target/neorv32/device/rv32i_m/C/Makefile.include, riscv-arch-test/port-neorv32/framework_v2.0/riscv-target/neorv32/device/rv32i_m/I/Makefile.include, riscv-arch-test/port-neorv32/framework_v2.0/riscv-target/neorv32/device/rv32i_m/M/Makefile.include, riscv-arch-test/port-neorv32/framework_v2.0/riscv-target/neorv32/device/rv32i_m/Zifencei/Makefile.include, riscv-arch-test/port-neorv32/framework_v2.0/riscv-target/neorv32/device/rv32i_m/privilege/Makefile.include, sim/ghdl_sim.sh
Instead of executing the simulation in the root of the repo, this PR modifies `sim/ghdl_sim.sh` for running it in subdir `sim` and generating intermediate files in `sim/build`.
=> [sim/ghdl] use --workdir=build

sw/isa-test/port-neorv32/device/rv32i_m/C/Makefile.include, sw/isa-test/port-neorv32/device/rv32i_m/I/Makefile.include, sw/isa-test/port-neorv32/device/rv32i_m/M/Makefile.include, sw/isa-test/port-neorv32/device/rv32i_m/Zifencei/Makefile.include, sw/isa-test/port-neorv32/device/rv32i_m/privilege/Makefile.include
This PR adds `time -v` to the architecture test simulation calls, in order to measure the execution time and resource usage.
Most of the tests need 20-60s, which is reasonable. However, `I/jal-01` needs 17 minutes!  @stnolting, is that expected? Might that be caused by some bug?
=> [riscv-arch-test] measure execution time of each test

docs/datasheet/soc_slink.adoc
Also explicitly state which end controls which signal.
=> Fix source/sink mixup in SLINK docs

.github/impl.dockerfile, .github/sim.dockerfile, .github/workflows/Containers.yml, .github/workflows/Implementation.yml, .github/workflows/Processor.yml
Instead of installing the dependencies in each CI workflow and job, in this PR a 'Containers' workflow is added for building custom images to be used in this repo. Precisely, images `ghcr.io/stnolting/neorv32/sim` and `ghcr.io/stnolting/neorv32/impl` are built and pushed. Then, in other workflows, those images are used.
Workflow 'Containers' is not triggered by pushes or PRs. It is executed weekly, and it can be triggered manually.
Note that we are currently using container images already. Therefore, the only advantage of this PR for now is avoiding the installation of the RISCV toolchain. However, it sets the foundation for future enhancements, such as the ones in #110.
=> [ci] add workflow 'Containers'

docs/datasheet/soc_sysinfo.adoc
- Remove the double documentation for bit 15 (SYSINFO_FEATURES_HW_RST) of the SYSINFO_FEATURES register.
- Add missing formatting (leading underscores) to the CPU_SYSINFO register table.
=> SYSINFO documentation fixups

docs/userguide/content.adoc
Close #155.
In this PR, section 'Simulating the Processor' from the User Guide is updated.
- An introduction is added.
- (sub)section titles are changed.
- The section about VUnit is enhanced.
- Some paragraphs are reformatted, some links are fixed, etc.
/cc @LarsAsplund
=> [docs/userguide] update section 'Simulating the Processor'

setups/osflow/Makefile, setups/osflow/filesets.mk
As the title explains, currently there is a default NEORV32_MEM_SRC variable in `filesets.mk`, which is overriden for some boards/examples. In this PR, that is changed so that no default NEORV32_MEM_SRC is defined. Therefore, for each board/design, the user needs to explicitly select whether to use the default description or some custom sources (such as SPRAM on UP5K).
=> [setups/osflow/filesets] do not provide default NEORV32_MEM_SRC, require it to be explicitly set

.github/impl.dockerfile, .github/sim.dockerfile
This is in preparation for #110.
In this PR, [pydoit](https://pydoit.org/) is added to the dockerfiles used in CI. No further modification is done yet, so doit is actually unused. However, it allows users providing their own `dodo.py` file to use containers `ghcr.io/umarcor/neorv32/sim` and/or `ghcr.io/umarcor/neorv32/impl`.
=> add pydoit to custom dockerfiles

.github/impl.dockerfile, .github/sim.dockerfile
Debian Bullseye was released in August. This PR updates the containers for them to be based on that instead of Debian Buster.
=> [containers] update from Debian Buster to Debian Bullseye

.github/workflows/Documentation.yml, .gitignore, do.py, dodo.py
This is a subset of #110.
As an initial approach to using [pydoit](https://pydoit.org/), in this PR a `do.py` file is added. It includes a single task for uploading the documentation to GitHub Pages. So, instead of having those commands hardcoded in the workflow file, the workflow executes the task through doit.
doit can be executed as a CLI tool (which will search for a `dodo.py`) or it can be used through an executable script. In this case, I made the script executable and I named it `do.py`. As a result, `./do.py` is equivalent to `doit -f do.py`.
=> [doit] add initial doit file; add task DeployToGitHubPages

.github/workflows/Documentation.yml, do.py
Similarly to #162, this is a subset of #110.
Instead of calling make in the Documentation workflow, a task named Documentation is added to the `do.py` file.
For now, the following are equivalent:
- `./do.py Documentation`
- `doit -f do.py Documentation`
- `make -C docs`
In upcoming PRs, we might remove `docs/Makefile` and replace it with more specific doit tasks.
=> [doit] add task Documentation

.github/workflows/riscv-arch-test.yml, do.py
Similarly to #162 and #163, this is a subset of #110.
Instead of calling `sim/run_riscv_arch_test.sh` directly, it is wrapped in a doit task named RunRISCVArchitectureTests. An option (`-s`|`--suite`) of type "choice" allows selecting which tests to run.
In upcoming PRs, we might remove `sim/run_riscv_arch_test.sh` and replace it with more specific doit/python code. Particularly, https://github.com/stnolting/neorv32/blob/master/sim/run_riscv_arch_test.sh#L49-L61 might be enhanced by using enums/dictionaries.
=> [doit] add task RunRISCVArchitectureTests

CHANGELOG.md, rtl/core/neorv32_package.vhd, rtl/system_integration/neorv32_ProcessorTop_stdlogic.vhd, rtl/system_integration/neorv32_SystemTop_axi4lite.vhd
Fix routing of the UART1 rx/tx signals in the AXI4Lite system integration top.
=> :bug: [rtl/system_integration] fix uart1 rx/tx signals

CHANGELOG.md, README.md, docs/datasheet/cpu.adoc, docs/datasheet/soc.adoc, docs/datasheet/soc_buskeeper.adoc, rtl/core/neorv32_bus_keeper.vhd, rtl/core/neorv32_package.vhd, rtl/core/neorv32_top.vhd, sw/example/processor_check/main.c, sw/lib/include/neorv32.h, sw/lib/source/neorv32_rte.c
This PR add a read-only memory-mapped status register to the `BUSKEEPER` module. The status register gives additional information regarding the actual cause of an instruction / data-load / data-store bus access fault exception:
* `BUSKEEPER_ERR_TYPE` = `0`: error caused by device itself (by asserting the `err_o` signal)
* `BUSKEEPER_ERR_TYPE` = `1`: error caused by bus timeout (accessed device is not responding at all)
* `BUSKEEPER_ERR_SRC` = `0`: error caused during access to processor-internal module
* `BUSKEEPER_ERR_SRC` = `1`: error caused during access via processor-external bus interface
✔️ This PR is fully backwards compatible - the memory-mapped BUSKEEPER register uses a previously unused IO space address (`0xffffff7C`).
=> [BUSKEEPER] add memory-mapped status register

.github/workflows/Windows.yml
Option 'pacboy' added to the latest release of setup-msys2 allows to make the syntax slightly cleaner.
=> [ci] use option 'pacboy' to simplify workflow 'Windows'

CHANGELOG.md, docs/datasheet/cpu.adoc, rtl/core/neorv32_cpu.vhd, rtl/core/neorv32_cpu_alu.vhd, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_package.vhd
Major CPU logic optimization and code clean-ups.
* closed several illegal instruction word holes (system/environment instructions, ALU instructions, FENCE instructions) - some illegal instruction word combinations were not correctly identified by the CPU
* reworked ALU (function select muxes)
* extension-specific instruction decoding logic (like bit-manipulation) is removed from the CPU if the extension is not enabled
* clean-up of CPU's control engine - simpler states (less logic) and more comments
=> CPU logic optimization

CHANGELOG.md, docs/datasheet/soc_twi.adoc, rtl/core/neorv32_package.vhd, rtl/core/neorv32_twi.vhd, sw/example/demo_twi/main.c, sw/example/processor_check/main.c, sw/lib/include/neorv32.h, sw/lib/include/neorv32_twi.h, sw/lib/source/neorv32_twi.c
This PR removes the `TWI_CTRL_CKSTEN` flag (bit 7) from the TWI control register. Clock stretching is now always enabled and bit 7 of the control register is hardwired to zero.
=> [TWI] remove clock-stretching enable flag

setups/osflow/Makefile
As reported by @zipotron in #213, variables passed when calling make are not honored. This PR ensures that overriding them is possible.
=> setups/osflow/Makefile: support overriding variables

CHANGELOG.md, docs/datasheet/soc_trng.adoc, rtl/core/neorv32_package.vhd, rtl/core/neorv32_trng.vhd, sw/example/demo_trng/main.c, sw/lib/source/neorv32_trng.c
This PR is a rework of the processor-internal TRNG module. There is a completely new architecture of the entropy source that requires less hardware while improving random number quality. A detailed description and evaluation of the reworked TRNG will be made available in the "spin-off" repository [stnolting/neoTRNG](https://github.com/stnolting/neoTRNG).
✔️ The changes in this PR are fully backwards-compatible (no change of the software interface).
=> Rework TRNG module

docs/userguide/content.adoc
Tried the example first with minicom, which didn't get the bootloader interrupt in the beginning. Somehow I couldn't figure out uploading files with screen either. GTKTerm seems to work perfectly fine. Maybe this saves someone else 10-30 minutes of searching.
Also fixed a minor typo in the preceding sentence.
=> Added a example serial terminal program for Linux 

CHANGELOG.md, docs/datasheet/on_chip_debugger.adoc, rtl/core/neorv32_debug_dtm.vhd, rtl/core/neorv32_package.vhd
This PR reworks the JTAG signal synchronization logic of the DTM (debug transfer module). The pre-PR version of the DTM did not fully comply with the JTAG interface timing requirements (sample TDO and TMS on the _rising_ edge of TCK, update TDO on the _falling_ edge of TCK).
This seems to cause some compatibility troubles with the JLINK EDU as reported by @emb4fun. It would be great if you could test the reworked DTM :wink:
This PR also includes some code clean-ups of the DTM code and also removes the number of recommended debugger wait states to allow faster JTAG operations.
=> [On-Chip Debugger] Fix JTAG timing

sw/lib/source/neorv32_gpio.c
This function should read from:
- NEORV32_GPIO.INPUT_LO and NEORV32_GPIO.INPUT_HI
But previously it was reading from:
- NEORV32_GPIO.OUTPUT_LO and NEORV32_GPIO.OUTPUT_HI
So it wasn't working correctly. The function neorv32_pin_get() was
reading the correct values (from INPUT instead of OUTPUT) and thus it
was working correctly.
=> Fix neorv32_gpio_port_get()

CHANGELOG.md, rtl/core/neorv32_bus_keeper.vhd, rtl/core/neorv32_package.vhd, rtl/core/neorv32_wishbone.vhd, sim/neorv32_tb.vhd, sim/simple/neorv32_tb.simple.vhd
This PR fixes a bug in the Wishbone timeout counter.
Wishbone timeout configurations (via the `MEM_EXT_TIMEOUT` generic) that are a power of two (like 256) caused an **immediate** timeout exception since the timeout counter was one bit short.
The same problem occurred in the BUSKEEPER's timeout counter. However, this bug did not actually appeared because the default BUSKEEPER timeout is not a power of two.
Thanks to @emb4fun for identifying this bug. :+1:
=> :bug: Fix Wishbone timeout bug

CHANGELOG.md, docs/datasheet/soc_sysinfo.adoc, docs/userguide/simulating_the_processor.adoc, rtl/core/neorv32_package.vhd, rtl/core/neorv32_sysinfo.vhd, sw/example/processor_check/main.c, sw/lib/include/neorv32.h
This PR adds a new flag to the SYSINFO module to check if the processor is being simulated:
`NEORV32_SYSINFO.SOC` bit 13: _SYSINFO_SOC_IS_SIM_, set if processor is being simulated
The state of this flag cannot be guaranteed for _all_ platforms as it depends on the toolchains 'pragma' support (works with GHDL, Intel Quartus, Lattice Radiant):
```vhdl
-- Check if we're inside the Matrix -------------------------------------------------------
-- -------------------------------------------------------------------------------------------
constant is_simulation_c : boolean := false -- seems like we're on real hardware
-- pragma translate_off
-- synthesis translate_off
-- synthesis synthesis_off
-- RTL_SYNTHESIS OFF
or true -- this MIGHT be a simulation
-- RTL_SYNTHESIS ON
-- synthesis …
```
=> Add SYSINFO flag to check if processor is being simulated

README.md, docs/datasheet/overview.adoc, docs/datasheet/soc.adoc, docs/datasheet/software.adoc, sw/README.md, sw/svd/README.md, sw/svd/neorv32.svd
This PR is an attempt to provide a SVD file for the NEORV32. The idea comes from the project's gitter chat.
The file will be `sw/svd/neorv32.svd`.
The file format is compatible to ARM's CMSIS-SVD format (Apache-2.0 License ).
* ARM/Keil documentation: https://www.keil.com/pack/doc/CMSIS/SVD/html/index.html
* CMSIS 4.4 example: https://github.com/ARM-software/CMSIS/blob/master/CMSIS/SVD/ARM_Example.svd
* RISC-V (SiFive) SVD example: https://github.com/riscv-rust/e310x/blob/master/e310x.svd
* Syntax verified using [SVDConv utility](https://www.keil.com/pack/doc/CMSIS/SVD/html/svd_SVDConv_pg.html)
* Verified C-header also generate by SVDConv utility
The NEORV32 SVD file is (located in) `sw/svd/neorv32.svd`. Right now, it just contains a minimal CPU description and the registers of the PWM …
=> Add a System View Description (SVD) file

sw/example/demo_slink/main.c, sw/example/demo_slink/makefile
This PR adds a demo program for the SLINK module (`sw/example/demo_slink`; written for the updates from #236).
It provides an interactive UART console to trigger SLINK read/write transactions by hand:
```
<<< SLINK Access Test Program >>>
This program allows to create SLINK transfers by hand.
Type 'help' to see the help menu.
SLINK_ACCESS:> help
Available commands:
help     - show this text
status   - show SLINK HW status
setup    - configure SLINK module
read     - read from SLINK channel
write    - write to SLINK channel
irq_mode - toggle SLINK IRQ mode
irq_en   - toggle SLINK IRQ enable
reset    - reset SLINK module
Configure the SLINK module using 'setup'. Then transfer data using 'read' and 'write'.
SLINK_ACCESS:> setup
Select SLINK access mode:
n: non-blocking access -> check SLINK …
```
=> [sw/example] add SLINK demo program

CHANGELOG.md, README.md, docs/datasheet/cpu.adoc, rtl/core/neorv32_cpu_cp_muldiv.vhd, rtl/core/neorv32_package.vhd
This PR optimizes the logic of the CPU's MULDIV co-processor (`M` ISA extension):
* multiplications and divisions are 1 cycle faster
* reduced hardware utilization
=> MULDIV optimization

CHANGELOG.md, README.md, docs/datasheet/cpu.adoc, docs/datasheet/soc_wdt.adoc, rtl/core/neorv32_cpu.vhd, rtl/core/neorv32_cpu_cp_muldiv.vhd, rtl/core/neorv32_package.vhd, rtl/core/neorv32_top.vhd, rtl/core/neorv32_wdt.vhd, sw/lib/include/neorv32.h, sw/svd/neorv32.svd
This PR adds two new flags to the Watchdog (WDT) control register (the bits were previously unused):
* `NEORV32_WDT.CTRL` bit 9: _WDT_CTRL_DBEN_ [r/w] - set to 1 to allow watchdog operation (timeout counter increment) even when the CPU is in debug mode (active OCD session), :warning: in the current version the WDT _always_ increments it's counter
* `NEORV32_WDT.CTRL` bit 10: _WDT_CTRL_HALF_ [r/-] - set when at least half of the max. timeout value has been reached
✔️ the changes in this PR are fully backwards-compatible
=> Watchdog [WDT]: add option to enable/disable WDT during debugging

CHANGELOG.md, docs/datasheet/cpu.adoc, rtl/core/neorv32_cpu_cp_muldiv.vhd, rtl/core/neorv32_package.vhd
This PR improves the CPU's MULDIV co-processor and is another optimization of #238:
* divisions are 1 cycle faster
* fast multiplications (using DPS blocks, enabled by `FAST_MUL_EN` generic) are 1 cycles faster
* slightly reduced resource utilization
=> Faster mul/div operations

rtl/core/neorv32_package.vhd
This PR fixes #242 by using a deferred constant. It shouldn't change anything except allowing to compile the package with Questa, which failed before.
=> Fix compile error with questa, for issue #242

docs/datasheet/soc.adoc, docs/datasheet/soc_pwm.adoc, docs/datasheet/soc_xirq.adoc, rtl/core/neorv32_package.vhd, rtl/core/neorv32_pwm.vhd, rtl/core/neorv32_top.vhd, rtl/core/neorv32_xirq.vhd, rtl/processor_templates/neorv32_ProcessorTop_Minimal.vhd, rtl/processor_templates/neorv32_ProcessorTop_MinimalBoot.vhd, rtl/processor_templates/neorv32_ProcessorTop_UP5KDemo.vhd, rtl/system_integration/neorv32_ProcessorTop_stdlogic.vhd, rtl/system_integration/neorv32_SystemTop_AvalonMM.vhd, rtl/system_integration/neorv32_SystemTop_axi4lite.vhd, setups/radiant/UPduino_v3/neorv32_upduino_v3_top.vhd
This PR modifies the top entity's `pwm_o` and `xirq_i` ports. Both ports have now a **_fixed size_** that corresponds to the maximum value of the according configuration generics (rather than being size-defined by those generics). I think this is more straight-forward as all other IOs (except for the CFS ones) have a fixed size, too.
```vhdl
-- PWM (available if IO_PWM_NUM_CH > 0) --
pwm_o : out std_ulogic_vector(59 downto 0); -- pwm channels
```
```vhdl
-- External platform interrupts (available if XIRQ_NUM_CH > 0) --
xirq_i : in  std_ulogic_vector(31 downto 0) := (others => 'L'); -- IRQ channels
```
=> ⚠️ Make PWM and XIRQ IOs fixed-sized

rtl/core/mem/README.md, rtl/core/mem/neorv32_dmem.legacy.vhd, rtl/core/mem/neorv32_imem.legacy.vhd
This PR renames the legacy HDL style memory files in `rtl/core/mem` from `*.cyclone2.vhd` to `*.legacy.vhd` to avoid confusion. These files are also platform-agnostic and _not_ optimized for a certain FPGA architecture.
=> [rtl/core/mem] Rename legacy-style memory files

.github/workflows/riscv-arch-test.yml, docs/datasheet/cpu.adoc, sim/run_riscv_arch_test.sh, sim/simple/neorv32_imem.simple.vhd
This PR makes some minor reworks of the `riscv-arch-test` GitHub actions workflow:
* use _sim_ package (mainly for RISC-V GCC and GHDL)
* add status note to sim-only IMEM (ROM)
* remove `rtl/core/mem/*.legacy.vhd` files for simulation
* skip `I/jmp-01` test case - the GHDL version used for the architecture tests does not proceed here somehow (using a constant array with more than 400000 elements)
=> [.github/riscv-arch-test] Fix / rework

CHANGELOG.md, docs/datasheet/soc_buskeeper.adoc, rtl/core/neorv32_bus_keeper.vhd, rtl/core/neorv32_cpu_bus.vhd, rtl/core/neorv32_package.vhd, rtl/core/neorv32_top.vhd, sw/lib/include/neorv32.h, sw/svd/neorv32.svd
This PR adds a new feature to the BUSKEEPER module (triggered by @emb4fun):
When setting bit 16 (_NEORV32_BUSKEEPER_) of the control register (`NEORV32_BUSKEEPER.CTRL`) the BUSKEEPER will issue a bus exception for all accesses to address `0x00000000` (instruction fetch / load data / store data). This can help to identify program bugs where uninitialized pointers are used.
=> [BUSKEEPER] Add NULL address check option

CHANGELOG.md, docs/datasheet/overview.adoc, docs/datasheet/soc_xip.adoc, rtl/core/neorv32_package.vhd, rtl/core/neorv32_xip.vhd, sw/example/demo_xip/main.c, sw/lib/include/neorv32.h, sw/lib/include/neorv32_xip.h, sw/lib/source/neorv32_xip.c, sw/svd/neorv32.svd
This PR is a rework of the processor's **Execute in Place (XIP)** module (#244).
* Control register changes
* removed QSPI mode enable (not implemented **_yet_** :wink:)
* rearranged flags
* removed XIP mode busy flag
* added flag to explicitly enable the module's SPI chip-select port (allows to send dummy clocks without actually enabling the SPI flash)
Further hardware changes:
* removed hardware-based sending of dummy SPI clocks (is now done by the XIP's software library functions)
* removed "inter-transmission" pause from SPI PHY - faster SPI accesses
* reduces hardware footprint: only ~300 LEs on an Intel Cyclone IV
---------------------------
:gear: "Final" pre-defined software functions for using the XIP module:
```c
int neorv32_xip_available(void);
int neorv32_xip_init(uint8_t …
```
=> :warning: [XIP] reworked execute in place module

CHANGELOG.md, docs/datasheet/soc_spi.adoc, docs/datasheet/soc_xip.adoc, rtl/core/neorv32_package.vhd, rtl/core/neorv32_spi.vhd, rtl/core/neorv32_xip.vhd, sw/lib/include/neorv32.h, sw/lib/include/neorv32_spi.h, sw/lib/include/neorv32_xip.h, sw/lib/source/neorv32_spi.c, sw/lib/source/neorv32_xip.c, sw/svd/neorv32.svd
This PR adds a "high-speed" SPI mode to the SPI and the XIP module. When enabled, the default three-bit clock prescaler select is ignored and the SPI clock operates at maximum speed, which is half of the processor clock (`processor_clk / 2`). Note: using only the clock prescaler select the maximum SPI clock frequency is `processor_clk / 4`.
To enable the high-speed SPI mode a new flag has been added to the modules control register (those bits were previously unused):
* `NEORV32_SPI.CTRL` bit 16 "_SPI_CTRL_HIGHSPEED_"
* `NEORV32_XIP.CTRL` bit 26 "_XIP_CTRL_HIGHSPEED_"
High-speed mode enable and disable functions have been added to the according software libraries.
✔️ This PR is fully backwards-compatible.
=> [SPI & XIP] add high-speed SPI mode option

setups/osflow/synthesis.mk
Close #245
Refs:
- im-tomu/fomu-workshop#600
- YosysHQ/yosys#3137
- YosysHQ/yosys#3109
=> setups/osflow/synthesis: recent versions of yosys need command 'read_verilog'

CHANGELOG.md, docs/datasheet/soc_gpio.adoc, rtl/core/neorv32_gpio.vhd, rtl/core/neorv32_package.vhd, rtl/core/neorv32_top.vhd, sw/lib/include/neorv32.h
This PR modifies the GPIO module to raise a _store bus access error exception_ if software tries to write to the read-only INPUT registers (`NEORV32_GPIO.INPUT_LO` and `NEORV32_GPIO.INPUT_HI`). The BUSKEEPER will indidcate a device error ("DEVICE_ERR") in this case.
=> [GPIO] raise bus exception if writing to INPUT registers

CHANGELOG.md, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_package.vhd
This PR provides a rework of the CPU's issue engine to reduce it's resource requirements.
The issue engine is located right between the pipeline front end (instruction fetch and instruction prefetch buffer) and the actual execution unit. The issue engine is responsible for decoding compressed 16-bit instruction (RISC-V `C` extension) and for handling unaligned 32-bit instructions. The changes from this PR highly reduce the size of this engine (~100 LUTs less on an Intel Cyclone IV FPGA). Note: the issue engine is only relevant if the `C` ISA extension is implemented (enabled via the `CPU_EXTENSION_RISCV_C` generic).
Furthermore, this PR includes some minor code clean-up of the CPU's control engine.
✔️ Changes in this PR are fully backwards-compatible.
=> [rtl/core] rework CPU issue engine (area optimization)

docs/userguide/sw_toolchain_setup.adoc
fix(doc): Closes #257 and changes `export PATH:$PATH:/opt/riscv/bin` to
`export PATH=$PATH:/opt/riscv/bin`.
=> [DOC] User Guide - 1.3. Installation

CHANGELOG.md, docs/datasheet/cpu.adoc, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_cpu_cp_bitmanip.vhd, rtl/core/neorv32_package.vhd, sw/example/bitmanip_test/main.c, sw/example/bitmanip_test/neorv32_b_extension_intrinsics.h
This PR adds another sub-extension to the recently ratified **RISC-V bit-manipulation ISA extension "`B`"**:
* `Zbs` - single-bit instructions
The NEORV32 CPU now supports three of the four `B` subsets (if the bit-manipulation is enabled by setting the `CPU_EXTENSION_RISCV_B` top generic _true_):
* ✔️ `Zbb` - basic bit-manipulation instructions
* ✔️ `Zba` - address-computation instructions
* ✔️ `Zbs` - single-bit instructions
* ❌ `Zbc` - carry-less multiplication instructions - not supported yet (but coming soon)
Since there is no upstream gcc support yet, `Zbs` intrinsics and emulation functions have been added to [`sw/example/bitmanip_test/neorv32_b_extension_intrinsics.h`](https://github.com/stnolting/neorv32/blob/master/sw/example/bitmanip_test/neorv32_b_extension_intrinsics.h) to …
=> [B ISA extension] add single-bit instructions (Zbs) support

CHANGELOG.md, README.md, docs/datasheet/cpu.adoc, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_cpu_cp_bitmanip.vhd, rtl/core/neorv32_package.vhd, sw/example/bitmanip_test/main.c, sw/example/bitmanip_test/neorv32_b_extension_intrinsics.h
This PR is a follow-up of #259 and adds the last missing sub-extension to the CPU's **RISC-V bit-manipulation ISA extension "`B`"**:
* `Zbc` - carry-less multiplication instructions
The NEORV32 CPU now supports _all_ four `B` subsets (according to the recently frozen and ratified RISC-V bit-manipulation spec. v0.93/v1.00):
* ✔️ `Zbb` - basic bit-manipulation instructions
* ✔️ `Zba` - address-generation instructions
* ✔️ `Zbs` - single-bit instructions
* ✔️  `Zbc` - carry-less multiplication instructions
:books: A copy of the RISC-V `B` spec (v0.93) can be found in [docs/references](https://github.com/stnolting/neorv32/tree/master/docs/references).
Since there is no upstream gcc support yet, `Zbc` intrinsics and emulation functions have been added to …
=> [B ISA extension] add carry-less multiply instructions (Zbc) support

CHANGELOG.md, docs/datasheet/soc_cfs.adoc, rtl/core/neorv32_cfs.vhd, rtl/core/neorv32_package.vhd, sw/example/demo_cfs/main.c, sw/example/demo_cfs/makefile
This PR reworks the "user" logic of the default _Custom Functions Subsystem (CFS)_ hardware module and also adds a simple example program to illustrate how to use/access the CFS from software (-> `sw/example/demo_cfs`).
The default CFS now implements four exemplary memory-mapped registers that perform simple, combinatorial data transformations:
* binary to gray conversion
* gray to binary conversion
* bit reversal
* byte swap (Endianness conversion)
=> [CFS] add demo program

CHANGELOG.md, rtl/core/neorv32_cpu.vhd, rtl/core/neorv32_cpu_alu.vhd, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_cpu_cp_bitmanip.vhd, rtl/core/neorv32_cpu_cp_fpu.vhd, rtl/core/neorv32_cpu_cp_muldiv.vhd, rtl/core/neorv32_cpu_cp_shifter.vhd, rtl/core/neorv32_package.vhd
This PR adds four additional co-processor slots (4..7) to the CPU's ALU. The new co-processor slots are not used yet and are reserved for future (ISA) extensions. Slot 4 is going to be used to implement a **Custom Functions Unit (CFU)** that allows to implement _custom RISC-V instructions_.
With this PR the ALU contains up to eight co-processors:
* **CP0**: shift operation, `I`/`E` base ISA, _mandatory_
* **CP1**: multiply/divide, `M` ISA extension, _optional_
* **CP2**: bit-manipulation, `B` ISA extension, _optional_
* **CP3**: floating-point unit, `Zfinx` ISA extensions, _optional_
* **CP4**: empty slot, _reserved_
* **CP5**: empty slot, _reserved_
* **CP6**: empty slot, _reserved_
* **CP7**: empty slot, _reserved_
------------------------------
:bug: This PR also fixes a bug in the …
=> [rtl/core] add 4 additional CPU CP slots; fix bugs in CP arbitration logic

CHANGELOG.md, docs/datasheet/soc_bootrom.adoc, docs/datasheet/soc_imem.adoc, rtl/core/mem/neorv32_imem.default.vhd, rtl/core/mem/neorv32_imem.legacy.vhd, rtl/core/neorv32_boot_rom.vhd, rtl/core/neorv32_imem.entity.vhd, rtl/core/neorv32_package.vhd, rtl/core/neorv32_top.vhd, sim/simple/neorv32_imem.iram.simple.vhd, sim/simple/neorv32_imem.simple.vhd
This PR adds the `err_o` signal to the IMEM module(s). This signal is set if the IMEM is implemented as true ROM and software attempts to perform a write access to it, which will create a "device error".
If there is a write access to a read-only IMEM the [📚 default runtime environment trap handler](https://stnolting.github.io/neorv32/#_default_rte_trap_handlers) will output an error message (in this example: store 32-bit word to address 0x0000_0004):
```
<RTE> Store access fault [DEVICE_ERR] @ PC=0x0000016E, MTVAL=0x00000004 </RTE>
```
**edit**
This PR also add the `err_o` signal to the processor's BOOTROM.
---------
ℹ️ **Before this PR** write access to the IMEM also raised a bus exception by not asserting the IMEM's `ack_o` signal, which resulted in a "device timeout error":
```
<RTE> …
```
=> [rtl] add err_o signal to IMEM modules

CHANGELOG.md, docs/datasheet/cpu_csr.adoc, docs/datasheet/on_chip_debugger.adoc, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_package.vhd
As illustrated in https://github.com/riscv/riscv-debug-spec/issues/638 this PR hardwires the `dcsr.stopcount` bit to `1`. Thus, all standard CPU counters (`[m]cycle[h]` and `[m]instret[h]`) and all hardware performance monitor (HPM) counters are always _stopped_ during debugging (when the CPU is in debug mode).
Note that the `[m]time[h]` CSRs are not affected by this since they are a shadow copy of the MTIME system timer, which keeps running also during debugging (hence, `dcsr.stoptime` is hardwired to `0`).
=> [OCD] stop CPU counters during debugging

docs/datasheet/software.adoc, docs/datasheet/software_rte.adoc, docs/userguide/sw_toolchain_setup.adoc, sw/example/newlib_demo/main.c, sw/example/newlib_demo/makefile, sw/lib/source/syscalls.c
This PR is an addition of #275 and adds the following:
* a demo/test example program for newlib's system call functions (like `malloc` and `write`) in `sw/example/newlib_demo`
* new documentation for the _C Standard Library_ (which is newlib by default)
* some notes regarding newlib (especially when building the compiler toolchain from scratch)
=> Add newlib example program and documentation

CHANGELOG.md, docs/datasheet/cpu.adoc, docs/datasheet/cpu_csr.adoc, docs/datasheet/soc.adoc, docs/datasheet/soc_cfs.adoc, docs/datasheet/soc_gptmr.adoc, docs/datasheet/soc_neoled.adoc, docs/datasheet/soc_slink.adoc, docs/datasheet/soc_spi.adoc, docs/datasheet/soc_twi.adoc, docs/datasheet/soc_uart.adoc, docs/datasheet/soc_wdt.adoc, docs/datasheet/soc_xirq.adoc, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_package.vhd, sw/example/demo_gptmr/main.c, sw/example/demo_slink/main.c, sw/example/processor_check/main.c, sw/lib/source/neorv32_xirq.c
This PR fixes a bug that has been introduced in version `1.6.4.6` / PR #236: to clear a pending interrupt application software has to write **ZERO** (and not one!) to the according `mip` bit (according to the RISC-V privilege architecture specifications). Hence, the acknowledge/clear mask needs to be inverted.
=> 🐛 [rtl/core] fix bug in mip CSR clear/acknowledge

CHANGELOG.md, docs/datasheet/cpu.adoc, docs/datasheet/cpu_csr.adoc, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_package.vhd, sw/common/crt0.S, sw/example/processor_check/main.c, sw/lib/include/neorv32.h, sw/lib/include/neorv32_cpu.h, sw/lib/source/neorv32_cpu.c
This PR is another clean-up and optimization of the CPU's control unit.
✨ Additionally, this PR adds support for the RISC-V `mstatus.TW` flag. This flag is is used to control the execution of the `wfi` (wait for interrupt / sleep) instruction in less-privileged user-mode. When set, executing `wfi` in user-mode will raise an illegal instruction exception. When cleared, user-mode is allowed to execute `wfi`. If user-mode is not implemented the `mstatus.TW` flag is hardwired to zero.
ℹ️ The user-level hardware performance monitor CSRs are added to the hardware in order to simplifiy CSR address decoding. However, the user-level HPM CSRs `hpmcounter*[h]` are **NOT** implemented. Any access from any operation mode will raise an exception. Only machine-mode is allowed to use the HPMs via the …
=> [rtl] CPU code clean-up; add RISC-V mstatus.TW CSR bit

CHANGELOG.md, rtl/core/neorv32_cpu_bus.vhd, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_cpu_cp_bitmanip.vhd, rtl/core/neorv32_cpu_cp_fpu.vhd, rtl/core/neorv32_cpu_cp_muldiv.vhd, rtl/core/neorv32_cpu_cp_shifter.vhd, rtl/core/neorv32_cpu_regfile.vhd, rtl/core/neorv32_icache.vhd, rtl/core/neorv32_package.vhd, rtl/core/neorv32_slink.vhd, rtl/core/neorv32_top.vhd, rtl/core/neorv32_xirq.vhd
This PR changes the way the `*_reduce_f` functions from the NEORV32 package are used.
If the function result is used for **direct** signal assignment this can cause undefined (`'X'` or `'U'`) signal states, which might corrupt gate-level simulation.
Current (pre-PR):
```vhdl
some_signal <= or_reduce_f(another_signal);
```
Proposed (post-PR):
```vhdl
some_signal <= '1' when (or_reduce_f(another_signal) = '1') else '0';
```
Furthermore, synthesis seems to be able to do better optimizations when using the changes from this PR (at least Intel Quartus).
There are no _functional_ (real hardware) changes caused by this PR.
=> 🧪 try to fix *_reduce_f functions usage for gate-level simulation

CHANGELOG.md, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_package.vhd
This PR simplifies the VHDL code of the CPU _issue engine_, which is part of the CPU _front end_. It is responsible for decoding compressed instructions and generating a constant stream of 32-bit instructions.
=> rework of CPU's issue engine

CHANGELOG.md, docs/datasheet/cpu.adoc, rtl/core/neorv32_cpu_bus.vhd, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_cpu_decompressor.vhd, rtl/core/neorv32_package.vhd, sim/neorv32_tb.vhd, sw/example/processor_check/main.c, sw/lib/source/neorv32_rte.c
:chart_with_upwards_trend: This PR improves the overall efficiency of the CPU: the logic optimizations from this PR reduce the area costs of the CPU (~8% less) while also shortening the CPU's critical path (~12% higher f_max).
:lock: Furthermore, this PR closes further illegal instruction holes (illegal instruction words that where not correctly detected or that caused side effects even if identified as "illegal").
:bug: This PR also fixes a rare bug in the core of the NEORV32 runtime-environment (RTE): if the C-extensions is disabled, a malformed instruction word that uses an opcode from the RVC (compressed) instruction space would cause the computation of an incorrect return address.
=> [CPU] area and timing optimization; closing further illegal instruction holes

CHANGELOG.md, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_package.vhd
This small PR adds an AND-gate to the CSR read address bus. This eliminates unnecessary switching activity in the (large) CSR block as the read address is only propagated (from the instruction word) if there is an actual CSR access. (Somehow,) this also reduces area costs of the CSR system :wink:
=> add gate for CSR read address

CHANGELOG.md, docs/datasheet/cpu_csr.adoc, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_cpu_cp_shifter.vhd, rtl/core/neorv32_cpu_decompressor.vhd, rtl/core/neorv32_cpu_regfile.vhd, rtl/core/neorv32_package.vhd
This is another logic optimization PR: rework logic of the `C`-extension's compressed instruction de-compressor.
* closed further illegal `C` instruction encoding holes
* `mtval` CSR now provides the de-compressed 32-bit instruction word when an illegal instruction has been raised by executing an invalid compressed instruction (instead of just showing all-zero)
* code cleanups (removing legacy stuff)
=> Rework `C` decompressor

CHANGELOG.md, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_cpu_regfile.vhd, rtl/core/neorv32_package.vhd, sw/common/crt0.S
This PR reworks the handling of register `x0` (= "zero"), which is always returns zero.
We do not want to implement AND-gates to set the register source operands (`rs1` & `rs2`) to zero when reading from register `x0` since this would cost ~64 LUTs and would also increase the critical path. Hence, register zero is part of the register file and will also be mapped to the register file-absorbing block RAM - so register `x0` is a _physical register_. We do not want to rely on BRAM initialization to ensure that `x0` is always zero. Thus, a special logic is required.
The current register file checks all write accesses if they target register zero. For any write access to this register, the actual read data is set to zero. This increases the critical path (register file -> ALU -> register file) …
=> Rework register file's "zero" register

CHANGELOG.md, docs/datasheet/soc.adoc, docs/userguide/application_specific_configuration.adoc, rtl/core/neorv32_cpu.vhd, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_package.vhd, rtl/core/neorv32_top.vhd, sim/neorv32_tb.vhd, sim/simple/neorv32_tb.simple.vhd
This is just another optimization PR that turns the CPU's front-end (instruction fetch engine) into a synchronous state machine. This shortens the critical path of the memory system (central memory/peripheral bus) and also reduces area costs.
**🎉 reaching >130MHz on an Intel Cyclone IV FPGA (medium SoC configuration) without constraints**
=> [rtl] make CPU front-end synchronous

CHANGELOG.md, rtl/core/neorv32_cpu_cp_shifter.vhd, rtl/core/neorv32_package.vhd
By default, the CPU uses a bit-serial approach for shift instructions (requiring up to 31 additional cycles). If `FAST_SHIFT_EN` is _true_ a 2-cycle barrel-shifter is implemented instead. This PR optimizes the timing of the barrel shifter by moving the internal pipeline register.
Furthermore, the _register balancing_ of the synthesis tool should now be able to move this pipeline register to further improve timing.
=> [rtl] optimize CPU barrel shifter timing

CHANGELOG.md, rtl/core/neorv32_cpu_cp_muldiv.vhd, rtl/core/neorv32_package.vhd
Just another optimization PR. This time targeting the CPU's multiplier/divider unit (`M` ISA extension):
* complete code rework
* less area costs
* shortened critical path
* cleaner code
=> [rtl] optimize CPU mul/div unit

CHANGELOG.md, docs/datasheet/cpu_csr.adoc, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_package.vhd, sw/lib/include/neorv32.h, sw/lib/source/neorv32_rte.c
This PR adds further flags to the CPU's custom `mxisa` CSR:
* _CSR_MXISA_IS_SIM_ (bit 20): is CPU being simulated right now? (via package's `is_siulation_c` auto-constant)
* _CSR_MXISA_HW_RESET_ (bit 21): dedicated hardware reset of all CPU core registers? (via packages's `dedicated_reset_c` constant)
=> Add further mxisa CSR flags

CHANGELOG.md, docs/datasheet/soc_trng.adoc, docs/userguide/simulating_the_processor.adoc, rtl/core/neorv32_package.vhd, rtl/core/neorv32_trng.vhd, sim/neorv32_tb.vhd, sim/simple/neorv32_tb.simple.vhd, sw/example/demo_trng/main.c, sw/lib/include/neorv32.h, sw/lib/include/neorv32_trng.h, sw/lib/source/neorv32_trng.c
This PR upgrades the TRNG module to the latest all-new [neoTRNG V2](https://github.com/stnolting/neoTRNG). 🚀
* much better random number quality
* reworked architecture of entropy source
* integrated post-processing for improved whitening
* simulation mode: implements a pseudo-RNG (LFSRs) instead of the ring oscillators (comb. loops) to allow using the TRNG also in simulation - but of course with very bad (!!!) random number quality
* added explicit flag to the TRNG's control register to check for simulation mode (bit 29: _TRNG_CTRL_SIM_MODE_)
=> update to new neoTRNG v2

CHANGELOG.md, docs/datasheet/cpu.adoc, rtl/core/neorv32_cpu_cp_bitmanip.vhd, rtl/core/neorv32_package.vhd
This is another code clean-up and optimization PR - this time targeting the CPU's `B` extension (bit-manipulation) co-processor.
* cleaner code
* slightly less area requirements
* faster execution of shift and shift-related (like `CLZ`) operations; one cycle less latency
=> Cleanup bitmanip co-processor

CHANGELOG.md, rtl/core/neorv32_bus_keeper.vhd, rtl/core/neorv32_package.vhd
Fixes #314. @GideonZ
The BUSKEEPER raises an _internal timeout error_ if an external access (via Wishbone) has the same access latency as there are maximum _internal_ timeout cycles (`max_proc_int_response_time_c`).
=> :bug: fix buskeeper timeout error

CHANGELOG.md, docs/datasheet/soc.adoc, docs/datasheet/soc_trng.adoc, rtl/core/neorv32_package.vhd, rtl/core/neorv32_top.vhd, rtl/core/neorv32_trng.vhd, rtl/system_integration/neorv32_ProcessorTop_stdlogic.vhd, rtl/system_integration/neorv32_SystemTop_AvalonMM.vhd, rtl/system_integration/neorv32_SystemTop_axi4lite.vhd, sim/neorv32_tb.vhd, sim/simple/neorv32_tb.simple.vhd, sw/lib/include/neorv32.h, sw/lib/include/neorv32_trng.h, sw/lib/source/neorv32_trng.c, sw/svd/neorv32.svd
This PR adds an optional and configurable data FIFO to the processor's _true random number generator_ module (**TRNG**).
The TRNG requires at least 16x8=128 cycles to generate a new RND data bytes (see [stnolting/neoTRNG](https://github.com/stnolting/neoTRNG) for more information). The new optional FIFO provides something like a "random data pool" by constantly sampling data from the TRNG core.
* The TRNG FIFO is configured by the new top generic `IO_TRNG_FIFO`: default value is 1, minimal value is 1, has to be a power of two.
* The FIFO can be cleared at any time either by disabling and re-enabling the TRNG module or via the new control register bit _TRNG_CTRL_FIFO_CLR_ (`NEORV32_TRNG.CTRL` bit 28; write-only, auto clears).
=> [TRNG] add optional/configurable data FIFO

docs/datasheet/soc.adoc, docs/datasheet/software.adoc, sw/common/crt0.S
When the bootloader executes an application from XIP, the startup code should not disable the XIP unit, otherwise the application will crash.
=> crt0.S: Do not clear XIP control registers except in bootloader mode

docs/datasheet/software.adoc, sw/common/crt0.S, sw/common/neorv32.ld
This PR modifies the default NEORV32 linker script and start-up code (crt0):
* all relevant sections start and end on a 32-bit (word) aligned boundary
* crt0 can use word-level memory operations instead of byte-level memory operations to initialize `.data` and clear `.bss` sections (faster booting / start-up!)
=> [linker script, crt0] align all sections to 32-bit boundaries

docs/datasheet/software.adoc, sw/common/crt0.S, sw/common/neorv32.ld, sw/example/hello_cpp/main.cpp, sw/example/hello_cpp/makefile
As promised, hereby the pull request with the necessary changes to the crt0.s and linker script to support the proper initialization of C++ objects by calling the constructors. A small demo shows that the static objects have been initialized properly.
=> Constructors

CHANGELOG.md, docs/userguide/debugging_with_ocd.adoc, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_package.vhd, sw/example/processor_check/main.c
This PR aims to fix the collision of synchronous exceptions and asynchronous exceptions (interrupt) as described in #325 by @GideonZ. PR #326 might also fix that issue.
=> 🐛 Fix sync. vs. async. exception collision

CHANGELOG.md, rtl/core/neorv32_package.vhd, rtl/core/neorv32_spi.vhd, rtl/core/neorv32_xip.vhd
This PR fixes the SPI phase offset problem (between SPI clock and SPI data_in/data_out) as described in #335 by @andkae. The XIP module is also affected by this bug and is also fixed by this PR.
ℹ️ This bug is only relevant only when using the SPI/XIP interface at very high clock speeds that are close to the processor's main clock (small clock prescaler or high-speed mode enabled).
=> :bug: fix SPI & XIP clock phase offset

CHANGELOG.md, docs/datasheet/soc_wishbone.adoc, rtl/core/neorv32_package.vhd, rtl/core/neorv32_wishbone.vhd
This is a rather small PR that adds an "operand gating" function to the external Wishbone interface.
All outgoing signals (seen from the processor) will not change at all when there is no active Wishbone access. This might reduce switching activity in the external memory system and makes inspecting Wishbone transactions in simulation much clearer.
=> [rtl] add Wishbone output "gating"

CHANGELOG.md, docs/datasheet/soc.adoc, docs/datasheet/soc_wdt.adoc, rtl/core/neorv32_package.vhd, rtl/core/neorv32_top.vhd, rtl/core/neorv32_wdt.vhd, sw/lib/include/neorv32.h, sw/lib/source/neorv32_wdt.c, sw/svd/neorv32.svd
This PR reworks the processor's internal reset generator system and also the behavior of the watchdog's "lock" feature.
The reset generator system has been split into an _external_ and an _internal_ system. The external reset is triggered by the processor's `rstn_i` signal while the internal reset is triggered by the processor's `rstn_i` signal, the watchdog or the on-chip debugger.
Whenever a valid reset request occurs (internal or external) the reset generator ensures that the reset applied to the system is active for at least 4 cycles. Furthermore, the reset applied to system will be release on _falling_ edge of the system clock to avoid metastable situation (= reset is de-asserted during a rising edge). More information can be found in this nice article: …
=> [rtl] rework reset system

CHANGELOG.md, docs/datasheet/soc.adoc, docs/datasheet/soc_wishbone.adoc, rtl/core/neorv32_package.vhd, rtl/core/neorv32_top.vhd, rtl/core/neorv32_wishbone.vhd, rtl/system_integration/neorv32_ProcessorTop_stdlogic.vhd, rtl/system_integration/neorv32_SystemTop_AvalonMM.vhd, rtl/system_integration/neorv32_SystemTop_axi4lite.vhd, sim/neorv32_tb.vhd, sim/simple/neorv32_tb.simple.vhd
This PR adds another configuration option for the external memory interface (**Wishbone**). By default, all incoming and outgoing Wishbone signals are registered to allow easy timing closure even when using complex (combinatorial) Wishbone interconnection networks.
The processor already provides the `MEM_EXT_ASYNC_RX` option to omit the register stage for incoming signals (seen from the processor). The new `MEM_EXT_ASYNC_TX` option now allows to also omit the register stage for outgoing signals.
Each enabled option will reduce the external memory interface latency by 1 cycle. If both options are enabled an external memory can be accessed with the same latency as any processor-internal memory.
=> [rtl] add "async TX" Wishbone option

CHANGELOG.md, docs/datasheet/cpu_csr.adoc, rtl/core/neorv32_cpu.vhd, rtl/core/neorv32_cpu_bus.vhd, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_cpu_cp_bitmanip.vhd, rtl/core/neorv32_cpu_cp_muldiv.vhd, rtl/core/neorv32_cpu_cp_shifter.vhd, rtl/core/neorv32_package.vhd, rtl/core/neorv32_top.vhd, rtl/core/neorv32_wishbone.vhd, sw/lib/include/neorv32.h
This is just another rtl clean-up PR (focusing mainly on cleaning up the assertions). The CPU assertions now also show the actual boot address:
```
neorv32_cpu.vhd:198:3:@0ms:(assertion note): NEORV32 CPU CONFIG NOTE: Boot from address 0x00000000.
```
=> [rtl] minor cleanups and typo fixes

CHANGELOG.md, rtl/core/neorv32_busswitch.vhd, rtl/core/neorv32_icache.vhd, rtl/core/neorv32_package.vhd, rtl/core/neorv32_top.vhd
This PR adds a minimal infrastructure to allow all internal devices to check if the current bus access is "cached". Right now, this feature is not used and does not impact area/critical path at all. I am planning to use this additional information to allow **burst accesses** for some peripherals:
* work-in-progress: XIP (reducing overhead - faster access)
* planned: Wishbone ("real" pipelined burst accesses)
=> [rtl] add "cached access" infrastructure

CHANGELOG.md, docs/datasheet/software.adoc, rtl/core/neorv32_package.vhd, sw/common/common.mk, sw/image_gen/image_gen.c
This PR adds/reworks two targets of the image generator / makefile for generating **raw executables**.
* `make hex` will generate a `neorv32_raw_exe.hex` file: ASCII hex char file; no header; can be used to initialize custom memories for _direct_ execution (for example custom VHDL memories)
* `make bin` will generate a `neorv32_raw_exe.bin` file: binary file; no header; can be used to initialize custom memories for _direct_ execution (for example to program flash for using XIP)
-> @betocool-prog :wink:
=> [image_generator, makefile] Update "raw" executable formats

CHANGELOG.md, docs/datasheet/soc_xip.adoc, rtl/core/neorv32_package.vhd, rtl/core/neorv32_xip.vhd, sw/example/demo_xip/main.c, sw/lib/include/neorv32.h, sw/lib/include/neorv32_xip.h, sw/lib/source/neorv32_xip.c, sw/svd/neorv32.svd
This PR adds an optional (experimental) **burst mode** for the XIP mode. The burst mode makes use of the flash's "incremental read" functionality to speed up sequential flash read accesses. XIP burst mode is enabled by setting bit 27 of the XIP's control register (calling new function `neorv32_xip_burst_mode_enable()`).
:bug: This PR also fixes the endiannes of the XIP mode. Now the XIP mode expects the data words to be stored in **little-endian** byte order to the flash. Thanks to @betocool-prog for finding this bug!
:warning: Programs stored to a flash for being used with the XIP module need to be updated due to the changed byte order.
=> 🧪 [XIP] add experimental burst mode; fix endianness

CHANGELOG.md, docs/datasheet/on_chip_debugger.adoc, rtl/core/neorv32_cfs.vhd, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_debug_dtm.vhd, rtl/core/neorv32_fifo.vhd, rtl/core/neorv32_package.vhd, rtl/core/neorv32_top.vhd, rtl/core/neorv32_wishbone.vhd, sim/neorv32_tb.vhd, sim/simple/neorv32_tb.simple.vhd, sw/example/processor_check/main.c
* :bug: fixes a bug that permanently stops `[m]cycle[h]` and `[m]instret[h]` counter if no HPM counters are implemented (_HPM_NUM_CNTS_ = 0)
* :bug: fix bug in WISHBONE.WE signal (when _ASYNC_TX_ mode enabled): signal was high for 1 cycle even if a read transfers (we = low) was triggered (@ #350)
* hardwired `dcsr.mprven` to 1: `mstatus.mprv` is also evaluated when in debug mode
* CFS can now check the current CPU privilege mode (to optionally constrain access/features to privileged software only)
* minor rtl clean-ups
=> 🐛 [rtl] cycle & instret bug fix, wishbone.we bug fix; minor rtl updates

CHANGELOG.md, rtl/core/neorv32_cpu_bus.vhd, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_package.vhd
This PR fixes a logic error when `PMP_NUM_REGIONS` = 0. The bug has been introduced with version `1.7.3.10` (#365).
=> :bug: [rtl] fix PMP config

CHANGELOG.md, rtl/core/neorv32_cpu_alu.vhd, rtl/core/neorv32_cpu_bus.vhd, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_cpu_cp_cfu.vhd, rtl/core/neorv32_package.vhd, rtl/core/neorv32_top.vhd, rtl/core/neorv32_xip.vhd, sw/example/demo_xip/main.c
This is just another rtl update PR.
* the **XIP module** will now raise a bus exception if the software tries to _write_ to the XIP memory-mapped flash (indicated as "device error" by the NEORV32 runtime environment)
* use a behavioral description of the ALU's adder/subtractor (seems to result in better logic; maybe because the synthesizer has more flexibility)
* minor code edits and cleanups
=> [rtl] minor edits and updates

CHANGELOG.md, docs/datasheet/software.adoc, docs/userguide/general_sw_framework_setup.adoc, rtl/core/neorv32_package.vhd, sw/common/neorv32.ld, sw/example/demo_newlib/main.c, sw/example/demo_newlib/makefile
This PR changes the default linker script in order to provide a more flexible memory/section/region configuration.
⚠️ The linker script (`sw/common/neorv32.ld`) now uses variables to define the section sizes and base addresses:
```
/* Default rom/ram (IMEM/DMEM) sizes */
__neorv32_rom_size = DEFINED(__neorv32_rom_size) ? __neorv32_rom_size : 2048M;
__neorv32_ram_size = DEFINED(__neorv32_ram_size) ? __neorv32_ram_size : 8K;
/* Default HEAP size (= 0; no heap at all) */
__neorv32_heap_size = DEFINED(__neorv32_heap_size) ? __neorv32_heap_size : 0;
/* Default section base addresses - do not change this unless the hardware-defined address space layout is changed! */
__neorv32_rom_base = DEFINED(__neorv32_rom_base) ? __neorv32_rom_base : 0x00000000; /* = VHDL package's "ispace_base_c" */ …
```
=> ⚠️ [linker script] simplify memory configuration

CHANGELOG.md, docs/datasheet/soc_slink.adoc, rtl/core/neorv32_package.vhd, rtl/core/neorv32_slink.vhd, sw/example/demo_slink/main.c, sw/example/processor_check/main.c, sw/lib/include/neorv32.h, sw/lib/include/neorv32_slink.h, sw/lib/source/neorv32_slink.c, sw/svd/neorv32.svd
This PR is another rework of the the processor's **Stream Link (SLINK)** module, triggered by  @betocool-prog (#376).
**⚠️ The module's register addresses and register contents are modified and are not backwards compatible!**
* add dedicated `RX_STATUS` and `TX_STATUS` registers that expose all FIFO's status signals (empty, at least half full, full) and "last element" signals
* add `IRQ` register to configure interrupt conditions per-link
* RX interrupt options:
* FIFO of link `i` _becomes_ empty
* FIFO of link `i` _becomes_ at least half full
* TX interrupt options:
* FIFO of link `i` _becomes_ empty
* FIFO of link `i` _becomes_ less than half full
=> :warning: [rtl] rework SLINK module

CHANGELOG.md, docs/datasheet/soc.adoc, docs/datasheet/soc_spi.adoc, rtl/core/neorv32_package.vhd, rtl/core/neorv32_spi.vhd, rtl/core/neorv32_top.vhd, rtl/system_integration/neorv32_ProcessorTop_stdlogic.vhd, rtl/system_integration/neorv32_SystemTop_AvalonMM.vhd, rtl/system_integration/neorv32_SystemTop_axi4lite.vhd, sim/neorv32_tb.vhd, sim/simple/neorv32_tb.simple.vhd, sw/bootloader/bootloader.c, sw/example/demo_spi/main.c, sw/example/demo_spi_irq/drv/neorv32_spi_irq.c, sw/example/demo_spi_irq/drv/neorv32_spi_irq.h, sw/example/demo_spi_irq/main.c, sw/example/processor_check/main.c, sw/lib/include/neorv32.h, sw/lib/include/neorv32_spi.h, sw/lib/source/neorv32_spi.c, sw/svd/neorv32.svd
This PR adds an optional data FIFO to the SPI module (idea by @akaeba from https://github.com/stnolting/neorv32/discussions/378). A new top generic is added to configure the SPI FIFO size: `IO_TRNG_FIFO`, default = 0; has to be zero or a power of two. Furthermore, all FIFO status signals are added to the SPI control register and a fine grained interrupt configuration is added:
* interrupt if SPI PHY completes the current transmission (default, behavior of pre-PR version)
* interrupt if SPI TX FIFO _becomes_ empty
* interrupt if SPI TX FIFO _becomes_ less than half full
✔️ The changes from this PR are fully backwards compatible.
=> ✨ [rtl] add optional SPI data FIFO

CHANGELOG.md, rtl/core/neorv32_package.vhd, rtl/core/neorv32_top.vhd, rtl/core/neorv32_twi.vhd
This PR relocates the TWI tri-state drivers from the TWI module to the NEORV32 top entity (one level to the top).
Maybe the tri-state drivers should be excluded from the processor so that they have to be implemented in the **design's** top entity... 🤔 Some synthesis tools seem to have problems if tri-state drivers are "buried" somewhere _inside_ the design (looking at you Vivado)...
=> [rtl] relocate TWI tri-state drivers

CHANGELOG.md, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_package.vhd, rtl/core/neorv32_top.vhd
This PR optimizes the CPU's front end (instruction fetch). The modified instruction fetch now uses **all** of the IPB FIFO (instruction prefetch buffer) instead of just 50%.
=> [rtl] optimize instruction fetch

CHANGELOG.md, docs/datasheet/soc_trng.adoc, rtl/core/neorv32_package.vhd, rtl/core/neorv32_trng.vhd, sw/lib/source/neorv32_trng.c
This PR adds a simple security feature to the TRNG: after reading a new random byte from the TRNG, the output is set to all-zero to ensure that a random data byte can only be read _once_ (regardless if the "valid" bit is checked by the software or not).
=> 🔒 [TRNG] add read data security feature

CHANGELOG.md, rtl/core/neorv32_package.vhd, sw/common/common.mk, sw/common/neorv32.ld, sw/example/demo_freeRTOS/makefile, sw/lib/source/syscalls.c, sw/ocd-firmware/debug_rom.ld, sw/ocd-firmware/makefile
Minor edits to adapt to the most recent toolchain from https://github.com/stnolting/riscv-gcc-prebuilt -> GCC 12.1.0 🚀
=> 🚀 [sw] Update software framework to GCC 12.1.0

README.md, docs/datasheet/overview.adoc, docs/userguide/content.adoc, docs/userguide/neorv32_in_verilog.adoc
[![neorv32-verilog](https://img.shields.io/github/workflow/status/stnolting/neorv32-verilog/Verification/main?longCache=true&style=flat&label=neorv32-verilog%20check&logo=Github%20Actions&logoColor=fff)](https://github.com/stnolting/neorv32-verilog/actions/workflows/main.yml)
This PR adds some documentation and links for the [neorv32-verilog](https://github.com/stnolting/neorv32-verilog) repository, which provides an automated GHDL-based flow to convert a custom NEORV32 configuration into an all-Verilog netlist module file (triggered by #266).
=> 🚀 [docs] add neorv32-verilog repository

CHANGELOG.md, docs/datasheet/cpu.adoc, docs/datasheet/cpu_csr.adoc, docs/datasheet/soc.adoc, docs/userguide/application_specific_configuration.adoc, rtl/core/neorv32_cpu.vhd, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_package.vhd, rtl/core/neorv32_top.vhd, rtl/processor_templates/neorv32_ProcessorTop_Minimal.vhd, rtl/processor_templates/neorv32_ProcessorTop_MinimalBoot.vhd, rtl/processor_templates/neorv32_ProcessorTop_UP5KDemo.vhd, rtl/system_integration/neorv32_ProcessorTop_stdlogic.vhd, rtl/system_integration/neorv32_SystemTop_AvalonMM.vhd, rtl/system_integration/neorv32_SystemTop_axi4lite.vhd, rtl/system_integration/neorv32_litex_core_complex.vhd, sim/neorv32_tb.vhd, sim/simple/neorv32_tb.simple.vhd, sw/lib/include/neorv32.h, sw/lib/include/neorv32_cpu.h, sw/lib/source/neorv32_cpu.c, sw/lib/source/neorv32_rte.c
This PR is another cleanup of the CPU's standard counters.
:warning: The `CPU_CNT_WIDTH` generic is removed. Hence, the width of the standard CPU counters (`[m]cycle` and `[m]instret`) is always 64-bit (low-word + high-word).
For area-constrained setups the standard CPU counters can be excluded from synthesis by disabling the `Zicntr` ISA extension (via the `CPU_EXTENSION_RISCV_Zicntr` generic).
=> ⚠️ [rtl] cleanup CPU standard counters, remove CPU_CNT_WIDTH generic

CHANGELOG.md, docs/datasheet/cpu.adoc, docs/datasheet/cpu_csr.adoc, docs/datasheet/software_rte.adoc, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_package.vhd, sw/example/processor_check/main.c, sw/lib/include/neorv32.h, sw/lib/source/neorv32_rte.c
This PR modifies the behavior of the `mtval` CSR (trap value register).
⚠️  In case of an illegal instruction exception `mtval` is **set to zero now**. Previously, it was written with the (de-compressed) 32-bit instruction word. However, the faulting instruction word can be retrieved by performing a load operation using the `mepc` CSR as address. Hence, this PR removes certain redundancies to reduce area requirements.
✔️ This simplification is explicitly allowed by the RISC-V priv. specs.
=> [rtl] set 'mtval' CSR to zero if illegal instruction exception

CHANGELOG.md, docs/datasheet/software.adoc, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_package.vhd, sw/common/crt0.S
Fixes a minor bug that did not clear pending FIRQs when clearing the according `mie` bits.
=> 🐛 [rtl] fix minor bug in mie CSR (FIRQs)

CHANGELOG.md, docs/datasheet/cpu.adoc, rtl/core/neorv32_cpu_cp_bitmanip.vhd, rtl/core/neorv32_package.vhd
This PR fixes a decoding collisions of the `B` enxtension's rotate instructions.
✨ With this PR the NEORV32 `B` ISA extension is fully operational - verified with [RISCOF](https://github.com/riscv-software-src/riscof).
=> :bug: [rtl] fix B ISA instruction decoding collisions

CHANGELOG.md, rtl/core/neorv32_busswitch.vhd, rtl/core/neorv32_cpu.vhd, rtl/core/neorv32_cpu_alu.vhd, rtl/core/neorv32_cpu_bus.vhd, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_cpu_cp_bitmanip.vhd, rtl/core/neorv32_cpu_cp_cfu.vhd, rtl/core/neorv32_cpu_cp_fpu.vhd, rtl/core/neorv32_cpu_cp_muldiv.vhd, rtl/core/neorv32_cpu_cp_shifter.vhd, rtl/core/neorv32_cpu_regfile.vhd, rtl/core/neorv32_icache.vhd, rtl/core/neorv32_package.vhd, rtl/core/neorv32_top.vhd, rtl/core/neorv32_uart.vhd
This PR removes the `data_width_c` package constant, which defines the "native data width" of the whole NEORV32 processor.
This is very a first step towards supporting the **RISC-V 64-bit ISA `rv64`**.
The SoC (so all memories and peripherals) will be 32-bit only. The CPU core itself will provide a new configuration generic `XLEN` that allows to specify the core's native data width (32-bit or 64-bit). This generic is not yet available!
This is still very early stuff and highly experimental! Full RV64 support will/might be added somewhere in the future.
=> [rtl] XLEN cleanup

.github/workflows/Processor.yml
This PR temporarily disables the Windows-based msys2 workflows.
The latest version of the MSYS2 [mingw-w64-riscv64-unknown-elf-gcc](https://packages.msys2.org/base/mingw-w64-riscv64-unknown-elf-gcc) package does not work with the current NEORV32 setup:
```
d:/a/_temp/msys64/mingw32/bin/../lib/gcc/riscv64-unknown-elf/12.2.0/../../../../riscv64-unknown-elf/bin/ld.exe: d:/a/_temp/msys64/mingw32/bin/../lib/gcc/riscv64-unknown-elf/12.2.0/../../../../riscv64-unknown-elf/lib\libc.a(lib_a-memcpy.o): ABI is incompatible with that of the selected emulation:
target emulation `elf64-littleriscv' does not match `elf32-littleriscv'
```
This package uses RISC-V GCC version 12.2. I am not sure if there is a problem with the compiler flags (`-misa-spec`?!) or with the package itself (compiled without rv32 …
=> 🐛 [.github] disable Windows/MSYS2 workflows for now

CHANGELOG.md, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_package.vhd
Avoids Critical Warning in Quartus Prime Version 20.1.0 Build 711 06/05/2020 Standard Edition
```bash
Critical Warning (18061): Ignored Power-Up Level option on the following registers
Critical Warning (18010): Register neorv32_top:neorv32_i|neorv32_cpu:neorv32_cpu_inst|neorv32_cpu_control:neorv32_cpu_control_inst|execute_engine.state[3] will power up to High
Critical Warning (18010): Register neorv32_top:neorv32_i|neorv32_cpu:neorv32_cpu_inst|neorv32_cpu_control:neorv32_cpu_control_inst|execute_engine.state[3] will power up to High
```
=> Fix Critical Warning in Quartus 20.1.0: avoid power up to high

rtl/system_integration/neorv32_litex_core_complex.vhd
The VHDL -> Verilog conversion flow can now configure the generics before the conversion. This avoid the workaround that was modifying the constants in litex_core_complex during the build.
Corresponding LiteX's PR: https://github.com/enjoy-digital/litex/pull/1460.
=> litex_core_complex: Expose configuration constants as generics.

CHANGELOG.md, docs/datasheet/cpu_csr.adoc, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_package.vhd, sw/common/crt0.S
This PR add a dedicated hardware reset to the CPU's `[m]cycle[h]`, `[m]instret[h]` and `[m]hpmcounter[h]` CSRs.
With this PR **all** CSRs now do provide a dedicated hardware reset.
=> Add HW reset to CPU counter CSRs

CHANGELOG.md, rtl/core/neorv32_package.vhd
The `is_power_of_two_f` function did not work at all and just checked the input value for being even...
=> :bug: [rtl] fix is_power_of_two VHDL function

CHANGELOG.md, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_package.vhd
Quartus 21.1 shows the following message:
> Warning (10631): VHDL Process Statement warning at neorv32_cpu_control.vhd(1635): inferring latch(es) for signal or variable "csr", which holds its previous value in one or more paths through the process
But there are no latches in the code! The CSR read and write processes are entirely synchronous. Furthermore, the synthesis report does not show any latches (Compilation Report -> Analysis & Synthesis -> Optimization Results -> Register Statistics).
This PR tries to fix this issue by reformatting certain parts of the VHDL code.
See discussion #421 for more information.
=> [rtl] Try to fix Quartus latch warnings

sw/example/demo_blink_led_asm/main.S, sw/example/demo_blink_led_asm/makefile
Add a new simple assembly-only demo program derived from `sw/example/demo_blink_led`.
Implements a simple counter that uses the lowest 8 bits of the GPIO's output port (increments every 0.25s). The CPU cycle counter is used as time base. Hence, this program requires the GPIO controller and the CPU Zicsr and Zicnt ISA extensions.
=> ✨ [sw] add assembly-only demo program

sw/example/bitmanip_test/README.md, sw/example/bitmanip_test/neorv32_b_extension_intrinsics.h, sw/example/floating_point_test/README.md, sw/example/floating_point_test/neorv32_zfinx_extension_intrinsics.h, sw/lib/include/neorv32_cpu_cfu.h, sw/lib/include/neorv32_intrinsics.h
This PR is a rework of the core's intrinsic / custom instruction library.
* fixed names of intrinsic prototypes: e.g. a "r3" type instruction consists of 3 registers (2 source registers, 1 destination register)
* `neorv32_cfu_r3_instr(funct7, funct3, rs1, rs2)`´is now the primitive for custom instructions (CFU); a compatibility layer is provided to further support the CFU's `neorv32_cfu_cmd0(funct7, rs1, rs2)` ... `neorv32_cfu_cmd7(funct7, rs1, rs2)` intrinsics
* the documentation will be updated/fixed in an upcoming PR
=> [sw] rework intrinsic libraries

CHANGELOG.md, docs/datasheet/cpu.adoc, docs/datasheet/cpu_cfu.adoc, docs/datasheet/cpu_csr.adoc, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_package.vhd, sw/example/processor_check/main.c, sw/lib/source/neorv32_cpu.c
* Fix a bug in the core's interrupt system: when in user-mode, interrupts are globally enabled even if `mstatus.mie` is cleared. Quote from the RISC-V privilege specification:
> When a hart is executing in privilege mode x, interrupts are globally enabled when xIE=1 and
globally disabled when xIE=0. Interrupts for lower-privilege modes, w<x, are always globally
disabled regardless of the setting of any global wIE bit for the lower-privilege mode. **Interrupts for
higher-privilege modes, y>x, are always globally enabled regardless of the setting of the global yIE
bit for the higher-privilege mode.** Higher-privilege-level code can use separate per-interrupt enable
bits to disable selected higher-privilege-mode interrupts before ceding control to a lower-privilege
mode.
* The illegal …
=> 🐛 [rtl] core trap fixes

CHANGELOG.md, docs/datasheet/cpu.adoc, docs/datasheet/on_chip_debugger.adoc, rtl/core/neorv32_cpu.vhd, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_debug_dm.vhd, rtl/core/neorv32_package.vhd, rtl/core/neorv32_top.vhd, sw/ocd-firmware/README.md, sw/ocd-firmware/debug_rom.ld, sw/ocd-firmware/park_loop.S
* optimize park loop code (slightly faster debugging response)
* add explicit debug-entry address generics to CPU (`CPU_DEBUG_PARK_ADDR`, `CPU_DEBUG_EXC_ADDR`)
=> 🧪 [OCD] optimize firmware (park-loop)

CHANGELOG.md, docs/datasheet/soc_icache.adoc, rtl/core/neorv32_icache.vhd, rtl/core/neorv32_package.vhd, sim/neorv32_tb.vhd, sim/simple/neorv32_tb.simple.vhd, sw/example/processor_check/main.c
Whenever the instruction cache detects a "miss" it fetches a complete block from main memory. If any address within that block does not assert a bus access ACKNOWLEDGE, or if any address within that block asserts a bus accesses ERROR, **the whole cache block** is invalidated and the CPU receives an ERROR - regardless of the actually accessed address.
Example:
* CPU jump to address `0x00001008`, which triggers an i-cache miss
* the i-cache fetches the according block from memory (starting with address `0x00001000`)
* address `0x00001000` asserts an ERROR while all other addresses inside the block assert an ACKNOWLEDGE
* the CPU receives an error because the whole block is treated as fault, even though only the (irrelevant) address `0x00001000` reported an ERROR
A more real-world example: …
=> 🐛 [rtl] fix iCache block error bug

CHANGELOG.md, docs/datasheet/cpu.adoc, docs/datasheet/software_rte.adoc, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_package.vhd, sw/example/processor_check/main.c, sw/lib/source/neorv32_rte.c
According to RISC-V priv. spec. the `xEPC` CSRs have to point to the address that caused an "instruction access fault" exception:
> 3.1.16 Machine Trap Value Register (mtval)
[...]
If mtval is written with a nonzero value when an instruction access-fault or page-fault exception occurs on a system with variable-length instructions, then mtval will contain the virtual address of the portion of the instruction that caused the fault, **while mepc will point to the beginning of the instruction**.
See https://github.com/riscv/riscv-isa-manual/issues/938
=> 🐛 [rtl] fix MEPC value for instruction access faults

CHANGELOG.md, docs/datasheet/cpu.adoc, docs/datasheet/cpu_csr.adoc, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_package.vhd, sw/lib/include/neorv32.h
`mtval` is no longer read-only and can now be written by machine-mode software.
=> [rtl] mtval CSR is now r/w

CHANGELOG.md, docs/datasheet/soc.adoc, rtl/core/neorv32_bus_keeper.vhd, rtl/core/neorv32_cfs.vhd, rtl/core/neorv32_gpio.vhd, rtl/core/neorv32_gptmr.vhd, rtl/core/neorv32_mtime.vhd, rtl/core/neorv32_neoled.vhd, rtl/core/neorv32_onewire.vhd, rtl/core/neorv32_package.vhd, rtl/core/neorv32_pwm.vhd, rtl/core/neorv32_slink.vhd, rtl/core/neorv32_spi.vhd, rtl/core/neorv32_top.vhd, rtl/core/neorv32_trng.vhd, rtl/core/neorv32_twi.vhd, rtl/core/neorv32_uart.vhd, rtl/core/neorv32_wishbone.vhd, rtl/core/neorv32_xip.vhd, rtl/core/neorv32_xirq.vhd
For each SoC module:
* split read/write access logic into two processes - one for write access logic, one for read access logic and bus handshake
* removed explicit reset to don't care (`'-'`)
=> [rt] SoC: rework r/w access logic and reset

CHANGELOG.md, docs/datasheet/cpu_csr.adoc, rtl/core/neorv32_cpu_alu.vhd, rtl/core/neorv32_cpu_bus.vhd, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_cpu_cp_bitmanip.vhd, rtl/core/neorv32_cpu_cp_cfu.vhd, rtl/core/neorv32_cpu_cp_fpu.vhd, rtl/core/neorv32_cpu_cp_muldiv.vhd, rtl/core/neorv32_package.vhd
* remove reset to don't care (`'-'`)
* connect FIFO reset
* optimization in branch detection logic (improved area and timing)
* optimization in CSR access check logic (improved area and timing)
* minor code edits and cleanups
* closed further illegal instruction encoding hole (CSR access instruction with `funct3 = 100`)
=> [rtl] CPU: optimizations and cleanup

CHANGELOG.md, docs/datasheet/soc.adoc, rtl/core/neorv32_package.vhd, rtl/core/neorv32_top.vhd
Initialization of registers via bitstream isn't compatible with at least two FPGA architectures:
- Gatemate FPGA -> leads to an error during systhesis with Yosys
- Microchip SmartFusion & Polarfire FPGAs / SoCs -> init value ignored during synthesis
Both aren't nice, the 2nd one can lead to nasty misbehavior if you rely on the initialization value.
There are two signals with init values in the neorv32 design:
```vhdl
neorv32_top.vhd:  signal rstn_ext_sreg : std_ulogic_vector(3 downto 0) := (others => '0'); -- initialize (reset) via bitstream
neorv32_top.vhd:  signal rstn_int_sreg : std_ulogic_vector(3 downto 0)  := (others => '0'); -- initialize (reset) via bitstream
```
I propose to remove the initialization resulting in this:
```vhdl
neorv32_top.vhd:  signal rstn_ext_sreg : …
```
=> Remove signal initalizations

CHANGELOG.md, README.md, docs/datasheet/cpu.adoc, docs/datasheet/cpu_csr.adoc, docs/datasheet/on_chip_debugger.adoc, docs/datasheet/soc.adoc, rtl/core/neorv32_cpu.vhd, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_debug_dm.vhd, rtl/core/neorv32_package.vhd, rtl/core/neorv32_top.vhd, sw/example/demo_trigger_module/main.c, sw/example/demo_trigger_module/makefile, sw/lib/include/neorv32.h, sw/lib/source/neorv32_rte.c
⚠️ This PR removes the CPU's `CPU_EXTENSION_RISCV_DEBUG` generic, which is replaced by two new generics to allow a finer configuration of the available debug spec. ISA extensions:
* `CPU_EXTENSION_RISCV_Sdext`: set _true_ to enable the RISC-V `Sdext` ISA extension (external debug support, required for the on-chip debugger)
* `CPU_EXTENSION_RISCV_Sdtrig`: set _true_ to enable the RISC-V `Sdtrig` ISA extension (trigger module)
✨ This PR also enhances the capabilities of the **RISC-V trigger module** (`Sdtrig` ISA extension), which can now also be used _independently_ of the on-chip debugger. The trigger module can raise a machine-mode breakpoint exception when execution reaches a programmable address. A simple example program will be added to `sw/example/demo_trigger_module`.
=> ⚠️ rework CPU debug spec ISA configuration; ✨ enhance trigger module

CHANGELOG.md, docs/datasheet/on_chip_debugger.adoc, rtl/core/neorv32_debug_dm.vhd, rtl/core/neorv32_debug_dtm.vhd, rtl/core/neorv32_package.vhd, rtl/core/neorv32_top.vhd
- remove DM's `haltsum0` register (🧪 experimental; allowed by RISC-V debug spec. v1.0)
- the DTM's DMI register now uses one bit less for addressing the DM registers
- use RISC-V-compatible DMI signals (as shown in Appendix 3 of the RISC-V debug spec.)
- fix DTM error flag logic
- fix DM reset logic
- minor edits and updates
=> [rtl] OCD: update DTM and DM

sw/lib/include/neorv32.h
It seems that there was a copy/past error when onewire unit was added to the NEORV32_SYSINFO_SOC_enum:
```c
enum NEORV32_SYSINFO_SOC_enum {
...
SYSINFO_SOC_IO_XIP         = 30, /**< SYSINFO_FEATURES (30) (r/-): Execute in place module implemented when 1 (via IO_XIP_EN generic) */
SYSINFO_SOC_IO_ONEWIRE     = 30  /**< SYSINFO_FEATURES (31) (r/-): 1-wire interface controller implemented when 1 (via IO_ONEWIRE_EN generic) */
};
```
This PR corrects the value of `SYSINFO_SOC_IO_ONEWIRE` to 31.
Please close this PR if this is by intention.
=> Fix value of SYSINFO_SOC_IO_ONEWIRE in NEORV32_SYSINFO_SOC_enum

CHANGELOG.md, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_package.vhd
fix minor bug in trigger module handling: trigger match may enter debug mode only if `tdata1.dmode` is set
=> [rtl] CPU: logic optimization

docs/userguide/general_hw_setup.adoc, rtl/test_setups/README.md, rtl/test_setups/neorv32_test_setup_approm.vhd, rtl/test_setups/neorv32_test_setup_bootloader.vhd, rtl/test_setups/neorv32_test_setup_on_chip_debugger.vhd
This PR adds a new test setup that also includes the RISC-V-compatible on-chip debugger (OCD).
=> [rtl/test_setups] add on-chip debugger test setup

CHANGELOG.md, docs/datasheet/soc_wdt.adoc, rtl/core/neorv32_package.vhd, rtl/core/neorv32_wdt.vhd, sw/example/demo_wdt/main.c, sw/example/processor_check/main.c, sw/lib/include/neorv32.h, sw/lib/include/neorv32_wdt.h, sw/lib/source/neorv32_wdt.c
This PR is complete rework of the NEORV32 Watchdog Timer (WDT).
* remove access password and bus exception trigger
* remove clock prescaler select
* add programmable 24-bit timeout value; internal counter increments at f_main/4096
* now using "bite and bark" concept
* when reaching "timeout/2" an optional CPU interrupt is triggered
* when reaching "timeout" a system-wide hardware reset is triggered
* change control register layout
* update HAL (SW drivers), example program and documentation
=> :warning: rework watchdog timer (WDT)

CHANGELOG.md, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_cpu_cp_bitmanip.vhd, rtl/core/neorv32_fifo.vhd, rtl/core/neorv32_mtime.vhd, rtl/core/neorv32_package.vhd, rtl/core/neorv32_top.vhd
- rework VHDL coding style to prevent some of Quartus' and Vivado's Warning messages
- rework PMP CSR read access logic
- fix minor bug in instruction fetch unit
=> [rtl] VHDL cleanups

CHANGELOG.md, docs/datasheet/cpu.adoc, docs/datasheet/cpu_csr.adoc, docs/datasheet/overview.adoc, docs/datasheet/soc.adoc, docs/datasheet/soc_mtime.adoc, rtl/core/neorv32_cpu.vhd, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_fifo.vhd, rtl/core/neorv32_mtime.vhd, rtl/core/neorv32_package.vhd, rtl/core/neorv32_top.vhd, rtl/processor_templates/neorv32_ProcessorTop_Minimal.vhd, rtl/processor_templates/neorv32_ProcessorTop_MinimalBoot.vhd, rtl/processor_templates/neorv32_ProcessorTop_UP5KDemo.vhd, rtl/system_integration/neorv32_ProcessorTop_stdlogic.vhd, rtl/system_integration/neorv32_SystemTop_AvalonMM.vhd, rtl/system_integration/neorv32_SystemTop_axi4lite.vhd, sim/neorv32_tb.vhd, sim/simple/neorv32_tb.simple.vhd, sw/example/processor_check/main.c, sw/lib/include/legacy.h, sw/lib/include/neorv32.h, sw/lib/include/neorv32_cpu.h, sw/lib/source/neorv32_cpu.c
* ⚠️ remove `mtime_i` and `mtime_o` top entity ports
* ⚠️ remove `time` and `timeh` CSRs
* ⚠️ hardwire `mcounteren` CSR to all-one - user-level software is always allowed to access the user-level counter CSRs
* add user-level HPM counters `hpmcounter3[h]` to `hpmcounter31[h]`
* simplify CSR access check logic
* ⚠️ clearing `mie` CSR (enabled interrupts) will not clear `mip` CSR (pending interrupts)
=> :warning: Rework CPU counters

CHANGELOG.md, docs/datasheet/cpu.adoc, docs/datasheet/cpu_csr.adoc, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_package.vhd
This PR also fixes a race condition: when a FIRQ is triggered in the same moment as the according FIRQ channel is cleared/acknowledged using the `mip` CSR the actual interrupt request got lost.
=> [rtl] Cleanup CPU interrupt controller

CHANGELOG.md, docs/datasheet/cpu.adoc, docs/datasheet/cpu_csr.adoc, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_package.vhd, sw/example/processor_check/main.c
* cleanup CPU's trap controller VHDL code
* fix `mip` CSR: bits in this register can now become set when the according interrupt source fire without the according `mie` CSR bit being set (RISC-V compatibility)
=> [rtl] rework mip csr

CHANGELOG.md, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_package.vhd
* faster exception/interrupt response (one cycle faster)
* less hardware requirements; ~10% smaller size
* VHDL code cleanup
* fixed warning "undriven signal" (`csr` record)
=> [rtl] CPU control optimization

CHANGELOG.md, rtl/core/neorv32_cpu.vhd, rtl/core/neorv32_cpu_alu.vhd, rtl/core/neorv32_cpu_bus.vhd, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_cpu_cp_bitmanip.vhd, rtl/core/neorv32_cpu_cp_cfu.vhd, rtl/core/neorv32_cpu_cp_fpu.vhd, rtl/core/neorv32_cpu_cp_muldiv.vhd, rtl/core/neorv32_cpu_cp_shifter.vhd, rtl/core/neorv32_cpu_decompressor.vhd, rtl/core/neorv32_cpu_regfile.vhd, rtl/core/neorv32_package.vhd
* control bus now using `record` type: cleaner code and easier to analyze in logic waveform
* minor instruction decoding optimization (`M` ISA extension)
* add 6th CPU co-processor slot (yet unused)
=> [rtl] CPU: use record as main control bus type

CHANGELOG.md, docs/datasheet/cpu.adoc, docs/datasheet/cpu_cfu.adoc, rtl/core/neorv32_cpu_alu.vhd, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_package.vhd
If a CPU co-processor operation (e.g. FPU or CFU) takes too long (default: max 128 clock cycles) the operation is automatically terminated by the hardware an an illegal instruction exception is raised.
=> [rtl] add co-processor timing monitor

sw/lib/include/neorv32.h
As discussed in #492 is for UART0 and UART1 the same register layout definition used.
=> [sw/lib/include/neorv32.h]: remove redundant uart typedef

CHANGELOG.md, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_cpu_cp_cfu.vhd, rtl/core/neorv32_package.vhd, rtl/core/neorv32_sysinfo.vhd, sw/example/demo_cfu/main.c
* fix minor bug in co-processor monitor (timeout exception was never triggered)
* VHDL code clean-up in SYSINFO module
* add CFU illegal instruction exception example
=> 🐛 [rtl] fix bug in co-processor monitor

CHANGELOG.md, docs/datasheet/soc_cfs.adoc, rtl/core/neorv32_cfs.vhd, rtl/core/neorv32_package.vhd, sw/example/demo_cfs/main.c, sw/lib/include/neorv32.h
The _custom functions subsystem_ (CFS) now provides up to 64 memory-mapped 32-bit registers for custom use.
=> [CFS] add another 64 interface registers

sw/svd/neorv32.svd
This also crashes SEGGER Embedded Studio for RISC-V.
=> Corrected the PWM address which was a typo.

sw/lib/include/neorv32.h, sw/lib/source/neorv32_gptmr.c
Change definition of NEORV32_GPTMR and replace all "NEORV32_GPTMR." by "NEORV32_GPTMR->".
Even make the GPTMR structure volatile.
=> GPTMR: Change "variable style" by "pointer style"

sw/bootloader/bootloader.c, sw/lib/include/neorv32.h, sw/lib/source/neorv32_mtime.c
Change definition of NEORV32_MTIME and replace all "NEORV32_MTIME." by "NEORV32_MTIME->".
Even make the MTIME structure volatile.
=> MTIME: Change "variable style" by "pointer style"

sw/lib/include/neorv32.h, sw/lib/source/neorv32_gpio.c
Change definition of NEORV32_GPIO and replace all "NEORV32_GPIO." by "NEORV32_GPIO->".
Even make the GPIO structure volatile.
=> GPIO: Change "variable style" by "pointer style"

sw/lib/include/neorv32.h, sw/lib/source/neorv32_onewire.c
Change definition of NEORV32_ONEWIRE and replace all "NEORV32_ONEWIRE." by "NEORV32_ONEWIRE->".
Even make the ONEWIRE structure volatile.
=> ONEWIRE: Change "variable style" by "pointer style"

sw/lib/include/neorv32.h, sw/lib/source/neorv32_pwm.c
Change definition of NEORV32_PWM and replace all "NEORV32_PWM." by "NEORV32_PWM->".
Even make the PWM structure volatile.
=> PWM: Change "variable style" by "pointer style"

sw/lib/include/neorv32.h, sw/lib/source/neorv32_trng.c
Change definition of NEORV32_TRNG and replace all "NEORV32_TRNG." by "NEORV32_TRNG->".
Even make the TRNG structure volatile.
=> TRNG: Change "variable style" by "pointer style"

sw/example/demo_twi/main.c, sw/lib/include/neorv32.h, sw/lib/source/neorv32_twi.c
Change definition of NEORV32_TWI and replace all "NEORV32_TWI." by "NEORV32_TWI->".
Even make the TWI structure volatile.
=> TWI: Change "variable style" by "pointer style"

sw/lib/include/neorv32.h, sw/lib/source/neorv32_xip.c
Change definition of NEORV32_XIP and replace all "NEORV32_XIP." by "NEORV32_XIP->".
Even make the XIP structure volatile.
=> XIP: Change "variable style" by "pointer style"

sw/bootloader/bootloader.c, sw/example/coremark/core_portme.c, sw/example/demo_freeRTOS/main.c, sw/example/demo_gptmr/main.c, sw/example/demo_mtime/main.c, sw/example/demo_newlib/main.c, sw/example/demo_spi/main.c, sw/example/demo_twi/main.c, sw/example/demo_wdt/main.c, sw/example/demo_xip/main.c, sw/example/dhrystone/dhry_1.c, sw/example/processor_check/main.c, sw/lib/include/neorv32.h, sw/lib/source/neorv32_cfs.c, sw/lib/source/neorv32_cpu.c, sw/lib/source/neorv32_gpio.c, sw/lib/source/neorv32_gptmr.c, sw/lib/source/neorv32_mtime.c, sw/lib/source/neorv32_neoled.c, sw/lib/source/neorv32_onewire.c, sw/lib/source/neorv32_pwm.c, sw/lib/source/neorv32_rte.c, sw/lib/source/neorv32_sdi.c, sw/lib/source/neorv32_spi.c, sw/lib/source/neorv32_trng.c, sw/lib/source/neorv32_twi.c, sw/lib/source/neorv32_uart.c, sw/lib/source/neorv32_wdt.c, sw/lib/source/neorv32_xip.c, sw/lib/source/neorv32_xirq.c
Change definition of NEORV32_SYSINFO and replace all "NEORV32_SYSINFO." by "NEORV32_SYSINFO->".
Even make the SYSINFO structure volatile.
=> SYSINFO: Change "variable style" by "pointer style"

CHANGELOG.md, docs/datasheet/soc_gptmr.adoc, rtl/core/neorv32_gptmr.vhd, rtl/core/neorv32_package.vhd, sw/example/demo_gptmr/main.c
Minor VHDL code reworks.
:warning: If the GPTMR operates in one-shot mode the according fast interrupt will remain pending until the timer is disabled / reconfigured.
=> [rtl] minor GPTMR code reworks

sw/lib/source/neorv32_uart.c
Hi there!
The current `printf` implementation did not allow me to print a single `%` by escaping it with an additional percent sign in front `%%`. This is [supported](https://cplusplus.com/reference/cstdio/printf/#:~:text=A%20%25%20followed%20by%20another%20%25%20character%20will%20write%20a%20single%20%25%20to%20the%20stream.) in the standard implementation.
If I put two, it printed out two. If I put only one, it printed `%<break>` with _cutecom_ (Maybe misconfiguration on my end? PuTTY correctly showed only `%`.)
Anyway this small pr adds support for it.
I assume that the custom implementation of `printf` is deliberately kept small and need not be compliant with all the quirks of the official rules (for example floats are left out). So feel free to decline this pr if it would add to …
=> [sw/uart] allow for escaped percent sign

sw/svd/neorv32.svd
Corrected typo at the CFS section.
Here the ">" was missing at the end.
=> SVD: Corrected typo

CHANGELOG.md, docs/datasheet/soc.adoc, docs/datasheet/soc_onewire.adoc, docs/datasheet/soc_twi.adoc, docs/userguide/packaging_vivado.adoc, rtl/core/neorv32_onewire.vhd, rtl/core/neorv32_package.vhd, rtl/core/neorv32_top.vhd, rtl/core/neorv32_twi.vhd, rtl/processor_templates/neorv32_ProcessorTop_UP5KDemo.vhd, rtl/system_integration/neorv32_SystemTop_AvalonMM.vhd, rtl/system_integration/neorv32_SystemTop_axi4lite.vhd, sim/neorv32_tb.vhd, sim/simple/neorv32_tb.simple.vhd
This PR removes the processor-internal tri-state drivers used by the OENWIRE and TWI modules as discussed in #538.
=> [rtl] move ONEWIRE and TWI tri-state drivers out of core

docs/datasheet/soc_bootrom.adoc, docs/datasheet/software.adoc, sw/lib/include/neorv32.h, sw/lib/include/neorv32_cpu_csr.h
-> `sw/lib/include/neorv32_cpu_csr.h`
=> [sw/lib] move CSR definitions to separate file

CHANGELOG.md, docs/datasheet/cpu.adoc, docs/datasheet/cpu_csr.adoc, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_package.vhd, sim/neorv32_tb.vhd, sw/example/processor_check/main.c, sw/lib/include/neorv32_cpu_csr.h
This PR adds the user-level `time` and `timeh` counter CSRs.
ℹ️ The `time[h]` CSRs are just another shadow copy of the machine-mode cycle counters (`mcycle[h]`).
> On some simple platforms, cycle count might represent a valid implementation of RDTIME, in which case RDTIME and RDCYCLE may return the same result. - RISC-V ISA spec.
=> ✨ add time[h] CSRs

CHANGELOG.md, docs/datasheet/cpu_csr.adoc, docs/datasheet/on_chip_debugger.adoc, docs/datasheet/soc.adoc, docs/userguide/debugging_with_ocd.adoc, rtl/core/neorv32_cfs.vhd, rtl/core/neorv32_cpu.vhd, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_package.vhd, rtl/core/neorv32_top.vhd, rtl/processor_templates/neorv32_ProcessorTop_Minimal.vhd, rtl/processor_templates/neorv32_ProcessorTop_MinimalBoot.vhd, rtl/processor_templates/neorv32_ProcessorTop_UP5KDemo.vhd, rtl/system_integration/neorv32_SystemTop_AvalonMM.vhd, rtl/system_integration/neorv32_SystemTop_axi4lite.vhd, rtl/system_integration/neorv32_litex_core_complex.vhd, sim/neorv32_tb.vhd, sim/simple/neorv32_tb.simple.vhd, sw/openocd/openocd_neorv32.cfg
* rename `HW_THREAD_ID` to `HART_ID` and change from `natural` to `std_ulogic_vector(31 downto 0)`
* add `VENDOR_ID` generic, type `std_ulogic_vector(31 downto 0)`, used to set content of `mvendorid` CSR (vendor's JEDEC manufacturer ID)
* hardwire JTAG tap's IDCODE identifier to all-zero
=> [rtl] cleanup top's generics

CHANGELOG.md, docs/datasheet/cpu.adoc, docs/datasheet/soc.adoc, rtl/core/neorv32_busswitch.vhd, rtl/core/neorv32_cpu.vhd, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_dcache.vhd, rtl/core/neorv32_icache.vhd, rtl/core/neorv32_package.vhd, rtl/core/neorv32_top.vhd, rtl/processor_templates/neorv32_ProcessorTop_Minimal.vhd, rtl/processor_templates/neorv32_ProcessorTop_MinimalBoot.vhd, rtl/processor_templates/neorv32_ProcessorTop_UP5KDemo.vhd, rtl/system_integration/neorv32_SystemTop_AvalonMM.vhd, rtl/system_integration/neorv32_SystemTop_axi4lite.vhd, rtl/system_integration/neorv32_litex_core_complex.vhd, rtl/test_setups/neorv32_test_setup_approm.vhd, rtl/test_setups/neorv32_test_setup_bootloader.vhd, rtl/test_setups/neorv32_test_setup_on_chip_debugger.vhd, sim/neorv32_tb.vhd, sim/simple/neorv32_tb.simple.vhd
* ⚠️ remove `CPU_EXTENSION_RISCV_Zicsr` generic; `Zicsr` ISA extension is always enabled
* optimize bus switch - less bus congestion, less wait cycles
* VHDL code cleanups
=> ⚠️ [rtl] remove Zicsr generic, cleanups and optimizations

docs/datasheet/soc_dcache.adoc, docs/userguide/customizing_the_bootloader.adoc, sw/bootloader/bootloader.c
Added a new bootloader config parameter (`UART_HW_HANDSHAKE_EN`) to `bootloader.c`. And, updated the docs to describe `UART_HW_HANDSHAKE_EN`.  (`UART_HW_HANDSHAKE_EN` defaults to disabled.)
Also, fix two typos in the d-cache docs.
=> Bootloader Config Parameter to Enable UART0 HW Handshaking.

CHANGELOG.md, docs/datasheet/cpu.adoc, docs/datasheet/cpu_csr.adoc, rtl/core/neorv32_cpu_bus.vhd, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_package.vhd, sim/neorv32_tb.vhd, sw/example/processor_check/main.c, sw/lib/include/neorv32_cpu.h, sw/lib/source/neorv32_cpu.c, sw/lib/source/neorv32_rte.c
* :sparkles: add support for `NA4` (naturally aligned power-of-two region, 4 byte wide) and `NAPOT` (naturally aligned power-of-two region, larger than 4 bytes) to the processor's physical memory protection system - PMP is now full spec-compliant
* :warning: change behavior of `neorv32_cpu_pmp_configure_region()` function
=> [PMP] add support for NA4 and NAPOT modes

CHANGELOG.md, docs/datasheet/cpu.adoc, docs/datasheet/cpu_csr.adoc, rtl/core/neorv32_cpu.vhd, rtl/core/neorv32_cpu_alu.vhd, rtl/core/neorv32_cpu_bus.vhd, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_cpu_cp_bitmanip.vhd, rtl/core/neorv32_cpu_cp_cfu.vhd, rtl/core/neorv32_cpu_cp_cond.vhd, rtl/core/neorv32_cpu_cp_fpu.vhd, rtl/core/neorv32_cpu_cp_muldiv.vhd, rtl/core/neorv32_cpu_cp_shifter.vhd, rtl/core/neorv32_cpu_decompressor.vhd, rtl/core/neorv32_cpu_regfile.vhd, rtl/core/neorv32_package.vhd, rtl/core/neorv32_top.vhd, sim/neorv32_tb.vhd, sw/example/processor_check/main.c, sw/lib/include/neorv32_cpu_csr.h, sw/lib/source/neorv32_rte.c
* "The NEORV32 does not implement the user-mode `time[h]` registers. Any access to these registers will trap. It is recommended that the trap handler software provides a means of accessing the platform-defined MTIME machine timer." - same concept is used in Ibex/openTitan :wink:
* VHDL code cleanups
* minor logic optimizations
* fix minor bug in NEORV32 runtime environment: do not try to load the trap-causing instruction word when a _instruction access fault exception_ has been raised
=> [rtl] cleanups and optimizations

CHANGELOG.md, docs/datasheet/soc_xirq.adoc, rtl/core/neorv32_package.vhd, rtl/core/neorv32_xirq.vhd, sw/example/demo_xirq/main.c, sw/example/processor_check/main.c, sw/lib/include/neorv32_xirq.h, sw/lib/source/neorv32_xirq.c
* rename XIRW registers (-> `EIE`, `EIP`, `ESC`)
* use same behavior as `mie`, `mip` and `mcause` CSRs
* interrupt can become/remain pending even if the according channel is not enabled but will only trigger a CPU interrupt when actually enabled
* fixing some documentation flaws
=> update XIRQ controller

sw/example/demo_freeRTOS/makefile
I know that perhaps a lot of additional work is needed to get networking working on this processor, so this prehaps isn't the most useful fix. 
Nevertheless, FreeRTOS have put all the source files (for only the TCP stuff) under `$(FREERTOS_HOME)/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/source/` and not `$(FREERTOS_HOME)/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/` as it currently is in the makefile in the FreeRTOS example. 
This PR just updates those routes. 
Users would also need to include a `FreeRTOSIPConfig.h` file as well. I have left that out for now, but I can add a note about that in the readme for the example. I can also provide a default one too - just wanted to see everyone's thoughts first.
=> Updated path for FreeRTOS example - FreeRTOS-Plus-TCP

CHANGELOG.md, docs/datasheet/soc_uart.adoc, rtl/core/neorv32_package.vhd, rtl/core/neorv32_uart.vhd, sw/lib/include/legacy.h, sw/lib/include/neorv32_uart.h, sw/lib/source/neorv32_uart.c
Software can now retrieve the UART FIFO configuration via new bits in the module's `DATA` register.
Suggested by @akaeba in #575.
=> [UART] add FIFO configuration to DATA register

CHANGELOG.md, rtl/core/neorv32_dma.vhd, rtl/core/neorv32_package.vhd, sim/neorv32_tb.vhd
Write data gets corrupted if there are DMA wait states (e.g. if no caches are implemented).
Disabled caches in VUnit testbench to have a test case for this.
(thx @biosbob for finding this bug!)
=> 🐛 [rtl] fix bug in DMA

CHANGELOG.md, rtl/core/neorv32_cpu.vhd, rtl/core/neorv32_cpu_bus.vhd, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_dcache.vhd, rtl/core/neorv32_package.vhd, rtl/core/neorv32_top.vhd, sim/run.py
* minor edits of CPU bus unit
* reduced switching activity of CPU's memory data input logic (less dyn. power consumption)
* small adjustments (for the perhaps upcoming `A`-extension)
* 💡 update Vunit simulation script (for using VUnit v5)
=> [rtl] minor edits; update to VUnit v5

CHANGELOG.md, rtl/core/mem/neorv32_dmem.default.vhd, rtl/core/mem/neorv32_dmem.legacy.vhd, rtl/core/mem/neorv32_imem.default.vhd, rtl/core/mem/neorv32_imem.legacy.vhd, rtl/core/neorv32_package.vhd, rtl/core/neorv32_sdi.vhd, rtl/test_setups/neorv32_test_setup_approm.vhd, rtl/test_setups/neorv32_test_setup_bootloader.vhd, rtl/test_setups/neorv32_test_setup_on_chip_debugger.vhd
* update test setup wrappers (add explicit instruction prefetch buffer configuration)
* optimize default IMEM and DMEM modules (synthesis tools like Quartus will no longer issue a warning about adding "bypass logic" -> less hardware requirements)
* make **SDI** FIFO access _synchronous_ to improve BRAM mapping
=> [rtl] minor rtl updates

CHANGELOG.md, docs/datasheet/cpu.adoc, docs/datasheet/cpu_csr.adoc, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_package.vhd
According to the RISC-V spec this is optional. However, it is required to pass the current version of the RISC-V ISA tests (SAIL reference model does not support `mtval`=0 on `ebreak` yet).
=> [CPU] move instruction address to mtval on ebreak exception

CHANGELOG.md, docs/datasheet/soc_trng.adoc, rtl/core/neorv32_package.vhd, rtl/core/neorv32_trng.vhd, sw/example/demo_trng/main.c, sw/lib/include/neorv32_trng.h, sw/lib/source/neorv32_trng.c, sw/svd/neorv32.svd
Add four new (read-only) bits to the TRNG control register so software can check the configured FIFO size.
=> [TRNG] software can now retrieve FIFO size

docs/datasheet/software.adoc, docs/userguide/debugging_with_ocd.adoc, sw/common/common.mk
The makefile's `gdb` target will now automatically start a pre-defined debugging session (requires openOCD to be already running & connected).
The default configuration used `main.elf` as executable and uses `target extended-remote localhost:3333` to connect to the core (defined in makefile's `GDB_ARGS` variable).
=> [makefile] extend GDB target

CHANGELOG.md, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_package.vhd
* code clean-up and optimization - slightly less hardware requirements
* optimize branch "prediction" - branches are processed more efficiently (faster)
* closed further illegal instruction word detection holes (invalid `funct3` for branches)
=> optimize CPU's control logic

CHANGELOG.md, rtl/core/neorv32_cpu.vhd, rtl/core/neorv32_cpu_alu.vhd, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_neoled.vhd, rtl/core/neorv32_package.vhd, rtl/core/neorv32_sdi.vhd, rtl/core/neorv32_slink.vhd, rtl/core/neorv32_spi.vhd, rtl/core/neorv32_top.vhd, rtl/core/neorv32_trng.vhd, rtl/core/neorv32_uart.vhd
VHDL code: use **entity instantiation** instead of component instantiation as suggested by @biosbob in https://github.com/stnolting/neorv32/discussions/613 [_EXPERIMENTAL!_].
Component instantiation is further used for components that are placed in the same file.
=> 🧪 VHDL - use entity instantiation

CHANGELOG.md, docs/datasheet/soc_uart.adoc, docs/userguide/simulating_the_processor.adoc, rtl/core/neorv32_package.vhd, rtl/core/neorv32_top.vhd, rtl/core/neorv32_uart.vhd, sim/simple/ghdl.run.sh
This PR removes the 32-bit data dump mode from the UART's sim mode. The UART is a **byte**-based IO device and should not be used to dump 32-bit data.
A simple way to dump 32-bit data to a file can be found in the neorv32-riscof repository:
https://github.com/stnolting/neorv32-riscof/blob/de8b6d145cbcb1f938418d9983a0cf2a2b3064ad/sim/neorv32_riscof_tb.vhd#L272-L286
=> ⚠️ Remove UART sim-mode's 32-bit dump

CHANGELOG.md, docs/datasheet/cpu.adoc, docs/datasheet/soc.adoc, rtl/core/neorv32_intercon.vhd, rtl/core/neorv32_package.vhd, sw/example/processor_check/main.c, sw/lib/include/neorv32_cpu.h
* SC instructions did not check if the access actually matches the reservation's address (region)
* if a LR instruction is followed by another LR instruction the latter ones overrides the reservation set of the former one
=> :bug: fixing some LR/SC design flaws

CHANGELOG.md, docs/datasheet/soc.adoc, docs/datasheet/soc_dmem.adoc, docs/datasheet/soc_imem.adoc, rtl/core/mem/neorv32_dmem.default.vhd, rtl/core/mem/neorv32_dmem.legacy.vhd, rtl/core/mem/neorv32_imem.default.vhd, rtl/core/mem/neorv32_imem.legacy.vhd, rtl/core/neorv32_dmem.entity.vhd, rtl/core/neorv32_imem.entity.vhd, rtl/core/neorv32_package.vhd, rtl/core/neorv32_top.vhd
The address logic of the internal memories as well as the central address decoding of the bus system cannot cope with address space sizes, which are not a power of two. This is especially true for the internal IMEM and DMEM memories. This PR fixes this problem by ensuring that the configured memory sizes are always a power of two:
> If the configured memory size (via the `MEM_INT_IMEM_SIZE` / `MEM_INT_DMEM_SIZE` generic) is **not** a power of two the actual memory size will be auto-adjusted to the next power of two (e.g. configuring a memory size of 60kB will result in a physical memory size of 64kB).
:+1: Identified by GitHub user @cmenendezzz in https://github.com/stnolting/neorv32/discussions/642.
:bug: This is not a real bug, but something that can cause problems.
=> 🐛 Make sure IMEM/DMEM sizes are a power of two

CHANGELOG.md, docs/datasheet/cpu.adoc, docs/datasheet/cpu_csr.adoc, docs/datasheet/overview.adoc, docs/datasheet/soc.adoc, rtl/core/neorv32_cpu.vhd, rtl/core/neorv32_cpu_alu.vhd, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_cpu_cp_bitmanip.vhd, rtl/core/neorv32_cpu_cp_cfu.vhd, rtl/core/neorv32_cpu_cp_cond.vhd, rtl/core/neorv32_cpu_cp_fpu.vhd, rtl/core/neorv32_cpu_cp_muldiv.vhd, rtl/core/neorv32_cpu_cp_shifter.vhd, rtl/core/neorv32_cpu_decompressor.vhd, rtl/core/neorv32_cpu_lsu.vhd, rtl/core/neorv32_cpu_pmp.vhd, rtl/core/neorv32_cpu_regfile.vhd, rtl/core/neorv32_intercon.vhd, rtl/core/neorv32_package.vhd, rtl/core/neorv32_top.vhd, sw/example/floating_point_test/main.c, sw/lib/include/neorv32_cpu_csr.h, sw/lib/source/neorv32_cpu.c, sw/lib/source/neorv32_cpu_amo.c, sw/lib/source/neorv32_rte.c
* remove co-processor timeout logic from ALU (use the watchdog timer to ensure the CPU does not get stuck instead)
* rename CPU data bus unit: `neorv32_cpu_bus.vhd -> neorv32_cpu_lsu.vhd` ("load/store unit")
* move entire PMP logic (including CSRs) into a new design file `neorv32_cpu_pmp.vhd`
* move FPU CSRs from central control unit to FPU module
* constrain maximum number of HPMs to 13 (`[m]hpmcounter3[h]` to `[m]hpmcounter15[h]`)
* minor RTL edits and cleanups
ℹ️ Moving the entire PMP/FPU CSR logic into optional (`if ... generate`) design units ensures that **all** of the logic is trimmed when the according module is not enabled.
=> ⚠️ Major code edits / cleanups

CHANGELOG.md, docs/datasheet/cpu.adoc, docs/datasheet/software_rte.adoc, rtl/core/neorv32_package.vhd, sw/example/demo_emulate_unaligned/main.c, sw/example/demo_emulate_unaligned/makefile, sw/lib/include/neorv32_rte.h, sw/lib/source/neorv32_rte.c
This PR updates the NEORV32 Runtime Environment (RTE) to support _easier_ emulation of unsupported CPU / SoC features like unimplemented instructions and even unaligned memory accesses.
The RTE now performs a full **context backup** of the interrupted application by storing all `x` integer registers to the stack. The base address of this stack frame is copied to the `mscratch` CSR. Dedicated "context access" function use this CSR value to provide easy access to the application context allowing reading and _altering_ of registers:
```c
// Prototypes
uint32_t neorv32_rte_context_get(int x); // read register x
void     neorv32_rte_context_put(int x, uint32_t data); write data to register x
// Examples
uint32_t tmp = neorv32_rte_context_get(9); // read register 'x9' …
```
=> Update RTE to support easy emulation of instructions

CHANGELOG.md, docs/datasheet/cpu.adoc, docs/datasheet/cpu_csr.adoc, docs/datasheet/software_rte.adoc, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_package.vhd, sw/example/demo_emulate_unaligned/main.c, sw/example/processor_check/main.c, sw/lib/include/neorv32_cpu_csr.h, sw/lib/source/neorv32_rte.c
* ⚠️ constrain `mtval` CSR - does no longer provide the faulting instruction word when an illegal instruction exception has been raised (allowed by RISC-V priv. spec.; simplifies hardware)
* add new `minstret` CSR that shows the (decompressed) instruction word for **all** synchronous exceptions
=> ⚠️ constrain MTVAL CSR, add MTINST CSR

CHANGELOG.md, docs/datasheet/on_chip_debugger.adoc, docs/datasheet/soc.adoc, rtl/core/neorv32_debug_dm.vhd, rtl/core/neorv32_debug_dtm.vhd, rtl/core/neorv32_package.vhd, rtl/core/neorv32_top.vhd, sw/ocd-firmware/park_loop.S, sw/openocd/openocd_neorv32.cfg
Triggered by @stokdam in https://github.com/stnolting/neorv32/pull/463#issuecomment-1690115103
This PR adds a new generic to the processor's top entity that allows to "downgrade" the on-chip debugger's debug module (DM) back to version 0.13.
* `DM_LEGACY_MODE = false`: DM is compatible to debug spec. version 1.0
* `DM_LEGACY_MODE = true`: DM is compatible to debug spec. version 0.13 (**legacy mode**)
This PR also provides some clean-ups and optimizations for the on-chip debugger modules (DTM & DM).
=> [OCD] add option to select DM legacy mode

CHANGELOG.md, docs/datasheet/cpu.adoc, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_package.vhd
This PR removes the CPU front end 's "branch prediction" logic that was used to halt instruction fetch while a branch/jump instruction is in progress until the destination address is available (resulting in less bus traffic / congestion).
However, benchmarks show that this prediction actually lowers performance:
Exemplary CoreMark run **with** branch prediction:
```
NEORV32: Hardware Performance Monitors (low words only)
> Active clock cycles:          2199671829
> Retired instructions:         596184106
> Retired compr. instructions:  349937868
> Instr.-fetch wait cycles:     34008506
> Instr.-issue wait cycles:     286243045
> Multi-cycle ALU wait cycles:  99331050
> Load operations:              108277848
> Store operations:             28390960
> Load/store wait cycles:       5984501 …
```
=> [cpu] remove branch prediction logic

CHANGELOG.md, docs/datasheet/cpu.adoc, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_package.vhd
raise illegal instruction exception if a multi-cycle instruction does not complete within a bound amount of time (default = 512 cycles); used to ensure that the FPU or CFU do not stall the CPU forever just because of an implementation flaw
=> [cpu] add execution monitor

CHANGELOG.md, docs/datasheet/cpu_cfu.adoc, docs/datasheet/cpu_csr.adoc, rtl/core/neorv32_cpu_alu.vhd, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_cpu_cp_cfu.vhd, rtl/core/neorv32_package.vhd, sw/example/demo_cfu/main.c, sw/lib/include/neorv32_cpu_cfu.h, sw/lib/include/neorv32_cpu_csr.h, sw/lib/source/neorv32_cpu_cfu.c, sw/openocd/openocd_neorv32.cfg
This PR allows to implement up to 2^32 CFU-internal ([Custom Functions Subsystem](https://stnolting.github.io/neorv32/#_custom_functions_unit_cfu) for user-defined RISC-V instructions) control and status registers (CSR) for additional operand propagation, configuration and status checking (i.e. passing a 256-bit key to an encryption module implemented within the CFU).
The CFU-CSR access mechanism uses an _indirect_ approach via just two CPU-CSRs:
* `cfusel` (address `0x800`) - CFU-internal CSR select ("CFU-CSR address")
* `cfureg` (address `0x801`) - CFU-internal CSR alias register ("CFU-CSR read/write data")
This concept is similar to the RISC-V [indirect-csr-access](https://github.com/riscv/riscv-indirect-csr-access) proposal.
=> [CFU] add support for CFU-internal CSRs

CHANGELOG.md, rtl/core/neorv32_cpu.vhd, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_cpu_pmp.vhd, rtl/core/neorv32_crc.vhd, rtl/core/neorv32_dcache.vhd, rtl/core/neorv32_debug_dm.vhd, rtl/core/neorv32_gpio.vhd, rtl/core/neorv32_icache.vhd, rtl/core/neorv32_neoled.vhd, rtl/core/neorv32_package.vhd, rtl/core/neorv32_pwm.vhd, rtl/core/neorv32_sdi.vhd, rtl/core/neorv32_slink.vhd, rtl/core/neorv32_spi.vhd, rtl/core/neorv32_sysinfo.vhd, rtl/core/neorv32_top.vhd, rtl/core/neorv32_trng.vhd, rtl/core/neorv32_twi.vhd, rtl/core/neorv32_uart.vhd, rtl/core/neorv32_wdt.vhd, rtl/core/neorv32_xirq.vhd, rtl/system_integration/neorv32_SystemTop_axi4lite.vhd
- constrain configuration generics (via `range`)
- minor VHDL code cleanups
- update AXI wrapper; add missing configuration options and signals
=> minor rtl edits

CHANGELOG.md, docs/datasheet/on_chip_debugger.adoc, docs/datasheet/soc.adoc, docs/datasheet/soc_wdt.adoc, rtl/core/neorv32_package.vhd, rtl/core/neorv32_top.vhd, rtl/core/neorv32_wdt.vhd, sw/example/demo_wdt/main.c, sw/example/processor_check/main.c, sw/lib/include/neorv32_wdt.h, sw/lib/source/neorv32_wdt.c, sw/svd/neorv32.svd
This PR adds a new register to the watchdog module (WDT) that is used to reset the internal timeout counter. A specific 32-bit word (a.k.a. "the password") has to be written to this register to actually reset the timer (making it less likely for a _rogue_ CPU to reset the WDT).
Additionally, the WDT now provides a "strict" bit in its control register. When enabled a hardware reset will be enforced if
* a wrong password is written to `RESET` or
* a write access is attempted to the control register while the LOCK bit is set
Furthermore, the processor's reset system is slightly reworked.
=> rework watchdog timer and reset system

CHANGELOG.md, docs/datasheet/cpu_csr.adoc, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_package.vhd, sim/neorv32_tb.vhd, sw/example/processor_check/main.c
Well hello there!
I stumbled upon this:
> An implementation may have different alignment constraints for different modes. In particular, MODE=Vectored may have stricter alignment constraints than MODE=Direct.
> [...]
> Allowing coarser alignments in Vectored mode enables vectoring to be implemented without a hardware adder circuit.
Which I found very interesting and thought we could implement that! It could shorten the latency from IRQ to calling the right ISR as no intermediate generic handler is required. A simple `jal zero, <function>` as mtvec jump table could directly jump to the handler.
Example jump table:
```assembly
.balign 128 // 128 byte alignment i.e. lowest 7 bits all zero
mtvec_jump_table:
jal zero, trap_handler          //  0 - exception (all)
nop …
```
=> implement vectored `mtvec`

CHANGELOG.md, docs/datasheet/cpu.adoc, rtl/core/neorv32_cpu.vhd, rtl/core/neorv32_cpu_alu.vhd, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_cpu_lsu.vhd, rtl/core/neorv32_dma.vhd, rtl/core/neorv32_gpio.vhd, rtl/core/neorv32_intercon.vhd, rtl/core/neorv32_onewire.vhd, rtl/core/neorv32_package.vhd, rtl/core/neorv32_twi.vhd, rtl/core/neorv32_wdt.vhd
* simplify TWI transfer trigger logic
* optimize CPU control logic (less logic in EXECUTE state; simplify debug mode controller)
* clean-up load/store unit (use buy type for IO; move bus access type logic to LSU)
* use _bus types_ for CPU front-end and load/store unit bus interfaces
* minor code clean-ups
=> Minor rtl optimizations and cleanups

CHANGELOG.md, rtl/core/neorv32_cpu.vhd, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_cpu_pmp.vhd, rtl/core/neorv32_package.vhd
* simplify memory access type logic (read/write)
* simplify PMP priority logic (reducing area requirements)
* make sure `mret` raises an illegal instruction when in debug mode
=> [PMP] logic optimization

sw/lib/include/neorv32_cpu.h
Warning removed of unused variable for neorv32_cpu_load_reservate_word and neorv32_cpu_store_conditional_word.
=> [SW] Warning removed of unused variable

sw/example/coremark/core_portme.c
The CoreMark is used in Machine-Mode, therefore the access to CSR_MCOUNTEREN can
be removed. The access to CSR_MCOUNTEREN is for User-Mode.
=> [SW] Illegal instruction removed

CHANGELOG.md, docs/datasheet/soc_dma.adoc, rtl/core/neorv32_dma.vhd, rtl/core/neorv32_package.vhd, sw/example/demo_dma/main.c, sw/example/processor_check/main.c, sw/lib/include/neorv32_dma.h, sw/lib/source/neorv32_dma.c, sw/svd/neorv32.svd
Add a new flag to the DMA's control register to indicate that a configured transfer has actually been executed.
:warning: The done flag does not indicate that the transfer was successful. Check the control register's error flags to check if the transfer caused any errors.
✔️ Feature suggested by @DS-567 in https://github.com/stnolting/neorv32/discussions/689.
=> [dma] add "transfer done" flag

.github/workflows/Processor.yml, CHANGELOG.md, do.py, docs/datasheet/software.adoc, rtl/core/neorv32_package.vhd, sw/common/common.mk, sw/example/demo_freeRTOS/makefile, sw/example/demo_freeRTOS_xirq/makefile, sw/example/processor_check/run_check.sh, sw/ocd-firmware/makefile
* `march` now requires `_zicsr` when using CSR access instructions (`Zicsr` ISA extension)
* `march` now requires `_zifencei` when using the instruction fence instruction (`Zifencei` ISA extension)
=> Update software framework to gcc-13.2.0

CHANGELOG.md, rtl/core/neorv32_cpu.vhd, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_cpu_regfile.vhd, rtl/core/neorv32_debug_dm.vhd, rtl/core/neorv32_package.vhd, rtl/core/neorv32_wdt.vhd, sw/example/processor_check/main.c
* cleanup redundant signals
* minor optimizations of branch system
* fix register override in RTE context edit test case (processor_check)
=> [cpu] minor cleanups and optimizations

CHANGELOG.md, docs/datasheet/cpu.adoc, docs/datasheet/soc.adoc, docs/userguide/customizing_the_bootloader.adoc, docs/userguide/debugging_with_ocd.adoc, rtl/core/neorv32_cpu.vhd, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_package.vhd, rtl/core/neorv32_top.vhd, rtl/processor_templates/neorv32_ProcessorTop_UP5KDemo.vhd, rtl/system_integration/neorv32_SystemTop_AvalonMM.vhd, rtl/system_integration/neorv32_SystemTop_axi4lite.vhd, rtl/system_integration/neorv32_litex_core_complex.vhd, rtl/test_setups/neorv32_test_setup_on_chip_debugger.vhd, sim/neorv32_tb.vhd, sim/simple/neorv32_tb.simple.vhd, sw/example/processor_check/main.c
The `Zifencei` ISA extension does not consume any relevant amount of resources plus it is mandatory for the on-chip debugger. In order to simplify configuration options this ISA extension is now always automatically enabled.
=> ⚠️ remove Zifencei generic - Zifencei ISA extension is now always enabled

sw/lib/include/neorv32_uart.h, sw/lib/source/neorv32_uart.c
=> [sw/lib] add nerov32-flavored vprintf funtion

docs/datasheet/software.adoc, sim/simple/ghdl.run.sh, sim/simple/ghdl.sh, sw/common/common.mk
This PR adds a new variable to the application makefile (`GHDL_RUN_FLAGS`) that allows to customize / override the simulation parameters (e.g. constraining the run time by `GHDL_RUN_FLAGS=--stop-time=1ms`).
=> [sim] Add GHDL run flags variable

sw/lib/source/neorv32_slink.c
In specific in *neorv32_slink_available()* function.
I added a [module](https://github.com/Unike267/Practices) to NEORV32 via Stream Link interface (AXI4-Stream) and I used in *.c* program *neorv32_slink_available()* function to check if SLINK module was available. The point is that I put the *IO_SLINK_EN => true* in the top of the design and when I checked the results via UART the program crashed because *neorv32_slink_available()* return -1 when the SLINK module was available. 
I checked the *neorv32_slink.c* and **I found this bug**. 
When I remade the *application_image* compiled with the fixed-up library  in local everything was good. I got the following results with CuteCom terminal:
/cc @umarcor
=> Fix bug in neorv32_slink_available() function

CHANGELOG.md, docs/datasheet/soc_trng.adoc, rtl/core/neorv32_package.vhd, rtl/core/neorv32_trng.vhd, sw/example/demo_trng/main.c
https://github.com/stnolting/neoTRNG
=> [rtl] upgrade neoTRNG to version 3

rtl/system_integration/neorv32_litex_core_complex.vhd
+ Board: ARTY A7 35T
I'm trying to implement the Neorv32 with Litex and with the deffault wrapper **there is a failure with the SDRAM initialization**. View enjoy-digital/litex#1802.
I tried changing the wishbone protocol from *pipelined* to *classic*, and that seems to fix the issue.
It might have some effect in performance, but at least it works.
The following log shows that memory is correctly initialized.
Looking forward, I believe there might be some conflict in the pipelined wishbone implementations of NEORV32 and Litex. @stnolting did you try the pipelined wishbone of NEORV32 with third-party wishbone peripherals?
/cc @enjoy-digital @umarcor
=> Fix-up the litex wrapper

CHANGELOG.md, docs/datasheet/soc_spi.adoc, rtl/core/neorv32_package.vhd, rtl/core/neorv32_spi.vhd, sw/lib/include/neorv32_spi.h, sw/lib/source/neorv32_spi.c
Add a new control register flag to override the clock presclaer selection. When set, the effective clock speed is f_main / 2. Fine-tuning of the clock is still possible by using the 4-bit clock divider bits.
:bug: This PR also fixes a bug in the SPI shift register that was introduced within the last version.
=> [SPI] re-add high-speed mode

CHANGELOG.md, docs/datasheet/soc_xip.adoc, rtl/core/neorv32_bootloader_image.vhd, rtl/core/neorv32_package.vhd, rtl/core/neorv32_xip.vhd, sw/bootloader/bootloader.c, sw/example/demo_xip/main.c, sw/lib/include/neorv32_xip.h, sw/lib/source/neorv32_xip.c, sw/svd/neorv32.svd
This PR adds a 4-bit clock divider `XPI_CTRL_CDIVx` to the XIP's SPI interface allowing fine-tuning of the SPI clock (similar to the SPI module configuration options).
```
f_spi = f_main / (2 * clock_prescaler * (1 + XPI_CTRL_CDIVx))
```
=> [XIP] add clock divider for fine-tuning

CHANGELOG.md, docs/datasheet/cpu.adoc, rtl/core/neorv32_cpu_cp_fpu.vhd, rtl/core/neorv32_package.vhd, sw/example/floating_point_test/main.c
Triggered by #728 this PR fixes the wiring of the FPU exception flag output and the `fflags` CSR bits.
=> 🐛 [FPU] fix wiring of exception flags

CHANGELOG.md, do.py, docs/datasheet/cpu.adoc, docs/datasheet/cpu_csr.adoc, docs/datasheet/on_chip_debugger.adoc, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_package.vhd, sim/neorv32_tb.vhd, sim/simple/neorv32_tb.simple.vhd, sw/example/processor_check/main.c, sw/example/processor_check/run_check.sh
Bug identified by @mikaelsky in https://github.com/stnolting/neorv32/issues/728#issuecomment-1819638160.
The current processor version captures unaligned instruction addresses in the pipeline's front-end. Hence, any misaligned instruction will still trigger an instruction fetch and jump-and-link instruction will still update the link register. This PR aims to fix this:
* Branch instructions (unconditional branches or "taken" conditional branches) do not trigger an instruction fetch if the address is misaligned.
* Jump-and-link instruction do not write to the link register if the destination address is misaligned.
* Misaligned instruction address exception are raised by the pipeline's back end (execution) and not by the pipeline's front-end (instruction fetch).
I am not quite sure about …
=> 🐛 fix bug in instruction-misaligned exception handling

CHANGELOG.md, rtl/core/neorv32_cpu.vhd, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_cpu_regfile.vhd, rtl/core/neorv32_package.vhd
* cleaner code
* much higher f_max
=> [rtl] cleanup & rework/optimize CPU branch system

CHANGELOG.md, docs/datasheet/cpu.adoc, docs/datasheet/cpu_csr.adoc, docs/datasheet/soc.adoc, rtl/core/neorv32_cpu.vhd, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_cpu_regfile.vhd, rtl/core/neorv32_package.vhd, rtl/core/neorv32_top.vhd, sim/neorv32_tb.vhd, sim/simple/neorv32_tb.simple.vhd, sw/lib/include/neorv32_cpu_csr.h, sw/lib/source/neorv32_rte.c
This PR adds a new "CPU tuning" configuration generic that allows to adapt the architecture style of the CPU's general purpose data register file:
```vhdl
REGFILE_HW_RST : boolean := false;
```
* default case
* register file is implemented as plain memory array
* will infer block RAM / maps to FPGA memory resources
* **no** dedicated hardware reset of the register file
* register `x0/zero` is implemented as physical register that has to be explicitly cleared (done transparently by the CPU control hardware)
* recommended for FPGA designs
* register file is implemented as individual flip flops
* 31*31=992 FFs for `rv32i`
* 15*32=480 FFs for `rv32e`
* cannot be mapped to FPGA block RAM
* **full** dedicated hardware reset of the register file
* register `x0/zero` is hardwired to zero
* …
=> ✨ Add "ASIC style" register file option

CHANGELOG.md, rtl/core/mem/neorv32_imem.default.vhd, rtl/core/mem/neorv32_imem.legacy.vhd, rtl/core/neorv32_cpu.vhd, rtl/core/neorv32_cpu_cp_bitmanip.vhd, rtl/core/neorv32_cpu_cp_fpu.vhd, rtl/core/neorv32_cpu_pmp.vhd, rtl/core/neorv32_dcache.vhd, rtl/core/neorv32_debug_dm.vhd, rtl/core/neorv32_icache.vhd, rtl/core/neorv32_intercon.vhd, rtl/core/neorv32_package.vhd, rtl/core/neorv32_top.vhd, rtl/core/neorv32_wishbone.vhd
Invalid generic configurations (for example a cache block size that is not a power of two) will no longer result in an error assertion. Instead, the invalid configuration is auto-adjusted and the user is informed with a warning. For example:
```vhdl
assert not ((nblocks_valid_c = false) or (block_size_valid_c = false)) report
"[NEORV32] Auto-adjusting invalid d-cache size configuration(s)." severity warning;
```
=> [rtl] Cleanup/update assertions and "auto-configuration"

CHANGELOG.md, docs/datasheet/cpu_csr.adoc, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_package.vhd, sw/lib/include/neorv32_cpu_csr.h
According to the RISC-V priv. spec. these CSRs seem to be mandatory (i.e. they have to be implemented if the `U` ISA extension is enabled). However, the features provided by these CSRs are not supported yet. Hence, the entire CSRs are hardwired to all-zero.
=> Add menvcfg[h] CSRs

docs/datasheet/software_rte.adoc, sw/lib/include/neorv32_rte.h, sw/lib/source/neorv32_rte.c
Update NEORV32 runtime environment (RTE)
* make sure that all public function of the RTE can be called from machine-mode only (raise exception otherwise)
* add debug function to print the current state of the RTE handler table (`neorv32_rte_print_info()`)
* make sure the RTE core does not save/restore the upper 16 x register when compiling for `rv32e`
=> [RTE] minor updates

CHANGELOG.md, docs/datasheet/cpu_csr.adoc, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_package.vhd
https://github.com/stnolting/neorv32/issues/728#issuecomment-1839300998 by @mikaelsky
=> [rtl] reset mstatus.mpp to machine-mode

CHANGELOG.md, docs/datasheet/cpu.adoc, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_package.vhd
The CPU's `sleep_o` signal get high when
* the CPU has entered sleep mode (`wfi` instruction)
* **and** all pending bus accesses (i.e. instruction fetch) have completed
* -> the CPU is safely "parked"
=> refine behaviour of CPU sleep signal

CHANGELOG.md, rtl/core/neorv32_fifo.vhd, rtl/core/neorv32_package.vhd
code clean-up + fix problem with inferring BRAM (discovered by @doud3157)
=> [rtl] rework FIFO module (to allow inferring block RAM)

CHANGELOG.md, docs/datasheet/soc.adoc, docs/datasheet/soc_mtime.adoc, rtl/core/neorv32_mtime.vhd, rtl/core/neorv32_package.vhd, rtl/core/neorv32_top.vhd, sim/neorv32_tb.vhd, sim/simple/neorv32_tb.simple.vhd
This PR adds again `mtime_o` to the top entity to retain the ability to retrieve the wall clock time (mtime) from the HDL gateware. (#761)
=> [rtl/core] add again mtime_o to top entity

CHANGELOG.md, rtl/core/neorv32_cpu_cp_shifter.vhd, rtl/core/neorv32_package.vhd
=> [rtl] fix minor VHDL coding style issue

CHANGELOG.md, rtl/core/neorv32_cfs.vhd, rtl/core/neorv32_cpu_alu.vhd, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_cpu_cp_cfu.vhd, rtl/core/neorv32_cpu_cp_fpu.vhd, rtl/core/neorv32_cpu_cp_shifter.vhd, rtl/core/neorv32_fifo.vhd, rtl/core/neorv32_intercon.vhd, rtl/core/neorv32_package.vhd, rtl/core/neorv32_top.vhd, sw/example/demo_cfu/main.c
Minor VHDL code cleanups and logic optimization (less area).
=> [rtl] minor cleanups and optimizations

CHANGELOG.md, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_cpu_decompressor.vhd, rtl/core/neorv32_package.vhd, sw/example/processor_check/main.c
Compressed floating point load/store operations are not supported by the `Zfinx` ISA extension and have to trap.
Bug identified by @mikaelsky in #770.
=> :bug: Remove RVC float load/store instructions

CHANGELOG.md, docs/datasheet/cpu.adoc, docs/datasheet/overview.adoc, docs/datasheet/soc.adoc, docs/datasheet/soc_sysinfo.adoc, rtl/core/neorv32_clockgate.vhd, rtl/core/neorv32_cpu.vhd, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_package.vhd, rtl/core/neorv32_sysinfo.vhd, rtl/core/neorv32_top.vhd, sim/neorv32_tb.vhd, sim/simple/neorv32_tb.simple.vhd, sw/lib/include/neorv32_sysinfo.h, sw/lib/source/neorv32_rte.c, sw/svd/neorv32.svd
This PR adds an optional clock gating mechanism to the processor. When enabled, the clock of the CPU core is shut down during sleep mode to reduce power consumption. This concept was developed/proposed by @mikaelsky in #772.
* add new top generic 'CLOCK_GATING_EN', default "false"
* add new VHDL module `neorv32_clockgate.vhd` that implements the clock switch
A secondary, always-on clock is added to the CPU. This additional clock is used to keep the interrupt buffer logic active while the rest of the CPU is switched off. Any (enabled) interrupt request (including a debug halt request) will make the CPU leave sleep mode.
The CPU's sleep signal is set high only when
* the execution stage has halted (no pending memory access in progress) **and**
* the instruction fetch stage is halted (no …
=> ✨ add optional CPU clock gating

CHANGELOG.md, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_package.vhd
Fix typo in CPU control that renders the clock gating (added in v1.9.3.4) useless: SLEEP output signal stuck at zero.
=> :bug: fix typo that renders the clock gating useless

CHANGELOG.md, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_package.vhd
A simple yet efficient optimization that reduces wait/restart cycles when branching. Improves overall performance by approx. 8% (CoreMark benchmark).
This also fixes #773.
=> [rtl] improve CPU front end

CHANGELOG.md, rtl/core/neorv32_fifo.vhd, rtl/core/neorv32_package.vhd
fifo.vhd has been updated to reflect feedback. Changes has been verified to not cause issues with assertions.
Added a tweak to the write path to make read and write symmetric allowing some flops to potentially be saved for FIFOs of size 1.
=> Updated FIFO NULL assertion fix

CHANGELOG.md, docs/datasheet/soc.adoc, rtl/core/neorv32_package.vhd, rtl/core/neorv32_top.vhd
using VHDL's "weak driver strengths" to model a pull-down / pull-up "resistor" in case these signals are not explicitly assigned during instantiation
=> set top entiy input defaults to 'L' or 'H'

CHANGELOG.md, docs/datasheet/soc.adoc, rtl/core/neorv32_package.vhd, rtl/core/neorv32_top.vhd
When the CPU is in sleep mode and clock gating is enabled the CPU itself is shut down. With this PR this switchable clock domain is extended (red box in the figure below):
- the CPU bus switched is shut down
- both caches - if implemented - are shut down
=> 🧪 extend switchable clock domain

CHANGELOG.md, rtl/core/neorv32_cpu_decompressor.vhd, rtl/core/neorv32_package.vhd
Added a illegal instruction exception to the register to register branch of the compressed instruction decoder.
=> Fix for issue #782

CHANGELOG.md, docs/datasheet/cpu.adoc, rtl/core/neorv32_cpu.vhd, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_package.vhd, sw/lib/include/neorv32_cpu_csr.h, sw/lib/include/neorv32_rte.h, sw/lib/source/neorv32_rte.c
This PR adds support for three additional RISC-V exceptions:
* instruction page fault (`mcause = 0x0000000c`)
* load page fault (`mcause = 0x0000000f`)
* store page fault (`mcause = 0x0000000d`)
Right now the trigger signals for these exceptions are unused and terminated / hardwired to zero within the CPU's top entity. Hence, the hardware overhead for implementing those new trap should be zero.
I am experimenting with a very simple MMU-like paging concept but I am not really sure if this would be beneficial for any "real-world" applications. However, this might be the first step toward supervisor-mode and virtual memory support.
As always, ideas and thoughts are highly welcome. :wink:
=> Add support for page fault exceptions

CHANGELOG.md, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_package.vhd
The privilege level signal `.priv` of the CPU's instruction request bus was hardwired so it always showed "user-mode" instead of the actual privilege mode.
=> [cpu] fix minor bug in instruction request bus

rtl/core/neorv32_cpu_cp_fpu.vhd
Patched up my fixes to the FPU to the current mainline from my local 1.9.3.0 checkout.
There are still challenges but these fixes makes the following riscof-arch F -> Zfinx tests pass:
rv32i_m_Zfinx_fadd_b1
rv32i_m_Zfinx_fadd_b10
rv32i_m_Zfinx_fadd_b11
rv32i_m_Zfinx_fadd_b12
rv32i_m_Zfinx_fadd_b13
rv32i_m_Zfinx_fadd_b2
rv32i_m_Zfinx_fadd_b3
rv32i_m_Zfinx_fadd_b4
rv32i_m_Zfinx_fadd_b5
rv32i_m_Zfinx_fadd_b7
rv32i_m_Zfinx_fadd_b8
rv32i_m_Zfinx_fclass_b1
rv32i_m_Zfinx_fcvt.s.w_b25
rv32i_m_Zfinx_fcvt.s.w_b26
rv32i_m_Zfinx_fcvt.s.wu_b25
rv32i_m_Zfinx_fcvt.s.wu_b26
rv32i_m_Zfinx_fcvt.w.s_b1
rv32i_m_Zfinx_fcvt.w.s_b22
rv32i_m_Zfinx_fcvt.w.s_b23
rv32i_m_Zfinx_fcvt.w.s_b24
rv32i_m_Zfinx_fcvt.w.s_b27
rv32i_m_Zfinx_fcvt.w.s_b28
rv32i_m_Zfinx_fcvt.w.s_b29
rv32i_m_Zfinx_fcvt.wu.s_b1 …
=> Fix for issue #785: FPU fflags no being asserted correctly

CHANGELOG.md, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_package.vhd
The `.priv` signal of the CPU's instruction request interface did not remain stable during the entire access. This PR aims to fix that.
=> 🐛 [cpu] fix non-stable privilege signal of instruction interface

CHANGELOG.md, rtl/core/neorv32_cpu_decompressor.vhd, rtl/core/neorv32_package.vhd
=> [CPU] close further illegal instruction loopholes

CHANGELOG.md, docs/datasheet/cpu.adoc, docs/datasheet/soc.adoc, docs/datasheet/soc_dcache.adoc, docs/datasheet/soc_icache.adoc, docs/datasheet/soc_xip.adoc, rtl/core/neorv32_cpu.vhd, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_cpu_lsu.vhd, rtl/core/neorv32_dcache.vhd, rtl/core/neorv32_dma.vhd, rtl/core/neorv32_icache.vhd, rtl/core/neorv32_intercon.vhd, rtl/core/neorv32_package.vhd, rtl/core/neorv32_top.vhd, rtl/core/neorv32_xip.vhd, rtl/system_integration/neorv32_SystemTop_AvalonMM.vhd, rtl/system_integration/neorv32_SystemTop_axi4lite.vhd, sim/neorv32_tb.vhd, sim/simple/neorv32_tb.simple.vhd
* add new signal to CPU request bus: `.fence` - high for one cycle when a `fence` or `fence.i` instruction is executed; valid without `.stb` being set
* :warning: removed top entity's `fence_o` and `fencei_o`; will be re-added as part of the processor's external bus interface (WISHBONE)
=> add fence signal to CPU bus

CHANGELOG.md, rtl/core/neorv32_dcache.vhd, rtl/core/neorv32_icache.vhd, rtl/core/neorv32_package.vhd, rtl/core/neorv32_xip.vhd
Bug introduced in previous version (1.9.4.7).
=> :bug: fix fence signal pass-through in caches

CHANGELOG.md, docs/datasheet/soc_dma.adoc, rtl/core/neorv32_dma.vhd, rtl/core/neorv32_package.vhd, sw/example/demo_dma/main.c, sw/example/processor_check/main.c, sw/lib/include/neorv32_dma.h, sw/lib/source/neorv32_dma.c, sw/svd/neorv32.svd
Optionally, the DMA can issue a FENCE request to the downstream memory system when a transfer has been completed without errors. This can be used to re-sync caches (flush and reload) and buffers to maintain data coherency. This automatic fencing is enabled by the setting the control register's `DMA_CTRL_FENCE` bit.
=> Add DMA fence operation

CHANGELOG.md, docs/datasheet/cpu.adoc, docs/datasheet/cpu_csr.adoc, docs/datasheet/soc.adoc, rtl/core/neorv32_cpu.vhd, rtl/core/neorv32_cpu_pmp.vhd, rtl/core/neorv32_package.vhd, rtl/core/neorv32_top.vhd, sim/neorv32_tb.vhd, sim/simple/neorv32_tb.simple.vhd
Add two new generics to disable certain PMP modes (to reduce CPU size / impact on critical path):
* `PMP_TOR_MODE_EN` (boolean, default _true_): implement top-of-region (TOP) mode when true
* `PMP_NAP_MODE_EN` (boolean, default _true_): implement naturally-aligned-power-of-2 modes (NA4 and NAPOT) modes when true
=> Allow disabling certain PMP modes

CHANGELOG.md, docs/datasheet/cpu.adoc, rtl/core/neorv32_cpu.vhd, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_package.vhd, sw/lib/include/neorv32_cpu_csr.h, sw/lib/include/neorv32_rte.h, sw/lib/source/neorv32_rte.c
Reverting the changes from #786. Keep support for page faults in [mmu development branch](https://github.com/stnolting/neorv32/tree/mmu_dev) for now.
=> [revert] remove page faults support

docs/datasheet/software.adoc, sw/common/common.mk, sw/example/coremark/core_portme.h
Pass the makefile's `CC_OPTS` variable, which contains all relevant GCC flags and switches, as "define" string to the application:
```makefile
CC_FLAGS = $(CC_OPTS)
CC_FLAGS += -DCC_OPTS="\"$(CC_OPTS)\""
```
Application software can use this "define" to print the actual GCC configuration that was used to compile the code:
```c
neorv32_uart0_printf("%s\n", CC_OPTS);
```
=> 🧪 [makefile] pass CC_OPTS variable as define string

.github/workflows/Processor.yml, sim/simple/ghdl.run.sh, sw/example/hello_world/makefile, sw/example/processor_check/makefile, sw/example/processor_check/run_check.sh
Coming from #816, this PR moves the cat-grep assert from the simulation shell script to the Makefile of the corresponding software program. In order to do so, target `sim-check` is added, which depends on `sim`.
This approach allows us to have per-program checks. In order to showcase the feature, I added a check to `hello_world` as well.
See a successful execution https://github.com/umarcor/neorv32/actions/runs/7977125739 and failures when I changed the strings in the software on purpose: https://github.com/umarcor/neorv32/actions/runs/7977200433.
=> [sim] add simulation check to sw makefiles as target 'sim-check'

CHANGELOG.md, docs/datasheet/soc.adoc, docs/datasheet/soc_slink.adoc, rtl/core/neorv32_package.vhd, rtl/core/neorv32_slink.vhd, rtl/core/neorv32_top.vhd, rtl/system_integration/neorv32_SystemTop_axi4lite.vhd, sim/neorv32_tb.vhd, sim/simple/neorv32_tb.simple.vhd, sw/example/demo_slink/main.c, sw/example/processor_check/main.c, sw/lib/include/neorv32_slink.h, sw/lib/source/neorv32_slink.c, sw/svd/neorv32.svd
Add native hardware support for the AXI-stream-compatible `tlast` signals that are used to identify the last data word of a stream.
Add new top signals:
```vhdl
slink_rx_lst_i : in  std_ulogic := 'L'; -- last element of stream
slink_tx_lst_o : out std_ulogic; -- last element of stream
```
⚠️ Reworked SLINK low-level driver / HAL. The SLINK module now uses four memory-mapped interface registers for control and data transfers. See the updated documentation.
ℹ️ The updated HAL is fully backwards-compatible.
🚀 Discussed in https://github.com/stnolting/neorv32/discussions/795; triggered by @Giorgio122.
=> [SLINK] add AXI-stream-compatible "tlast" signals

docs/userguide/simulating_the_processor.adoc
As discussed in #816, this PR brings a couple of enhancements to the Simulation section of the User Guide.
On the one hand, an admonition is added for users to know that using instructions corresponding to unsupported/disabled extensions will make the processor hung and the simulation will timeout.
On the other hand, the recommended MARCH to build hello_world is changed not to use extension C, since that's disabled in the simple testbench.
=> [docs/userguide/simulating_the_processor] add admonition and recommend MARCH=rv32im to build hello_world

CHANGELOG.md, docs/datasheet/cpu_csr.adoc, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_package.vhd, sw/lib/include/neorv32_cpu_csr.h
Fixing #818 
Write accesses to the `mip` FIRQ CSR bits always impacted **all** FIRQ bits (making clearing/acknowledging a single FIRQ impossible). As a side-effect of this fix the `mip.firq` bits are now read-write. Hence, software can trigger FIRQ manually by writing `1` to the according FIRQ bits.
=> 🐛 Fix write access to mip.firq CSR bits

.github/workflows/Processor.yml
This PR is based on #820 ~, so I'll keep it as a draft until that one is merged~.
As discussed in #816, this PR adds testing example hello_world to CI workflow Processor.
The same job as for processor_check is used. This PR just adds a matrix to execute multiple jobs, one per example code.
=> [ci] test example hello_world as well

CHANGELOG.md, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_fifo.vhd, rtl/core/neorv32_neoled.vhd, rtl/core/neorv32_package.vhd, rtl/core/neorv32_sdi.vhd, rtl/core/neorv32_slink.vhd, rtl/core/neorv32_spi.vhd, rtl/core/neorv32_trng.vhd, rtl/core/neorv32_uart.vhd
Vivado was not able to infer block RAM / LUT-RAM for the FIFO memory.
@robhancocksed, @mikaelsky, @umarcor
=> [fifo] fix (Vivado) synthesis issue

docs/userguide/packaging_vivado.adoc, rtl/system_integration/neorv32_SystemTop_axi4lite.vhd
Fixes Vivado clock domain warnings/errors when connecting SLINK interfaces to other AXI4-Stream components, as described in https://github.com/stnolting/neorv32/issues/825
=> Added dummy clocks for SLINK streams in AXI4-Lite wrapper

CHANGELOG.md, docs/datasheet/cpu.adoc, docs/datasheet/cpu_csr.adoc, docs/datasheet/on_chip_debugger.adoc, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_package.vhd, sim/neorv32_tb.vhd, sw/example/processor_check/main.c, sw/lib/include/neorv32_cpu_csr.h
This is a rework of #821 trying to finally fix #818.
CSR bits that can change at _any_ time and provide clear-only behavior need special handling when performing CSR write/clear/set operations. The modifications from this PR ensure that only the intended bits are touched at all.
Effected CSRs:
* `mip[.firq]`
* `tdata1[.hit]`
:warning: `mip` is clear-only again - writing ones has no effect at all (reverting the access changes from #821).
=> :bug: fix atomic write/clear/set accesses of clear-only CSR bits

sw/common/common.mk, sw/ocd-firmware/makefile
While trying to build and install the bootloader on MSYS2 following my notes from #55, I found the following typo: `s/RISCV_TOLLCHAIN/RISCV_TOOLCHAIN/`. So I fixed it.
However, then I found out that it seems not to be used anymore. Now `RISCV_PREFIX` is used: `RISCV_PREFIX=riscv64-unknown-elf- MARCH=rv32i make -C sw/bootloader/ install`. Therefore, I removed it. Yet, I don't know if that's correct.
@stnolting wdyt?
=> [sw] remove unused variable RISCV_TOOLCHAIN

CHANGELOG.md, rtl/core/neorv32_gptmr.vhd, rtl/core/neorv32_package.vhd, sw/example/processor_check/main.c
If the GPTMR's threshold value is set to zero (yes, this is just a corner case) it should immediately trigger an interrupt (if enabled). This PR fixes this.
=> :bug: fix GPTMR threshold = 0 configuration

docs/userguide/programming_an_external_spi_flash_via_bootloader.adoc
Updated user guide command to program external flash from 'p' to 's' to match the bootloader program.
Bootloader help prompt output is reproduced below:
> Autoboot in 8s. Press any key to abort.
Aborted.
Available CMDs:
h: Help
r: Restart
u: Upload
s: Store to flash
l: Load from flash
x: Boot from flash (XIP)
e: Execute
CMD:>
=> Small correction in user guide

CHANGELOG.md, docs/datasheet/cpu.adoc, rtl/core/neorv32_cache.vhd, rtl/core/neorv32_package.vhd, sim/neorv32_tb.vhd, sw/common/common.mk, sw/example/processor_check/main.c
This PR adds a new generic cache module that ~~will~~ _might_ replace the I- and D-cache modules. Right now, this new cache module is not used at all by the default processor setup.
Cache specs:
* direct-mapped, configurable block size ("cache lines"), configurable number of blocks
* **write-back** strategy: write back dirty cache blocks when the block is replaced
* **write-allocate**: a write miss will load the entire block from memory
* supports direct (uncached) memory accesses
=> [rtl] add generic cache module (not used yet)

CHANGELOG.md, rtl/core/neorv32_cache.vhd, rtl/core/neorv32_icache.vhd, rtl/core/neorv32_package.vhd, rtl/core/neorv32_top.vhd
* i-cache: do not allow reservation set operations; issue downstream fence at the end of a clear operation
* generic cache module (XCACHE): add option to make cache read-only; add option to disable uncached/direct accesses; both options are not used yet by the default processor setup and are still experimental
=> Minor cache updates

rtl/system_integration/neorv32_litex_core_complex.vhd
Remove I- and D-caches, just use the external bus cache (XCACHE).
=> [litex] update core complex wrapper

CHANGELOG.md, docs/datasheet/cpu_cfu.adoc, rtl/core/neorv32_cpu_cp_cfu.vhd, rtl/core/neorv32_package.vhd, sw/example/demo_cfu/main.c
This PR is a rework of the **Custom Functions Unit (CFU)** that replaces the default example application by a "real world" application implementing the royalty-free [Extended Tiny Encryption Algorithm (XTEA)](https://en.wikipedia.org/wiki/XTEA) as dedicated ISA extension implemented as CFU-based custom RISC-V instructions.
The according demo program computes the encryption and decryption of random data using a 1.) software-only reference and a 2.) hardware-accelerated version using 5 custom XTEA instructions:
```
neorv32/sw/example/demo_cfu$ make USER_FLAGS+=-DUART0_SIM_MODE clean_all sim
[...]
<<< NEORV32 Custom Functions Unit (CFU) - Custom Instructions Example >>>
[NOTE] This program assumes the default CFU hardware module that
implements the Extended Tiny Encryption Algorithm (XTEA). …
```
=> Update CFU example: use XTEA as "real world" demo application

CHANGELOG.md, rtl/core/neorv32_cache.vhd, rtl/core/neorv32_cpu.vhd, rtl/core/neorv32_cpu_alu.vhd, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_cpu_lsu.vhd, rtl/core/neorv32_cpu_regfile.vhd, rtl/core/neorv32_intercon.vhd, rtl/core/neorv32_package.vhd, rtl/core/neorv32_top.vhd
* made interconnect's gateway more generic (in case someone wants to use it for building custom bus systems)
* optimize CPU data path
* smaller hardware footprint (~5% smaller)
* shortened critical path (134MHz, CPU-only, Cyclone 4)
=> CPU RTL optimization

CHANGELOG.md, docs/datasheet/soc_onewire.adoc, rtl/core/neorv32_cfs.vhd, rtl/core/neorv32_gptmr.vhd, rtl/core/neorv32_onewire.vhd, rtl/core/neorv32_package.vhd, rtl/core/neorv32_sdi.vhd
The interrupt of the ONEWIRE module will now become set whenever the module is in idle state (e.g. after completing an operation).
The GPTMR timer interrupt will now remain pending until explicitly cleared by writing zero to the module's `GPTMR_CTRL_TRIGM` and/or `GPTMR_CTRL_TRIGC` control register bits (depneing on the interrupt trigger configuration).
> [!NOTE]
> This PR is part of a series that aims to _unify_ (and simplify) the entire interrupt system of the processor.
=> :warning: rework ONEWIRE and GPTMR interrupts

CHANGELOG.md, docs/datasheet/soc_dma.adoc, docs/datasheet/soc_twi.adoc, docs/datasheet/soc_xirq.adoc, rtl/core/neorv32_dma.vhd, rtl/core/neorv32_package.vhd, rtl/core/neorv32_twi.vhd, rtl/core/neorv32_xirq.vhd, sw/lib/source/neorv32_xirq.c
The interrupt of the TWI module will now become set whenever the module is in idle state (e.g. after completing an operation).
The CPU interrupt of the XIRQ module will now _stay_ high until explicitly acknowledge by writing to the module's `ESC` register.
> [!NOTE]
> This PR is part of a series that aims to _unify_ (and simplify) the entire interrupt system of the processor.
=> :warning: rework TWI interrupt

CHANGELOG.md, docs/datasheet/cpu.adoc, docs/datasheet/cpu_csr.adoc, docs/datasheet/soc.adoc, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_dma.vhd, rtl/core/neorv32_package.vhd, sim/neorv32_tb.vhd, sw/example/demo_dma/main.c, sw/example/demo_gptmr/main.c, sw/example/demo_slink/main.c, sw/example/demo_spi_irq/drv/neorv32_spi_irq.c, sw/example/processor_check/main.c, sw/lib/include/neorv32_cpu.h, sw/lib/include/neorv32_cpu_csr.h, sw/lib/source/neorv32_cpu.c, sw/lib/source/neorv32_rte.c, sw/lib/source/neorv32_xirq.c
Bit 2 of the control register should be used for this but the hardware was using bit 3.
The standard RISC-V machine interrupt (like the timer interrupt MTI) are level-triggered. With this PR the NEORV32-specific fast interrupt requests (FIRQs) now also follow this standard.
`mip` shows all current pending interrupt sources (all interrupt lines that are high). Writing to this register has no effect and is ignored by the hardware. All interrupts keep pending until the interrupt-causing source is cleared (e.g. by reading from a RX FIFO that was signaling "data available").
-----------
> [!NOTE]
> This PR is part of a series that aims to _unify_ (and simplify) the entire interrupt system of the processor.
=> :bug: fix DMA fence flag, :warning: rework CPU FIRQs

docs/datasheet/software.adoc, sw/common/common.mk
This introduces the following new makefile variables: `CFLAGS` for C, `CXXFLAGS` for C++, `ASFLAGS` for Assembler and `LDFLAGS` for the linker. Names follow  conventions from  https://www.gnu.org/software/make/manual/html_node/Implicit-Variables.html
These variables can then be set either in the user application makefile (before including `common.mk`) or on the command line when calling make.
Fixes #856
=> Support tool-specific standard flags in makefile

CHANGELOG.md, docs/datasheet/soc.adoc, docs/datasheet/soc_twi.adoc, rtl/core/neorv32_package.vhd, rtl/core/neorv32_top.vhd, rtl/core/neorv32_twi.vhd, sim/neorv32_tb.vhd, sim/simple/neorv32_tb.simple.vhd, sw/example/demo_twi/main.c, sw/example/processor_check/main.c, sw/lib/include/neorv32_twi.h, sw/lib/source/neorv32_twi.c, sw/svd/neorv32.svd
An optional FIFO is implemented that can be used to "program" long sequences of TWI operations (START conditions, repeated START conditions, STOP conditions, data transmissions) without further interaction of the CPU. The FIFO is configured by a new top generic:
```vhdl
IO_TWI_FIFO : natural range 1 to 2**15 := 1;
```
* remove support for clock-stretching
* remove bus state sensing
* rework low-level interface / HAL
* interrupt will fire when the FIFO is empty and no bus operation is pending
=> :warning: rework TWI module

CHANGELOG.md, docs/datasheet/soc_twi.adoc, rtl/core/neorv32_package.vhd, rtl/core/neorv32_twi.vhd, sw/example/demo_twi/main.c, sw/example/processor_check/main.c, sw/lib/include/neorv32_twi.h, sw/lib/source/neorv32_twi.c, sw/svd/neorv32.svd
requested by @NikLeberg in https://github.com/stnolting/neorv32/pull/865#issuecomment-2029060807
=> add back TWI clock stretching option

CHANGELOG.md, docs/datasheet/soc.adoc, docs/datasheet/soc_slink.adoc, rtl/core/neorv32_package.vhd, rtl/core/neorv32_slink.vhd, rtl/core/neorv32_top.vhd, sim/neorv32_tb.vhd, sim/simple/neorv32_tb.simple.vhd, sw/example/demo_slink/main.c, sw/example/processor_check/main.c, sw/lib/include/neorv32.h, sw/lib/include/neorv32_slink.h, sw/lib/source/neorv32_slink.c, sw/svd/neorv32.svd
Split the SLINK interrupt into two individual interrupts:
* FIRQ14: SLINK RX interrupt (was global SLINK interrupt)
* FIRQ15: SLINK TX interrupt (was unused)
=> [SLINK] split interrupt into two FIRQs

CHANGELOG.md, docs/datasheet/cpu.adoc, docs/userguide/simulating_the_processor.adoc, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_cpu_cp_bitmanip.vhd, rtl/core/neorv32_package.vhd, sw/example/processor_check/run_check.sh
Finally, the RISC-V `B` ISA extension (bit manipulation) has been frozen and is about to be ratified.
Now, `B` only contains the `Zba`, `Zbb` and `Zbs` sub-extensions but **not** the `Zbc` sub-extension (carry-less multiplication). Find more information at https://jira.riscv.org/browse/RVS-2006?src=confmacro.
⚠️ Hence, this PR removes `Zbc` support from the CPU (for now).
=> B ISA extensions only contains Zba + Zbb + Zbs

CHANGELOG.md, docs/datasheet/soc_sdi.adoc, docs/datasheet/soc_spi.adoc, rtl/core/neorv32_package.vhd, rtl/core/neorv32_sdi.vhd, rtl/core/neorv32_spi.vhd, sw/example/processor_check/main.c, sw/lib/include/neorv32_sdi.h, sw/lib/include/neorv32_spi.h, sw/lib/source/neorv32_sdi.c, sw/lib/source/neorv32_spi.c, sw/svd/neorv32.svd
* add "SPI idle" interrupt condition (fire interrupt if TX FIFO is empty and SPI bus engine is idle)
* add "TX FIFO not at least half full" interrupt condition
* add "TX FIFO not at least half full" status flag
> [!NOTE]
> This PR is part of a series that aims to _unify_ (and simplify) the entire interrupt system of the processor.
=> add additional SPI and SDI interrupt conditions

CHANGELOG.md, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_cpu_cp_shifter.vhd, rtl/core/neorv32_package.vhd, rtl/core/neorv32_xirq.vhd
* simplify CPU shifter code
* simplify control's CSR write logic
* use a structural priority encoder for the XIRQ
* start using new (simplified) VHDL file headers 💄
=> minor rtl clean-ups and optimization

CHANGELOG.md, docs/datasheet/soc_slink.adoc, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_cpu_cp_cfu.vhd, rtl/core/neorv32_package.vhd, rtl/core/neorv32_slink.vhd, rtl/system_integration/neorv32_litex_core_complex.vhd, sw/lib/include/neorv32_slink.h, sw/lib/source/neorv32_slink.c, sw/svd/neorv32.svd
* :warning: rename SLINK data interface registers: only two registers are used now: `DATA` and `DATA_LAST`; reading any of these registers will return data from the RX FIFO; writing to any of these registers will write to the TX FIFO; writing `DATA_LAST` will also set the "last" identifier
* minor CPU control unit optimizations (area)
* update LiteX wrapper file header
* cleanup some CFU comments and code (for better understanding)
=> :warning: rename SLINK data interface registers

CHANGELOG.md, rtl/core/neorv32_cfs.vhd, rtl/core/neorv32_cpu_cp_bitmanip.vhd, rtl/core/neorv32_cpu_cp_shifter.vhd, rtl/core/neorv32_cpu_regfile.vhd, rtl/core/neorv32_dma.vhd, rtl/core/neorv32_package.vhd, rtl/core/neorv32_xip.vhd
* cleanup VHDL package functions
* cleanup CPU barrel shifter
* cleanup register file
* cleanup and optimize `B` extension (significantly less area)
=> rtl logic optimization and cleanups

CHANGELOG.md, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_package.vhd, sw/example/processor_check/main.c
Fixing #879.
The CPU can now be halted right after reset **before** the first instruction is executed. However, the on-chip debugger does not provide the "halt on reset" functionality yet (but that can be emulated by the debugger).
=> fix external debug-halt vs. exception concurrency

CHANGELOG.md, rtl/core/neorv32_cpu_cp_cond.vhd, rtl/core/neorv32_cpu_cp_fpu.vhd, rtl/core/neorv32_cpu_pmp.vhd, rtl/core/neorv32_package.vhd, rtl/core/neorv32_uart.vhd
* removed non-ASCII characters from FPU comments (`neorv32_cpu_cp_fpu.vhd`)
* fixed minor VHDL/GHDL issue (only relevant for older GHDL versions) in PMP mode select (case operand: "object type is not locally static")
* fixed imprecise timing of first-transmitted UART TX bit (was not correctly synchronized with the UART baud clock)
=> minor rtl fixes

CHANGELOG.md, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_package.vhd
Allow the debugger's single-stepping to intercept exception entry (halt right after trap entry).
Fixing #885
=> [rtl] fix single-step halting

CHANGELOG.md, rtl/core/neorv32_cpu.vhd, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_cpu_cp_bitmanip.vhd, rtl/core/neorv32_cpu_cp_fpu.vhd, rtl/core/neorv32_cpu_cp_muldiv.vhd, rtl/core/neorv32_cpu_lsu.vhd, rtl/core/neorv32_cpu_pmp.vhd, rtl/core/neorv32_dma.vhd, rtl/core/neorv32_package.vhd, sw/common/common.mk, sw/example/coremark/core_portme.c
Clean-up boolean expressions for better code readability:
* `(XYZ = true)` -> `xyz`
* `(xyz = false)` -> `(not xyz)`
=> minor rtl cleanups

CHANGELOG.md, rtl/core/neorv32_package.vhd, rtl/core/neorv32_uart.vhd
According to #890
[bug] uart issue after #883 upd
The change is in neorv32_uart.vhd file
On line 289:
From rx_engine.sreg(8 downto 1) to rx_engine.sreg(7 downto 0)
=> Fix UART receiver

rtl/core/neorv32_sdi.vhd
RX FIFO misses the value setting for FULL_RESET generic completly. I suppose then it falls back to the default value, since that one is false too in the neorv32_fifo.vhd this commit isn't leading to any different behavior in RTL, but should be added just for consisentcy issues
=> Update neorv32_sdi.vhd - Minor typo correction

.gitignore, docs/datasheet/software.adoc, sw/common/common.mk, sw/image_gen/image_gen.c
The image generator and the main application makefile now support two more output file formats:
* `make coe`: generate *.coe file (for FPGA memory initialization; Vivado standard)
* `make mem`: generate *.mem file (also for FPGA memory initialization older Vivado standard))
=> Add COE and MEM file generator options

CHANGELOG.md, docs/datasheet/soc.adoc, docs/datasheet/soc_slink.adoc, rtl/core/neorv32_package.vhd, rtl/core/neorv32_slink.vhd, rtl/core/neorv32_top.vhd, rtl/system_integration/neorv32_vivado_ip.vhd, sim/neorv32_tb.vhd, sim/simple/neorv32_tb.simple.vhd, sw/example/processor_check/main.c, sw/lib/include/neorv32_slink.h, sw/lib/source/neorv32_slink.c, sw/svd/neorv32.svd
This PR adds two new 4-bit ports to the SLINK module allowing the single RX/TX ports to access up to 16 stream link sources/sinks (via a switch or interconnect).
New top entity ports:
* `slink_rx_src_i`, input, 4-bit, compatible to AXI-stream's `TID` signal
* `slink_tx_dst_o`, output, 4-bit, compatible to AXI-stream's `TDEST` signal
The routing information is also fully buffered by the SLINK's internal RX/TX FIFOs.
=> Add SLINK routing information ports

CHANGELOG.md, docs/datasheet/soc.adoc, docs/datasheet/soc_xirq.adoc, rtl/core/neorv32_package.vhd, rtl/core/neorv32_top.vhd, rtl/core/neorv32_xirq.vhd, rtl/system_integration/neorv32_vivado_ip.tcl, rtl/system_integration/neorv32_vivado_ip.vhd, sim/neorv32_tb.vhd, sim/simple/neorv32_tb.simple.vhd, sw/example/demo_xirq/main.c, sw/example/processor_check/main.c, sw/lib/include/neorv32_xirq.h, sw/lib/source/neorv32_xirq.c, sw/svd/neorv32.svd
This PR removes the `XIRQ_TRIGGER_TYPE` and `XIRQ_TRIGGER_POLARITY` generics which were used to configure the _type_ (level or edge) and the _polarity_ (low/high or rising/falling) of each XIRQ channel.
They are replaced by two new XIRQ registers (`TTYP` and `TPOL`) to allow **online configuration** (i.e. during runtime) of the trigger type for each XIRQ channel.
=> Make XIRQ trigger configuration *programmable*

CHANGELOG.md, docs/datasheet/soc_dcache.adoc, docs/datasheet/soc_icache.adoc, docs/datasheet/soc_xbus.adoc, rtl/core/neorv32_cache.vhd, rtl/core/neorv32_intercon.vhd, rtl/core/neorv32_package.vhd, rtl/core/neorv32_top.vhd, sw/example/processor_check/main.c, sw/lib/include/neorv32_cpu.h
With this PR the caches ensure that uncached accesses always have **lower** priority than cache block operation. Thus, cache block operations will never be interrupted allowing continuous burst transfers. Furthermore, uncached/direct memory accesses will be stalled until all cache operations are completed to ensure memory coherency.
=> Fix uncached/cached access priority

CHANGELOG.md, docs/datasheet/soc.adoc, docs/datasheet/soc_xbus.adoc, rtl/core/neorv32_package.vhd, rtl/core/neorv32_top.vhd, rtl/core/neorv32_xbus.vhd, rtl/system_integration/neorv32_vivado_ip.vhd, sim/neorv32_tb.vhd, sim/simple/neorv32_tb.simple.vhd
New top signal:
```vhdl
xbus_tag_o : out std_ulogic_vector(2 downto 0); -- access tag
```
* `xbus_tag_o(0)` **P**: access is performed from **privileged** mode (machine-mode) when set
* `xbus_tag_o(1)` **NS**: this bit is hardwired to `0` indicating a **secure** access
* `xbus_tag_o(2)` **I**: access is an **instruction** fetch when set; access is a data access when cleared
> [!NOTE]
> This signal is compatible to AXI4's `ARPROT` and `AWPROT` signals.
=> [xbus] access type identifier (tag signal)

sw/example/performance_tests/I/main.c, sw/example/performance_tests/M/main.c, sw/example/performance_tests/Zfinx/main.c, sw/example/processor_check/main.c, sw/lib/include/neorv32_gpio.h, sw/lib/source/neorv32_gpio.c
The two functions
```c
void neorv32_gpio_pin_set(int pin);
void neorv32_gpio_pin_clr(int pin);
```
are _unified_ into a single function that is used to CLEAR (value = 0) or SET (value != 0) a specific GPIO output pin:
```c
void neorv32_gpio_pin_set(int pin, int value);
```
=> [sw/lib] :warning: rework gpio_pin_set function

CHANGELOG.md, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_cpu_cp_bitmanip.vhd, rtl/core/neorv32_cpu_cp_fpu.vhd, rtl/core/neorv32_cpu_cp_muldiv.vhd, rtl/core/neorv32_cpu_decompressor.vhd, rtl/core/neorv32_cpu_lsu.vhd, rtl/core/neorv32_cpu_pmp.vhd, rtl/core/neorv32_cpu_regfile.vhd, rtl/core/neorv32_package.vhd, rtl/core/neorv32_top.vhd
* minor VHDL code base clean-ups
* fix missing default values in TOP
=> minor rtl code clean-ups

CHANGELOG.md, docs/datasheet/soc_dma.adoc, docs/datasheet/soc_uart.adoc, rtl/core/neorv32_dma.vhd, rtl/core/neorv32_package.vhd, rtl/core/neorv32_uart.vhd, sw/example/demo_dma/main.c, sw/example/processor_check/main.c, sw/lib/include/neorv32_dma.h, sw/lib/include/neorv32_uart.h, sw/lib/source/neorv32_dma.c, sw/lib/source/neorv32_uart.c, sw/svd/neorv32.svd
Add two new control register bits to manually clear the RX / TX FIFOs:
* bit 28: `UART_CTRL_RX_CLR`, flag auto-clears
* bit 29:`UART_CTRL_TX_CLR`, flag auto-clears
Add new FIRQ interrupt type configuration flag:
* bit 15: `DMA_CTRL_FIRQ_TYPE`
* when `0`: trigger DMA operation on rising-edge of selected FIRQ channel (e.g. trigger only once)
* when `1`: trigger DMA operation whenever the selected FIRQ channel is active/high (e.g. trigger again and again)
=> Add UART FIFO clear flags; add DMA FIRQ interrupt configuration

CHANGELOG.md, rtl/core/mem/README.md, rtl/core/mem/neorv32_imem.default.vhd, rtl/core/mem/neorv32_imem.legacy.vhd, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_fifo.vhd, rtl/core/neorv32_package.vhd
* clean-up rtl code (CPU control)
* remove redundant output register from FIFO (when using the SYNC read configuration with just a single FIFO entry)
=> Minor rtl edits/cleanups

CHANGELOG.md, docs/datasheet/cpu_csr.adoc, rtl/core/neorv32_cpu_alu.vhd, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_cpu_cp_cfu.vhd, rtl/core/neorv32_cpu_decompressor.vhd, rtl/core/neorv32_package.vhd, sim/neorv32_tb.vhd, sw/example/processor_check/main.c
* remove "proxy/controller" logic from CFU module (reducing size); put a minimal proxy logic to the ALU
* allow implementers to skip registered CFU output to reduce latency (faster execution)
Output illegal instruction word "as-is" in their pre-decoded 32-bit format.
=> :warning: rework CFU interface

sw/example/bus_explorer/main.c, sw/example/demo_cfu/main.c, sw/example/demo_mtime/main.c, sw/example/demo_onewire/main.c, sw/example/demo_sdi/main.c, sw/example/demo_spi/main.c, sw/example/demo_twi/main.c, sw/example/demo_xirq/main.c, sw/lib/include/neorv32_mtime.h, sw/lib/source/neorv32_mtime.c, sw/lib/source/neorv32_xirq.c, sw/lib/source/syscalls.c
* newlib system calls: fix minor type issue
* improve `hexstr_to_uint` function (and rename to `hexstr_to_uint32`)
* improve [bus_explorer](https://github.com/stnolting/neorv32/tree/main/sw/example/bus_explorer) user console
* add Unix timestamping functions to MTIME library; MTIME machine timer can now easily be used as real-time clock
* fix XIRQ's `neorv32_xirq_install` function: XIRQ channels have to be enabled by hand (using `neorv32_xirq_channel_enable()`)
* minor cleanups and edits
=> minor software updates and fixes

CHANGELOG.md, rtl/core/neorv32_cfs.vhd, rtl/core/neorv32_cpu.vhd, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_cpu_lsu.vhd, rtl/core/neorv32_crc.vhd, rtl/core/neorv32_debug_dm.vhd, rtl/core/neorv32_dma.vhd, rtl/core/neorv32_gpio.vhd, rtl/core/neorv32_gptmr.vhd, rtl/core/neorv32_intercon.vhd, rtl/core/neorv32_mtime.vhd, rtl/core/neorv32_neoled.vhd, rtl/core/neorv32_onewire.vhd, rtl/core/neorv32_package.vhd, rtl/core/neorv32_pwm.vhd, rtl/core/neorv32_sdi.vhd, rtl/core/neorv32_slink.vhd, rtl/core/neorv32_spi.vhd, rtl/core/neorv32_sysinfo.vhd, rtl/core/neorv32_top.vhd, rtl/core/neorv32_trng.vhd, rtl/core/neorv32_twi.vhd, rtl/core/neorv32_uart.vhd, rtl/core/neorv32_wdt.vhd, rtl/core/neorv32_xip.vhd, rtl/core/neorv32_xirq.vhd, rtl/system_integration/neorv32_vivado_ip.vhd
* IO devices: use termination record for response bus reset
* rtl tops: constrain all relevant (`natural`) generics
* minor code edits and cleanups
=> minor rtl edits and cleanups

CHANGELOG.md, docs/datasheet/overview.adoc, docs/datasheet/soc_xbus.adoc, docs/legal.adoc, rtl/core/neorv32_package.vhd, rtl/system_integration/README.md, rtl/system_integration/xbus2ahblite_bridge.vhd, sim/neorv32_tb.vhd, sim/simple/neorv32_tb.simple.vhd
The bridge is located in `rtl/system_integration`:
* `xbus2ahblite_bridge.vhd`
> [!NOTE]
> This bridge is still experimental.
=> 🧪 Add experimental XBUS (Wishbone) to AHB3-Lite bridge

docs/datasheet/cpu.adoc, docs/datasheet/soc_gpio.adoc, sw/bootloader/bootloader.c, sw/common/crt0.S, sw/example/atomic_test/main.c, sw/example/demo_newlib/main.c, sw/example/processor_check/main.c, sw/lib/include/neorv32_aux.h, sw/lib/include/neorv32_cpu.h, sw/lib/include/neorv32_cpu_amo.h, sw/lib/include/neorv32_gpio.h, sw/lib/include/neorv32_legacy.h, sw/lib/source/neorv32_cpu.c, sw/lib/source/neorv32_cpu_amo.c, sw/lib/source/neorv32_gpio.c, sw/lib/source/neorv32_mtime.c, sw/lib/source/neorv32_rte.c, sw/svd/neorv32.svd
* use crt0's trap handler for exceptions during destructor execution
* GPIO: rename interface registers
* `INPUT_LO -> INPUT[0]`
* `INPUT_HI -> INPUT[1]`
* `OUTPUT_LO -> OUTPUT[0]`
* `OUTPUT_HI -> OUTPUT[1]`
* backwards compatibility aliases are added to `neorv32_legacy.h`
* provide global data types (unions) for subword accesses
* rename atomic LR/SC wrappers:
* `neorv32_cpu_load_reservate_word() -> neorv32_cpu_amolr()`
* `neorv32_cpu_store_conditional_word() -> neorv32_cpu_amosc()`
* backwards compatibility aliases are added to `neorv32_legacy.h`
=> minor software framework cleanups and optimizations

CHANGELOG.md, rtl/core/neorv32_cache.vhd, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_cpu_lsu.vhd, rtl/core/neorv32_cpu_pmp.vhd, rtl/core/neorv32_dma.vhd, rtl/core/neorv32_mtime.vhd, rtl/core/neorv32_package.vhd, rtl/core/neorv32_top.vhd, sw/lib/include/neorv32.h, sw/lib/include/neorv32_aux.h
* optimize MTIME logic (less area requirements)
* add VHDL `replicate_f` function to make sign-extensions etc. more readable
* minor coding cleanups
=> minor rtl cleanups and optimizations

CHANGELOG.md, docs/datasheet/soc.adoc, rtl/core/neorv32_package.vhd, rtl/core/neorv32_top.vhd
This PR adds a new top generic (`IO_DISABLE_SYSINFO`, default `false`) that allows to disable the SYSINFO module. This option is intended for advanced users that wish to use a **"CPU-only"** processor setup with a custom software framework.
> [!WARNING]
> Deactivating the module means that large parts of the default NEORV32 software framework will no longer work (bootloader, HAL/drivers, etc.)!
=> Add option to disable SYSINFO module

CHANGELOG.md, rtl/core/neorv32_package.vhd, rtl/core/neorv32_sdi.vhd, sw/example/processor_check/main.c, sw/lib/include/neorv32_sdi.h, sw/lib/source/neorv32_sdi.c
The SDI `SDI_CTRL_TX_FULL` flag was broken (not indicating when the TX FIFO is actually full).
=> 🐛 Fix SDI "TX FIFO full" flag

CHANGELOG.md, docs/datasheet/soc_sdi.adoc, rtl/core/neorv32_package.vhd, rtl/core/neorv32_sdi.vhd, sim/neorv32_tb.vhd, sim/simple/neorv32_tb.simple.vhd, sw/example/demo_sdi/main.c, sw/example/processor_check/main.c, sw/lib/include/neorv32_sdi.h, sw/lib/source/neorv32_sdi.c, sw/svd/neorv32.svd
* :warning: remove control register flag to clear the RX FIFO; can be done by toggling the modules enable bit
* :sparkles: add new control register flag to check the current state of the SDI's chip-select input
=> Minor SDI edits

CHANGELOG.md, rtl/core/neorv32_package.vhd, sw/common/neorv32.ld, sw/example/demo_newlib/main.c, sw/example/demo_newlib/makefile, sw/lib/source/syscalls.c
A bug in the implementation of newlib's `sbrk` function caused `malloc` to always make memory available, even though the heap was already full. This caused a collision of heap and stack and finally a CPU crash.
* :bug: fixed bug in newlib's `sbrk` function; `malloc` works now as expected
* :sparkles: add support for `time()` function
=> 🐛 [newlib] fix broken `sbrk` function

CHANGELOG.md, docs/datasheet/soc_sysinfo.adoc, rtl/core/neorv32_package.vhd, rtl/core/neorv32_sysinfo.vhd, sw/example/coremark/core_portme.c, sw/example/demo_gptmr/main.c, sw/example/demo_mtime/main.c, sw/example/demo_spi/main.c, sw/example/demo_trng/main.c, sw/example/demo_twi/main.c, sw/example/demo_wdt/main.c, sw/example/dhrystone/dhry_1.c, sw/lib/include/neorv32_sysinfo.h, sw/lib/source/neorv32_cpu.c, sw/lib/source/neorv32_mtime.c, sw/lib/source/neorv32_neoled.c, sw/lib/source/neorv32_onewire.c, sw/lib/source/neorv32_rte.c, sw/lib/source/neorv32_spi.c, sw/lib/source/neorv32_sysinfo.c, sw/lib/source/neorv32_uart.c, sw/lib/source/neorv32_xip.c, sw/svd/neorv32.svd
Implementing #951 (option 3).
`NEORV32_SYSINFO.CLK` is now a real register that can be overridden by application software (e.g. to take into account any _dynamic_ frequency scaling of the processor clock). Upon reset, `CLK` is initialized from the `CLOCK_FREQUENCY` generic.
=> Make SYSINFO CLK writable

CHANGELOG.md, docs/userguide/packaging_vivado.adoc, rtl/core/neorv32_package.vhd, rtl/system_integration/neorv32_vivado_ip.tcl, rtl/system_integration/neorv32_vivado_ip.vhd
Fixing #974.
Use VHDL2008 for compiling the IP's top module to allow assigning `std_logic_vector` and `std_ulogic_vector` without casting.
=> [vivado_ip] fix error when AXI port is unconnected

CHANGELOG.md, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_cpu_cp_cond.vhd, rtl/core/neorv32_cpu_cp_muldiv.vhd, rtl/core/neorv32_cpu_cp_shifter.vhd, rtl/core/neorv32_cpu_pmp.vhd, rtl/core/neorv32_cpu_regfile.vhd, rtl/core/neorv32_package.vhd, rtl/core/neorv32_top.vhd, rtl/core/neorv32_trng.vhd
* upgrade TRNG to [neoTRNG v3.1](https://github.com/stnolting/neoTRNG)
* improve timing of CPU's critical path (regfile -> ALU(add) -> regfile)
* improve timing and area utilization of CPU's barrel shifter
* improve area utilization of MUL/DIV unit
* add missing reset to ASIC-style register-file read access
* minor code cleanups
=> [rtl] minor timing and area optimizations

CHANGELOG.md, docs/datasheet/cpu.adoc, docs/datasheet/cpu_csr.adoc, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_cpu_cp_muldiv.vhd, rtl/core/neorv32_crc.vhd, rtl/core/neorv32_imem.vhd, rtl/core/neorv32_package.vhd, rtl/system_integration/neorv32_vivado_ip.tcl, rtl/system_integration/neorv32_vivado_ip.vhd, sw/example/processor_check/main.c, sw/lib/include/neorv32_cpu_csr.h
* Vivado IP module: major rework; use explicit `std_logic[_vector] <-> std_ulogic[_vector]` conversion; remove VHDL2008 requirement (not supported by the IP packager?)
* CPU: remove output register of multiplier unit to improve mapping to DSP block (`FAST_MUL_EN` option only)
* CPU: :warning: remove user-level HPMs
* CPU: rework `mcountern` CSR; add explicit `CY` and `IR` bits
* CPU: rework "next PC" logic - use ALU adder to compute the next instruction address (removes one carry chain and shortens the critical path of the base CPU core)
* DOCs: updates, cleanups and fixes
=> RTL reworks, cleanups and optimizations

CHANGELOG.md, docs/datasheet/soc.adoc, rtl/core/neorv32_cpu_alu.vhd, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_cpu_cp_fpu.vhd, rtl/core/neorv32_intercon.vhd, rtl/core/neorv32_package.vhd, rtl/core/neorv32_top.vhd
* :bug: CPU: fix PC reset bug (introduced in v1.10.2.8)
* CPU: clean-up illegal instruction decoding logic (FPU and atomic instructions)
* CPU: simplify `fence[.i]` decoding
* SoC: add register stage to IO switch to relax the critical path of the interconnect; IO accesses now require an additional clock cycle to complete
* SoC: rework reset system; all registers of the entire processor now trigger exclusively on the rising clock edge (no more `falling_edge()`)
* minor edits and clean-ups
=> :bug: fix minor regression bug; minor RTL optimizations

CHANGELOG.md, rtl/core/neorv32_package.vhd
As discussed in #1002 the maximum number of `loop` iterations (for unrolling by the synthesizer) might be constrained (e.g. by AMD Vivado). This PR removes the `for .. loop` construct.
=> 🧪 Remove "loop" from memory initialization function

docs/datasheet/on_chip_debugger.adoc, sw/ocd-firmware/debug_rom.ld
This proposes some minor fixes (no impact expected) of the OCD.
- fix address map in  linker script (not really important, but just for completeness)
- fix renaming of `dm_base_c` to `base_io_dm_c`
As I don't think the changes will have any impact, I left out the `CHANGELOG.md` update. Let me know if you'd like to have one nonetheless.
=> minor fixes in OCD

CHANGELOG.md, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_fifo.vhd, rtl/core/neorv32_package.vhd
* add a dedicated register stage for the CSR address that gets updated only if there is an actual CSR access operation (reduces switching activity)
* code cleanup
* revert package function cleanup (Quartus issues warnings if variables are initialized only at declaration)
=> optimize CSR address logic

CHANGELOG.md, docs/datasheet/cpu_csr.adoc, docs/datasheet/on_chip_debugger.adoc, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_intercon.vhd, rtl/core/neorv32_package.vhd, rtl/core/neorv32_top.vhd
* reset `mtvec`, `mepc` and `dpc` CSRs to all-zero
* reset `dcsr.priv` CSR bit to zero
* replace all `'-'` (don't care) by `'0'` (Yosys seems to have problems with this sometimes)
* simplify `mtvec` logic for _vectored_ interrupt mode
=> Minor rtl/CSR optimizations

docs/datasheet/software.adoc, docs/userguide/eclipse_ide.adoc, sw/common/common.mk, sw/example/eclipse/.settings/org.eclipse.cdt.core.prefs, sw/example/eclipse/.settings/org.eclipse.embedcdt.debug.gdbjtag.openocd.core.prefs, sw/example/eclipse/.settings/org.eclipse.embedcdt.managedbuild.cross.riscv.core.prefs, sw/example/eclipse/makefile
By default, **no** debug symbols are added to the final ELF. You can add debug symbols manually (in your project's local makefile), e.g. `USER_FLAGS += -g`.
This PR also fixes a problem in the default Eclipse project: sometimes the sources (during debugging) cannot be found. This is fixed by adding an explicit indexer configuration and explicit debug symbols: `USER_FLAGS += -ggdb -gdwarf-3`
=> Cleanup debug symbols

CHANGELOG.md, rtl/core/neorv32_cache.vhd, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_package.vhd, rtl/core/neorv32_top.vhd, sw/example/processor_check/main.c, sw/lib/include/neorv32_intrinsics.h
* cleanups boolean expressions in cache module
* adjust top's "sanity check" outputs
* add illegal FPU instruction to processor check program (`fsqrt`)
* cleanup/simplify (custom) instruction macros
* cleanup CPU control logic and do some minor optimizations; improve some code comments
* remove CNT event register stage
=> minor HDL cleanups and otimizations

CHANGELOG.md, docs/datasheet/soc_wdt.adoc, rtl/core/neorv32_package.vhd, rtl/core/neorv32_top.vhd, rtl/core/neorv32_wdt.vhd, sw/example/demo_wdt/main.c, sw/lib/include/neorv32_wdt.h, sw/lib/source/neorv32_wdt.c
The watchdog is now able to distinguish 4 reset causes:
* `WDT_RCAUSE_EXT` (0b00): Reset caused by external reset signal/pin
* `WDT_RCAUSE_OCD` (0b01): Reset caused by on-chip debugger
* `WDT_RCAUSE_TMO` (0b10): Reset caused by watchdog timeout
* `WDT_RCAUSE_ACC` (0b11): Reset caused by illegal watchdog access (strict mode) - invalid reset password or a write attempt to the _locked_ configuration register
=> Cleanup and extend watch dog's reset-cause logic

CHANGELOG.md, rtl/core/neorv32_cpu_cp_fpu.vhd, rtl/core/neorv32_package.vhd
Fix invalid instruction logic (if any operand is sNAN).
Bug identified by @racodond in #1024.
@mikaelsky, maybe this is also interesting for you :wink:
=> :bug: fix minor bug in FPU MUL instruction

rtl/core/neorv32_debug_dm.vhd
Just found this signal that is completely redundant. I kinda remember us having found that and removing it a few months ago... did it creep back it? 🤔
Unrelated: I'm playing around with implementing system bus access for the DM. Is that something you would accept a PR for?
=> [rtl] remove redundant `prog_buf`

CHANGELOG.md, rtl/core/neorv32_cpu_alu.vhd, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_cpu_cp_bitmanip.vhd, rtl/core/neorv32_cpu_cp_cond.vhd, rtl/core/neorv32_cpu_cp_fpu.vhd, rtl/core/neorv32_cpu_cp_muldiv.vhd, rtl/core/neorv32_cpu_cp_shifter.vhd, rtl/core/neorv32_package.vhd, sw/example/processor_check/main.c
This is a massive rework of the CPU instruction decoding logic that replaces the centralized instruction decoding (inside the control unit) by a "split" decoding.
Only the basic rv32 register-register / register-immediate ALU instruction (`alu/alui` opcode space) are decoded inside the control unit. All further instructions (including shift operation) are forwarded to the CPU co-processors. If no co-processor generates a response within a bound amount of time the instruction is considered "illegal" (raising an exception). Therefore, each co-processor has to decode all relevant instructions locally.
This change aims to reduce hardware complexity and to make the code base easier to understand and maintain.
**🚧 work-in-progress 🚧**
=> [cpu] rework ALU instruction decoding and CPU co-processor interface

docs/datasheet/cpu.adoc
Small fix on **Table 77. NEORV32 Trap Description** of the datasheet. TRAP_CODE_S_ACCESS description mentioned errors during loads and vice versa for the TRAP_CODE_L_ACCESS.
Originally:
```
| `TRAP_CODE_S_ACCESS`     | bus timeout, bus access error or <<_smpmp_isa_extension,PMP>> rule violation during load data operation
| `TRAP_CODE_L_ACCESS`     | bus timeout, bus access error or <<_smpmp_isa_extension,PMP>> rule violation during store data operation
```
Fix:
```
| `TRAP_CODE_L_ACCESS`     | bus timeout, bus access error or <<_smpmp_isa_extension,PMP>> rule violation during load data operation
| `TRAP_CODE_S_ACCESS`     | bus timeout, bus access error or <<_smpmp_isa_extension,PMP>> rule violation during store data operation
```
=> Fix typo trap table

CHANGELOG.md, docs/datasheet/cpu.adoc, docs/datasheet/cpu_cfu.adoc, rtl/core/neorv32_cpu_alu.vhd, rtl/core/neorv32_cpu_cp_cfu.vhd, rtl/core/neorv32_package.vhd
⚠️ This PR is a rework of the _custom functions unit's_ (CFU) handshake protocol.
With the changes from this PR, the "processing done" / "result valid" signal `valid_o` has to be set (for one cycle) at the same time the processing result / output data `result_o` is valid.
Thus, the handshake is easier to understand and easier to implement.
✨ Furthermore, this PR provides a rework of the "CFU proxy logic" allowing an (all-combinatorial) CFU operation to commit much faster: the minimum CPU execution time of a single CFU operation is reduced from 4 clock cycles down to 3 clock cycles.
=> :warning: rework CFU handshake interface

CHANGELOG.md, rtl/core/neorv32_cpu_lsu.vhd, rtl/core/neorv32_package.vhd, rtl/core/neorv32_top.vhd, rtl/core/neorv32_trng.vhd
https://github.com/stnolting/neoTRNG/releases/tag/v3.2
=> Uprade neoTRNG to version 3.2

CHANGELOG.md, docs/datasheet/on_chip_debugger.adoc, docs/datasheet/soc.adoc, rtl/core/neorv32_debug_dm.vhd, rtl/core/neorv32_package.vhd, rtl/core/neorv32_sysinfo.vhd, rtl/core/neorv32_top.vhd, rtl/system_integration/neorv32_vivado_ip.tcl, rtl/system_integration/neorv32_vivado_ip.vhd
* debug module is compatible to spec. version 1.0 that has been ratified over a year ago and is widely supports (like upstream opcenOCD)
* remove `OCD_DM_LEGACY_MODE` generic
=> :warning: Remove OCD's DM legacy mode

rtl/system_integration/neorv32_vivado_ip.tcl
Currently empty ports for AXI-Stream interfaces (`s1_axis` and `s0_axis`) are still shown even if they're not enabled (shown in the picture). Setting `enablement_dependency` property for the bus interfaces instead can hide them entirely.
Tested in Vivado 2022.2
=> [vivado ip] hide entire AXI-Stream interface in block diagram if disabled

CHANGELOG.md, docs/datasheet/soc_xbus.adoc, rtl/core/neorv32_package.vhd, rtl/system_integration/neorv32_vivado_ip.tcl, rtl/system_integration/neorv32_vivado_ip.vhd, rtl/system_integration/xbus2axi4lite_bridge.vhd
This separate logics of XBUS to AXI4 converter inside the Vivado IP wrapper module into a new `xbus2axi4lite_bridge` module.
=> [rtl/system_integration] create individual module for AXI4 Lite bridge

rtl/system_integration/neorv32_vivado_ip.tcl
Parameters inside the IP GUI are split into pages and groups, and there editability are depending on other corresponding parameters (e.g. XBUS_CACHE_EN is editable only when XBUS_EN is set). Hopefully it looks more neat and is easier to use now :)
=> [vivado ip] reorganize Vivado IP GUI

rtl/system_integration/neorv32_vivado_ip.tcl, rtl/system_integration/neorv32_vivado_ip.vhd, rtl/system_integration/xbus2axi4lite_bridge.vhd
Hey thank you for merging my recent pulls! And here's the last split of #1060.
As mentioned in https://github.com/stnolting/neorv32/pull/1060#issuecomment-2420540728 did you encounter any error from the tool? It works fine for me on my computer with Vivado 2022.2.
=> [vivado ip] make m_axi (XBUS) interface optional

CHANGELOG.md, docs/datasheet/soc_xirq.adoc, rtl/core/neorv32_package.vhd, rtl/core/neorv32_xirq.vhd, sw/example/demo_xirq/main.c, sw/example/processor_check/main.c, sw/lib/include/neorv32_xirq.h, sw/lib/source/neorv32_xirq.c, sw/svd/neorv32.svd
Remove the XIRQ's "interrupt pending register" `EIP`.
:warning: The module's register addresses are changed.
:rocket: Software no longer needs to explicitly clear pending XIRQ interrupts; this is now handled entirely by the hardware leading to less interrupt overhead.
=> ⚠️ Rework XIRQ - remove "pending" register

.github/workflows/Processor.yml
I would like to reduce the amount of (external) dependencies. Hence, this PR removes the `sim` package.
=> [github workflow] remove packages

CHANGELOG.md, rtl/core/neorv32_package.vhd, sim/neorv32_tb.vhd, sim/sim_uart_rx.vhd, sim/xbus_gateway.vhd, sim/xbus_memory.vhd
Triggered by @mahdi259 in #1115 this PR adds new generics to the default testbench that control implementation (and initialization) of two processor-external memories.
```vhdl
-- external memory A --
EXT_MEM_A_EN   : boolean                        := true;        -- enable memory
EXT_MEM_A_BASE : std_ulogic_vector(31 downto 0) := x"00000000"; -- base address, has to be word-aligned
EXT_MEM_A_SIZE : natural                        := 64;          -- memory size in bytes, min 4
EXT_MEM_A_FILE : string                         := "";          -- memory initialization file (plain HEX), no initialization if empty
-- external memory B --
EXT_MEM_B_EN   : boolean                        := true;        -- enable memory
EXT_MEM_B_BASE : std_ulogic_vector(31 downto 0) := x"80000000"; -- base address, …
```
=> [sim] rework default testbench

CHANGELOG.md, docs/datasheet/cpu.adoc, docs/datasheet/cpu_csr.adoc, docs/datasheet/soc.adoc, docs/datasheet/soc_sysinfo.adoc, rtl/core/neorv32_cpu.vhd, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_package.vhd, rtl/core/neorv32_sysinfo.vhd, rtl/core/neorv32_top.vhd, rtl/file_list_cpu.f, rtl/system_integration/neorv32_vivado_ip.vhd, sim/neorv32_tb.vhd, sw/lib/include/neorv32_cpu_csr.h, sw/lib/include/neorv32_sysinfo.h, sw/lib/source/neorv32_rte.c, sw/svd/neorv32.svd
As the clock-gating feature is only used by the CPU core itself, the clock switch is moved from the processor top to the CPU top. `CLOCK_GATING_EN` is now a CPU _tuning option_.
* remove SYSINFO `SYSINFO_SOC_CLOCK_GATING` flag
* add `mxisa` CSRS `CSR_MXISA_CLKGATE` flag
=> Relocate clock gating switch

CHANGELOG.md, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_package.vhd
According to the RISC-V specs, `csrrw[i]` instructions _"shall not read the CSR and shall not cause any of the side effects that might occur on a CSR read"_ if `rd=0`. This PR fixes this.
For the NEORV32, this is not a bug as there are no CSRs that cause side effects when being read. However, this fix
* reduces switching activity during CSR reads when `rd=0`
* allows to to write to CSRs without causing side effects (might be relevant for future CSRs)
=> fix CSR read operations (side effects)

CHANGELOG.md, docs/datasheet/cpu.adoc, docs/datasheet/soc.adoc, docs/datasheet/soc_dcache.adoc, docs/datasheet/soc_icache.adoc, docs/datasheet/soc_xbus.adoc, docs/datasheet/soc_xip.adoc, rtl/core/neorv32_cache.vhd, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_package.vhd
Previously, the commands `fence` and `fence.i` were functionally equivalent. The execution of one of the two instructions leads to a complete cache re-synchronization (flushing/clearing/reloading the instruction **and** data cache). However, this is too inefficient, so this PR splits the two commands functionally.
* `fence.i` - clear and reload instruction cache
* `fence` - flush, clear and reload data cache
After the L1 caches, both instructions still behave identically.
=> [control] separate fence and fence.i instructions

CHANGELOG.md, docs/datasheet/cpu_dual_core.adoc, docs/datasheet/software_rte.adoc, rtl/core/neorv32_package.vhd, sw/example/demo_dual_core_rte/Makefile, sw/example/demo_dual_core_rte/main.c, sw/example/demo_dual_core_rte/spinlock.c, sw/example/demo_dual_core_rte/spinlock.h, sw/lib/include/neorv32_rte.h, sw/lib/source/neorv32_rte.c
With this PR, the NEORV32 runtime environment ("RTE"; responsible for providing a unified API for trap handling) implements a gloabl trap handler table that applies to both cores.
Hence, both cores will execute the _same_ trap handler if the same trap is triggered. The installed user-defined trap handlers can determine the core's ID (`mhartid` CSR) to perform core-specific trap handling.
=> ⚠️ [rte] use a single, global trap handler table

CHANGELOG.md, docs/datasheet/cpu_csr.adoc, rtl/core/neorv32_bus.vhd, rtl/core/neorv32_cache.vhd, rtl/core/neorv32_cpu.vhd, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_cpu_lsu.vhd, rtl/core/neorv32_package.vhd, rtl/core/neorv32_top.vhd, sw/bootloader/bootloader.c, sw/example/processor_check/main.c, sw/lib/include/neorv32_aux.h, sw/lib/source/neorv32_aux.c
* :bug: fix minor bug: multiple drivers on ICC net (introduced in version 1.10.9.2)
=> Minor rtl edits and cleanup; :bug: fix multiple drivers bug

CHANGELOG.md, docs/datasheet/soc_twd.adoc, rtl/core/neorv32_package.vhd, rtl/core/neorv32_twd.vhd, sw/example/processor_check/main.c
This PR fixes several design flaws:
* :bug: drive SDA line only if **READ** operation
* :bug: wait for STOP condition if a READ transfer has received a NACK
* only write received I2C data to the internal RX FIFO if an actual **WRITE** operation in in progress
* check for STOP condition also in ACK/NACK timeslot (if possible)
triggered in #1157 and replacing #1158
=> 🐛 [twd] fix some design flaws

CHANGELOG.md, docs/datasheet/soc_xbus.adoc, rtl/core/neorv32_bus.vhd, rtl/core/neorv32_cache.vhd, rtl/core/neorv32_package.vhd, rtl/core/neorv32_xbus.vhd, rtl/system_integration/neorv32_vivado_ip.tcl, rtl/system_integration/xbus2axi4lite_bridge.vhd
* allow atomic memory accesses (read-modify-write) to fail already during the first bus operation (read/load)
* external bus interface (XBUS / Wishbone): keep `cyc` signal active during read-modify-write operations to make bus accesses un-interruptable
* AXI4-Lite bridge: allow back-to-back atomic access operations
=> atomic memory access updates and improvements

CHANGELOG.md, rtl/core/neorv32_package.vhd, rtl/core/neorv32_twd.vhd
Since the SDA has to have a valid value only during high SCL, I had the case where with the fall of SCL the SDA also changed and thus a wrong state transition happened. But the protocol should guarantee a valid input during high SCL, so this should be a valid fix?
The image shows such a transition, which would fail with the old implementation.
=> [rtl] use past SDA in twd FSM transition

CHANGELOG.md, rtl/core/neorv32_package.vhd, rtl/core/neorv32_twd.vhd, rtl/core/neorv32_twi.vhd
Should improve compatibly with other TWI devices on the same bus as the reset doesn't pull-down SCL and SDA anymore.
=> [rtl] reset SDA and SCL of TWI and TWD to '1'

CHANGELOG.md, rtl/core/neorv32_package.vhd, sw/common/crt0.S, sw/example/processor_check/main.c
Fixes #1169.
⚠️ The default C constructors do not preserve any registers on the stack.
=> 🐛 Fix crt0's main entry address being overridden by constructors

CHANGELOG.md, rtl/core/neorv32_package.vhd, rtl/core/neorv32_top.vhd
The clk_gen_en2 vector in neorv32_top.vhd had clk_gen_en(CG_WDT) assigned twice, and clk_gen_en(CG_CFS) was missing.
=> [cfs] Add missing CFS clock gen enable signal.

CHANGELOG.md, docs/datasheet/soc.adoc, docs/datasheet/soc_uart.adoc, rtl/core/neorv32_package.vhd, rtl/core/neorv32_top.vhd, rtl/core/neorv32_uart.vhd, rtl/system_integration/neorv32_vivado_ip.tcl, rtl/system_integration/neorv32_vivado_ip.vhd, sim/neorv32_tb.vhd
The hardware flow control signals of the UARTs are low active. This PR adds a `n` to these signal names to underline this:
* `uart*_rts_o` -> `uart*_rtsn_o`
* `uart*_cts_i` -> `uart*_ctsn_i`
=> :warning: rename UART RTS/CTS signals

CHANGELOG.md, docs/datasheet/overview.adoc, rtl/core/neorv32_cpu.vhd, rtl/core/neorv32_cpu_alu.vhd, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_cpu_frontend.vhd, rtl/core/neorv32_cpu_pmp.vhd, rtl/core/neorv32_package.vhd, rtl/file_list_cpu.f, rtl/file_list_soc.f, sw/example/processor_check/main.c
Add new module: `neorv32_cpu_frontend.vhd`:
* Fetch engine - fetches aligned 32-bit chunks of instruction words
* Prefetch buffer - buffers pre-fetched 32-bit instruction data
* Issue engine - decodes RVC instructions, aligns & issues instruction words
=> Source-out CPU front-end

sw/bootloader/makefile
Fix Bootloader Makefile, USER_FLAG for setting the UART Baudrate was wrong
=> Fix Bootloader Makefile UART_BAUD

CHANGELOG.md, docs/datasheet/soc.adoc, rtl/core/neorv32_bus.vhd, rtl/core/neorv32_package.vhd, rtl/core/neorv32_top.vhd
Some _normal_ memory operations were treated as `LR.W` / `SC.W` instructions. This PR fixes the incomplete bus type decoding.
As a minor edit, this PR also disables all optional CPU extensions by default (primarily `Zicntr`).
=> 🐛 fix bug in Zalrsc ISA extension

CHANGELOG.md, docs/datasheet/overview.adoc, rtl/core/neorv32_clint.vhd, rtl/core/neorv32_clockgate.vhd, rtl/core/neorv32_cpu.vhd, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_cpu_counters.vhd, rtl/core/neorv32_debug_auth.vhd, rtl/core/neorv32_package.vhd, rtl/file_list_cpu.f, rtl/file_list_soc.f, sw/lib/source/neorv32_cpu.c
This PR further streamlines the CPU control unit by moving the entire CPU counter logic to a new rtl file: `neorv32_cpuc_counters.vhd`. So far, this new file is responsible for implementing the primary logic of the following RISC-V ISA extensions:
* `Zicntr` - base counters (`[m]cylce[h]` and `[m]instret[h]` CSRs)
* `Zihpm` - hardware performance monitors (`[m]hpmcnt*[h]` and `mhpmevent*` CSRs)
=> [cpu] relocate CPU counters

rtl/processor_templates/neorv32_ProcessorTop_Minimal.vhd, rtl/processor_templates/neorv32_ProcessorTop_MinimalBoot.vhd
Re-enable the Zicntr ISA extension on the neorv32_ProcessorTop_Minimal and neorv32_ProcessorTop_MinimalBoot templates to restore RISC-V compliance.
This allows for an easier path for evaluating 3rd party software depending on Zicntr (e.g. the Zephyr RTOS).
=> rtl: processor_templates: enable Zicntr ISA extension on minimal templates

sw/common/common.mk
`@readlink -f ${SHELL}` means `@readlink -f C:\Program Files\Git\usr\bin\sh.exe` on windows, so we need to escape the path to account for the space
=> Fix: quote readlink to fix windows make check

sw/common/neorv32.ld
The heap section **sets** the location counter to `__neorv32_heap_size` instead of incrementing it. 
I discovered this one when `rust-lld` failed with an error while creating a runtime support crate for neorv32 in Rust.
=> fix: increment location counter with heap size

rtl/core/neorv32_package.vhd, rtl/core/neorv32_top.vhd, rtl/system_integration/neorv32_litex_core_complex.vhd
As discussed in #1199 one way to make a SoC with more than two cores would be to make more of a NUMA architecture with several instances of the top level CPU.
I had that more or less working on 1.9.7 that LiteX was using, but noticed that's actually quite outdated.
Applying the same changes to the latest version is somehow not as functional.
I'll put up the LiteX changes in a second, maybe someone more familiar with these two projects can have a look.
=> Add NUMA LiteX configuration

CHANGELOG.md, rtl/core/neorv32_cpu_cp_bitmanip.vhd, rtl/core/neorv32_package.vhd
The shift operations of the `Zbb` instructions caused a permanent ALU stall (and thus, a timeout leading to an illegal instruction exception) when `CPU_FAST_SHIFT_EN` and `RISCV_ISA_Zbkc` are both disabled.
Bug discovered by @ecstrema in https://github.com/stnolting/neorv32/issues/640#issuecomment-2724946979.
=> :bug: Fix `Zbb` shift instructions

sw/bootloader/bootloader.c, sw/example/demo_spi/main.c, sw/example/demo_twi/main.c, sw/example/processor_check/main.c, sw/lib/include/neorv32_spi.h, sw/lib/include/neorv32_twi.h, sw/lib/source/neorv32_spi.c, sw/lib/source/neorv32_twi.c
* `neorv32_twi_trans() -> neorv32_twi_transfer()`
* `neorv32_spi_trans() -> neorv32_spi_transfer()`
=> :warning: rename SPI & TWI transfer functions

docs/datasheet/cpu.adoc
Fix the name for the "A" (Atomic memory instructions) ISA extension in the instruction set extensions table.
=> docs: datasheet: cpu: fix name for the "A" ISA extension

sw/common/neorv32.ld
* fix alignment of `.init_array.*` and `.fini_array.*` section (have to be 32-bit aligned)
* cleanup linker script
=> 🐛 [linker] fix alignment of init/fini arrays

sw/lib/include/neorv32.h, sw/lib/include/neorv32_cpu.h, sw/lib/include/neorv32_wdt.h, sw/lib/source/neorv32_wdt.c
This PR adds a function to perform a "soft restart" of a CPU core. For example, this can be used to "park" the secondary CPU core (core1) again so it can be launched again:
```c
int main_core1(void) {
// setup NEORV32 runtime-environment (RTE) for this core (core1)
neorv32_rte_setup();
// do some useful stuff
stuff();
// park core1 again in crt0 boot code
neorv32_cpu_soft_restart();
// return to crt0 and halt; will never be reached
return 0;
}
```
> [!WARNING]
> This is just a "software reset" that uses the in-code reset/boot/entry address linked at compile time.
After this core can be re-booted using `neorv32_smp_launch();`.
--------------
A real hardware reset of the entire processor can be triggered via the watchdog (WDT) module by the new new `neorv32_wdt_force_hwreset();` function: …
=> [sw/lib] add restart/reset functions

sw/lib/include/neorv32_neoled.h, sw/lib/source/neorv32_neoled.c
- Fixed "NEOLED_CTRL_IRQ_CONF" bit never being set in the "neorv32_neoled_setup" function.
- Updated corresponding doxygen comments
"irq_mode" parameter was shifted to the "NEOLED_CTRL_EN" position and thus rendered ineffective. This caused the "NEOLED_CTRL_IRQ_CONF" bit to remain 0 at all times, causing the interrupt to always trigger on an empty FIFO.
Tested with current main branch up to commit e1283bc. Interrupt is triggered on both an empty and (less than) half full FIFO.
=> [sw/lib/neoled] fix neoled "irq_mode" not a applied in "neorv32_neoled_setup" and [sw/lib/neoled] updated doxygen comments

CHANGELOG.md, docs/datasheet/soc_pwm.adoc, rtl/core/neorv32_package.vhd, rtl/core/neorv32_pwm.vhd, sw/lib/include/neorv32_pwm.h, sw/lib/source/neorv32_pwm.c, sw/svd/neorv32.svd
Add support for setting the PWM output polarity (normal/inverted). This simplifies software support when driving active-low PWM signals (e.g. active-low driven LEDs).
=> Add support for setting PWM polarity

CHANGELOG.md, rtl/core/neorv32_bus.vhd, rtl/core/neorv32_package.vhd, sw/example/demo_dual_core_primes/Makefile, sw/example/demo_dual_core_primes/main.c
* remove the idle cycle that occurs while the bus switch is checking if there is a request from the _other_ core; for the dual-core setup this optimization provides about ~10% more performance
* add a new demo program that shows how to split a workload (counting prime numbers) across the two cores
=> Optimize round-robin bus switch: remove idle cycles

CHANGELOG.md, docs/datasheet/cpu.adoc, rtl/core/neorv32_bus.vhd, rtl/core/neorv32_cache.vhd, rtl/core/neorv32_clint.vhd, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_cpu_frontend.vhd, rtl/core/neorv32_cpu_lsu.vhd, rtl/core/neorv32_cpu_pmp.vhd, rtl/core/neorv32_dma.vhd, rtl/core/neorv32_package.vhd
This PR adds a new status signal (`lock`) to the processor-internal request bus. When set, the bus infrastructure gives priority to this bus transaction and does not allow any interruptions. This reduces waite states when transferring larger memory blocks (e.g. cache blocks).
Cache block updates (cache line = 8x32-bit) issues by both CPU cores are interleaved.
Cache block updates (cache line = 8x32-bit) complete one after another.
Next step: cache bursts.
=> Add bus lock feature

CHANGELOG.md, rtl/core/neorv32_cache.vhd, rtl/core/neorv32_package.vhd, rtl/core/neorv32_top.vhd
In the current version the block replacement logic is highly inefficient. If a dirty block _x_ is replaced by a new block _y_ the following operations are performed:
1. upload the diry block _x_ to main memory
2. download block _x_ from memory
3. download new block _y_
Obviously, step 2. is redundant and is removed by this PR.
The bus switch, which connects the CPU's instruction and data ports (that might be cached) to the rest of the system, now uses a "lockable" round-robin scheduling if any CPU cache (D$ or I$) is enabled. This lockable scheduling prevent interleaving of cache block transfers leading to less wait states.
=> Optimize cache system

rtl/processor_templates/README.md
In 96d1dbdcc2092080672aa65b70567bca9e177315 the `setups` directory became [neorv32-setups](https://github.com/stnolting/neorv32-setups). This update the README link too.
Thank you for this awesome project!
=> [docs] fix dead link to setups

CHANGELOG.md, docs/datasheet/cpu.adoc, docs/datasheet/soc.adoc, docs/datasheet/soc_dcache.adoc, docs/datasheet/soc_icache.adoc, rtl/core/neorv32_cache.vhd, rtl/core/neorv32_cpu.vhd, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_package.vhd, rtl/core/neorv32_top.vhd, sw/example/processor_check/main.c
Moving back the to the "write-through" strategy.
* simpler memory synchronization: write to the data cache are always sync with main memory
* only main memory -> cache block transfers; this will make it easier to implement memory bursts
* write-allocate / write-back strategies might be re-implemented later when burst support is available
=> Rework caches; use "write-through" strategy

CHANGELOG.md, docs/datasheet/cpu.adoc, rtl/core/neorv32_bus.vhd, rtl/core/neorv32_cache.vhd, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_cpu_frontend.vhd, rtl/core/neorv32_cpu_lsu.vhd, rtl/core/neorv32_dma.vhd, rtl/core/neorv32_package.vhd, rtl/core/neorv32_xbus.vhd
This PR adds an explicit "this is a burst"-signal to the processor-internal bus system. The `burst` signal is set when the `lock` signal is set (but not the other way around). This makes burst detection logic easier.
=> [bus] add explicit burst signal to internal processor bus

CHANGELOG.md, rtl/core/neorv32_bus.vhd, rtl/core/neorv32_package.vhd
Bug introduced in previous version (v1.11.4.5, #1265).
=> 🐛 Fix missing burst signal in bus register stage

CHANGELOG.md, docs/datasheet/cpu.adoc, docs/datasheet/soc_xbus.adoc, rtl/core/neorv32_cache.vhd, rtl/core/neorv32_cpu_lsu.vhd, rtl/core/neorv32_package.vhd, sim/xbus_memory.vhd
* 🐛 For atomic read-modify-write operations the CPU's `lock` signal is cleared too early.
* 🐛 Previously, the `ben` bus signal was only used internally for write accesses. Read accesses were always expected to return a complete 32-bit word. However, this is a problem for the XBUS interface, as the `sel` (= `ben`) Wishbone signal is also used for read accesses (-> #1269). This PR fixes this issue; `sel` and `ben` now correctly indicate which read/write data bytes are actually valid/required.
These errors were introduced with the introduction of the locking infrastructure / cache burst.
=> :bug: fix CPU bus issues

CHANGELOG.md, rtl/core/neorv32_bus.vhd, rtl/core/neorv32_cpu_frontend.vhd, rtl/core/neorv32_package.vhd
Instruction fetch always has to request a full 32-bit word (-> `ben = 1111`).
This bug only affects the external bus interface (XBUS). The processor-internal modules ignore `ben` for read accesses and always output a full 32-bit word.
=> :bug: fix byte-enable bus signal for instruction fetch accesses

CHANGELOG.md, rtl/core/neorv32_dmem.vhd, rtl/core/neorv32_imem.vhd, rtl/core/neorv32_package.vhd
The previous version caused DRC errors (cascading BRAMs) on Vivado 24.1 when using large IMEM/DMEM configuration (> 256kB).
=> Rework IMEM & DMEM RAM style

CHANGELOG.md, docs/datasheet/soc.adoc, docs/datasheet/soc_dma.adoc, rtl/core/neorv32_dma.vhd, rtl/core/neorv32_package.vhd, rtl/core/neorv32_top.vhd, rtl/system_integration/neorv32_vivado_ip.tcl, rtl/system_integration/neorv32_vivado_ip.vhd, sim/neorv32_tb.vhd, sw/example/demo_dma/main.c, sw/example/processor_check/main.c, sw/lib/include/neorv32_dma.h, sw/lib/source/neorv32_dma.c, sw/svd/neorv32.svd
* :bug: fix DMA's byte-enable issues (-> #1269)
* add a configurable descriptor FIFO: program several transfers and execute them at once
* new top generic `IO_DMA_DSC_FIFO` - number of entries in the DMA descriptor FIFO
Example:
```c
// program two DMA transfers
neorv32_dma_program(
(uint32_t)&src_array_a,
(uint32_t)&dst_array_a,
DMA_SRC_INC_BYTE | DMA_DST_INC_BYTE | DMA_BSWAP | 32 // 32 bytes, convert Endianness
);
neorv32_dma_program(
(uint32_t)&src_array_b,
(uint32_t)&dst_array_b,
DMA_SRC_CONST_WORD | DMA_DST_CONST_WORD | 4 // words
);
// start transfers and wait in sleep mode for completion
neorv32_dma_start();
neorv32_cpu_sleep();
```
=> 🧪 rework DMA controller

CHANGELOG.md, docs/datasheet/soc.adoc, docs/datasheet/soc_slink.adoc, docs/datasheet/soc_uart.adoc, rtl/core/neorv32_package.vhd, rtl/core/neorv32_top.vhd, rtl/core/neorv32_uart.vhd, sim/neorv32_tb.vhd, sw/example/processor_check/main.c, sw/lib/include/neorv32.h, sw/svd/neorv32.svd
Just like in #1286, this PR combines the individual RX and TX interrupt signals of the UART module(s) into a single interrupt signal:
> The UART module provides a single interrupt request that can be used to signal certain RX/TX data FIFO conditions. The according interrupt conditions are based on the RX/TX FIFO status flags `UART_CTRL_RX_*` / `UART_CTRL_TX_*` and are configured via the according `UART_CTRL_IRQ_RX_*` / `UART_CTRL_IRQ_TX_*` bits. The UART interrupt will fire when the module is enabled (`SLINK_CTRL_EN`) and **any** of the selected interrupt conditions is met. Hence, all enabled interrupt conditions are logically OR-ed. The interrupt remains active until all interrupt-causing conditions are resolved.
=> ⚠️ combine UART's RX and TX interrupts into a single interrupt

CHANGELOG.md, docs/datasheet/soc_dma.adoc, rtl/core/neorv32_cpu_frontend.vhd, rtl/core/neorv32_dma.vhd, rtl/core/neorv32_fifo.vhd, rtl/core/neorv32_neoled.vhd, rtl/core/neorv32_onewire.vhd, rtl/core/neorv32_package.vhd, rtl/core/neorv32_sdi.vhd, rtl/core/neorv32_slink.vhd, rtl/core/neorv32_spi.vhd, rtl/core/neorv32_trng.vhd, rtl/core/neorv32_twd.vhd, rtl/core/neorv32_twi.vhd, rtl/core/neorv32_uart.vhd, sw/example/coremark/include/core_portme.h, sw/example/coremark/source/core_portme.c, sw/example/demo_dma/main.c, sw/lib/include/neorv32_dma.h, sw/lib/source/neorv32_dma.c, sw/svd/neorv32.svd
* Add optional "outout gate": If `OUT_GATE` is enabled, the FIFO outputs all-zero if no valid data is available.
* Improve performance; now requires one cycle less for each read-write operation.
* Code cleanup and logic optimization.
* ⚠️ Rework "error"/"done" and interrupt acknowledge mechanism.
* 🧪 Add experimental multi-threading / dual-core configuration.
=> Minor rtl edits and optimizations

CHANGELOG.md, docs/datasheet/soc_wdt.adoc, rtl/core/neorv32_cpu_cp_cond.vhd, rtl/core/neorv32_cpu_cp_muldiv.vhd, rtl/core/neorv32_debug_auth.vhd, rtl/core/neorv32_package.vhd, rtl/core/neorv32_top.vhd, rtl/core/neorv32_wdt.vhd, sw/example/demo_wdt/main.c, sw/lib/include/neorv32_wdt.h, sw/lib/source/neorv32_wdt.c, sw/svd/neorv32.svd
* remove control register's `strict` bit
* if the configuration register is locked, the WDT will be in "strict" mode:
* write access to the control register triggers a hardware reset of the system
* writing an incorrect password to the reset register triggers a hardware reset of the system
* minor code edits and cleanups
=> remove WDT "strict" bit; minor code edits and cleanups

sw/example/processor_check/main.c, sw/example/processor_check/makefile, sw/lib/include/neorv32_rte.h, sw/lib/source/neorv32_rte.c
Use a _directly-indexed_ look-up table for the runtime environment's trap handlers. This is not necessarily memory-efficient (many entries are unused), but it is much faster to process.
This modification is fully backwards compatible.
=> Rework RTE trap handler look-up-table

CHANGELOG.md, docs/datasheet/cpu.adoc, docs/datasheet/software.adoc, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_package.vhd, sim/neorv32_tb.vhd, sw/example/bus_explorer/main.c, sw/example/demo_clint/main.c, sw/example/demo_dma/main.c, sw/example/demo_dual_core_rte/main.c, sw/example/demo_emulate_unaligned/main.c, sw/example/demo_gpio/main.c, sw/example/demo_gptmr/main.c, sw/example/demo_semihosting/main.c, sw/example/demo_slink/main.c, sw/example/demo_spi_irq/main.c, sw/example/demo_trng/main.c, sw/example/demo_twd/main.c, sw/example/processor_check/main.c, sw/lib/include/neorv32.h, sw/lib/include/neorv32_legacy.h, sw/lib/include/neorv32_rte.h, sw/lib/source/neorv32_rte.c
* cleanup redundancies
* rework trap handler configuration (`int neorv32_rte_handler_install(uint32_t code, void (*handler)(void))`): use the actual trap code (from `mcause`) instead of an explicit trap code list
* a backwards-compatibility wrapper is added (`sw/lib/inc/neorv32_legacy.h`), so no code adaptions are required
* the "double-trap exception" now has highest trap priority
=> [rte] cleanups and optimizations

CHANGELOG.md, docs/datasheet/on_chip_debugger.adoc, docs/datasheet/soc.adoc, rtl/core/neorv32_cpu.vhd, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_package.vhd, rtl/core/neorv32_top.vhd, rtl/system_integration/neorv32_libero_ip.vhd, rtl/system_integration/neorv32_vivado_ip.tcl, rtl/system_integration/neorv32_vivado_ip.vhd, sim/neorv32_tb.vhd
* ⚠️ remove `OCD_HW_BREAKPOINT` top generic
* ✨ replaced by new generic to configure the number of hardware triggers:
```vhdl
OCD_NUM_HW_TRIGGERS : natural range 0 to 16 := 0; -- number of hardware break-/watchpoints
```
Tested with openOCD and GDB:
```
Info : [neorv32.cpu0] Found 4 triggers
```
=> ✨ add configurable number of break-/watchpoints

CHANGELOG.md, docs/datasheet/soc_uart.adoc, docs/userguide/simulating_the_processor.adoc, rtl/core/neorv32_package.vhd, rtl/core/neorv32_top.vhd, rtl/core/neorv32_uart.vhd, sim/ghdl.sh, sim/neorv32_tb.vhd, sim/sim_uart_rx.vhd, sw/example/demo_semihosting/makefile, sw/example/hello_world/makefile, sw/example/processor_check/makefile
Rename UART log files.
* `neorv32.uart0_sim_mode.out` -> `neorv32.uart0_sim_mode.log`
* `neorv32.uart1_sim_mode.out` -> `neorv32.uart1_sim_mode.log`
* `neorv32_tb.uart0_rx.out` -> `tb.uart0_rx.log`
* `neorv32_tb.uart1_rx.out` -> `tb.uart1_rx.log`
=> Cleanup UART simulation logging

rtl/core/neorv32_top.vhd
Hi Stephan!
To avoid issues with VUnit `trace` function we should change `trace` signal name in the top. I proposed to change from `trace` to `trace_s` ("s" refers to signal).
Due to `trace` elements are evaluated through "()" and in VHDL this can also refer to a function, the following error occurs:
```
Compiling into neorv32: vunit_out/preprocessed/neorv32/neorv32_application_image.vhd passed
Compiling into neorv32: vunit_out/preprocessed/neorv32/neorv32_imem.vhd              passed
Compiling into neorv32: vunit_out/preprocessed/neorv32/neorv32_top.vhd               failed
=== Command used: ===
/usr/local/bin/ghdl -a --workdir=/wrk/sim/MEM/vunit_out/ghdl/libraries/neorv32 --work=neorv32 --std=08 -P/wrk/sim/MEM/vunit_out/ghdl/libraries/vunit_lib …
```
=> Replace trace with trace_s in the top

docs/datasheet/soc_tracer.adoc, sw/example/demo_tracer/main.c, sw/example/demo_tracer/neorv32_tracer.gdb
* add GDB helper script: `neorv32/sw/example/demo_tracer/neorv32_tracer.gdb`
* restart tracer for CPU 0 or CPU 1
* dump and pretty-print trace log
* updated documentation's tracer section
Using the tracer from GDB:
```
(gdb) make clean elf
...
(gdb) load
...
(gdb) c
...
(gdb) source neorv32_tracer.gdb
(gdb) tracer_get
[0] SRC: 0x3b0 -> DST: 0x2cc <TRACE_START>
Line 128 of "main.c" starts at address 0x3b0 <main+212> and ends at 0x3b4 <main+216>.
Line 68 of "main.c" starts at address 0x2cc <test_code> and ends at 0x2d0 <test_code+4>.
...
```
=> Add GDB tracer support

CHANGELOG.md, docs/datasheet/cpu.adoc, docs/datasheet/soc.adoc, docs/datasheet/soc_dcache.adoc, docs/datasheet/soc_icache.adoc, docs/datasheet/soc_sysinfo.adoc, docs/datasheet/soc_xbus.adoc, rtl/core/neorv32_cache.vhd, rtl/core/neorv32_package.vhd, rtl/core/neorv32_sysinfo.vhd, rtl/core/neorv32_top.vhd, rtl/system_integration/neorv32_vivado_ip.tcl, rtl/system_integration/neorv32_vivado_ip.vhd, rtl/system_integration/xbus2axi4_bridge.vhd, sim/neorv32_tb.vhd, sw/lib/include/neorv32_sysinfo.h, sw/lib/source/neorv32_aux.c, sw/svd/neorv32.svd
New configuration option that allows you to set whether the caches use burst transfers or only single accesses for cache block update operations:
```vhdl
CACHE_BURSTS_EN : boolean := true; -- i-cache/d-cache: enable issuing of burst transfer for cache update
```
Bursts should only be disabled if modules connected to the external bus interface (AXI) do not support burst transfers. By default bursts are always enabled. Hence, the changes from the PR are fully backwards-compatible.
=> Make cache/AXI bursts optional

CHANGELOG.md, docs/datasheet/cpu.adoc, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_cpu_hwtrig.vhd, rtl/core/neorv32_package.vhd, sw/example/processor_check/main.c, sw/lib/source/neorv32_rte.c
* Runtime environment (RTE): Adjust the return address (`mepc`) _after_ calling the handler. This allows the trap handler to check/use the original `mepc` value.
* Hardware trigger module (`Sdtrig` ISA extensions): Correct trigger logic. Now the instruction address trigger is triggered precisely even when it is set to an instruction that raises an exception (such as the environment call command `ecall`).
* Single-stepping: Rework single-step trap trigger (turn it into an actual _synchronous_ exception).
* `mtinst` CSR: Do not write zero to the CSR in case of an interrupt. `mtinst` now also shows the last executed instruction word when encountering an interrupt.
* CSR write logic: Code cleanup; use a single `case` statement instead of several `if` statements.
* Code cleanups and logic …
=> minor fixes and optimizations

CHANGELOG.md, docs/datasheet/soc.adoc, docs/datasheet/soc_dcache.adoc, docs/datasheet/soc_icache.adoc, docs/datasheet/soc_xbus.adoc, rtl/core/neorv32_bus.vhd, rtl/core/neorv32_cache.vhd, rtl/core/neorv32_package.vhd, rtl/core/neorv32_top.vhd, rtl/core/neorv32_xbus.vhd, rtl/system_integration/neorv32_libero_ip.vhd, rtl/system_integration/neorv32_litex_core_complex.vhd, rtl/system_integration/neorv32_vivado_ip.vhd, sim/neorv32_tb.vhd, sim/xbus_gateway.vhd, sw/example/processor_check/main.c
* ⚠️ remove top's `XBUS_TIMEOUT` generic
* the number of cycles after which a bus access times out is now entirely defined by the `bus_timeout_c` package constant (1024 by default)
* rework bus monitor: if a burst transfer causes an error the bus monitor will issue the missing data ACKs if the accessed device does not provide them
* rework caches: the cache now stores a status-bit for each cache word (absorbed into the BRAM's parity bit):
* if a single access within a cache block transfer causes a bus error only that specific word is marked as invalid instead of the entire cache block; this also allows to cache memories that are smaller than a single cache line
=> Rework bus access error logic

CHANGELOG.md, rtl/core/neorv32_cpu_frontend.vhd, rtl/core/neorv32_cpu_regfile.vhd, rtl/core/neorv32_dma.vhd, rtl/core/neorv32_fifo.vhd, rtl/core/neorv32_neoled.vhd, rtl/core/neorv32_onewire.vhd, rtl/core/neorv32_package.vhd, rtl/core/neorv32_sdi.vhd, rtl/core/neorv32_slink.vhd, rtl/core/neorv32_spi.vhd, rtl/core/neorv32_tracer.vhd, rtl/core/neorv32_trng.vhd, rtl/core/neorv32_twd.vhd, rtl/core/neorv32_twi.vhd, rtl/core/neorv32_uart.vhd, rtl/file_list_cpu.f, sim/neorv32_tb.vhd
* optimize instruction prefetch buffer (CPU front-end): use a specialized module instead of the generic FIFO module
* rework CPU register file logic
* cleanup and otimize FIFO component:
* remove memory-reset option
* remove asynchronous reset option; read access are always synchronous
* remove level output (was unused anyway)
=> rtl code cleanups and optimizations

sw/lib/include/neorv32_semihosting.h
=> [demo_semihosting] use 4-byte instead of 16-byte alignment

CHANGELOG.md, docs/datasheet/soc_sdi.adoc, docs/datasheet/soc_uart.adoc, rtl/core/neorv32_bootloader_image.vhd, rtl/core/neorv32_dma.vhd, rtl/core/neorv32_neoled.vhd, rtl/core/neorv32_onewire.vhd, rtl/core/neorv32_package.vhd, rtl/core/neorv32_prim.vhd, rtl/core/neorv32_sdi.vhd, rtl/core/neorv32_slink.vhd, rtl/core/neorv32_spi.vhd, rtl/core/neorv32_tracer.vhd, rtl/core/neorv32_trng.vhd, rtl/core/neorv32_twd.vhd, rtl/core/neorv32_twi.vhd, rtl/core/neorv32_uart.vhd, sim/neorv32_tb.vhd, sw/example/demo_sdi/main.c, sw/example/processor_check/main.c, sw/lib/include/neorv32_sdi.h, sw/lib/include/neorv32_spi.h, sw/lib/include/neorv32_uart.h, sw/lib/source/neorv32_sdi.c, sw/lib/source/neorv32_spi.c, sw/lib/source/neorv32_uart.c, sw/svd/neorv32.svd
* remove RX/TX FIFO "half-full" status flags
* simply interrupt conditions
* RX FIFO not empty (data available)
* RX FIFO full
* TX FIFO empty
* TX FIFO not full
* massive code rework
* rework control and data register layouts
* minor logic optimizations and code-cleanups
* remove RX/TX FIFO "half-full" status flags
* simply interrupt conditions
* RX FIFO not empty (data available)
* RX FIFO full
* TX FIFO empty
* rework control register layout
* minor logic optimizations and code-cleanups
=> ⚠️ simplify UART and SDI modules

CHANGELOG.md, docs/datasheet/soc_tracer.adoc, rtl/core/neorv32_package.vhd, rtl/core/neorv32_tracer.vhd
This PR adds additional instruction decoding to the simulation log of the TRACER module.
The decoding shows not only the mnemonics, but also the operands (in the respective instruction format). In addition, CSR addresses are also translated into the corresponding names.
```
50 242 00000150 10500073 M wfi
51 871239 00000154 ffdff06f M c.jal
52 871250 0000009c fff44737 M lui <TRAP_ENTRY>
53 871252 000000a0 00872103 M lw
54 871270 000000a4 00c72603 M c.lw
55 871278 000000a6 fff40737 M lui
56 871281 000000aa 00072223 M sw
57 871289 000000ae 04a0006f M c_jal
58 871309 000000f8 80000197 M auipc
59 871311 000000fc 0807c7b3 M ALU?
```
```
50 226 0x0000019c 0x10500073 M wfi
51 890622 0x000000c8 0xfff44737 M lui x14, 0xfff44000 <TRAP_ENTRY>
52 890624 0x000000cc 0x00872103 M lw x2, 2(x14)
53 890632 …
```
=> [tracer] update simulation-mode instruction decoding

CHANGELOG.md, docs/datasheet/soc_tracer.adoc, rtl/core/neorv32_package.vhd, rtl/core/neorv32_tracer.vhd
Rework instruction decoding logic and (try to) include _all_ currently supported ISA extensions.
The new decoding logic used some kind of look-up table which is much easier to handle / update.
```vhdl
("-----------------100-----0010011", "xori       "),
("-----------------110-----0010011", "ori        "),
("-----------------111-----0010011", "andi       "),
("0000000----------001-----0010011", "slli       "),
("0000000----------101-----0010011", "srli       "),
```
For each commited instruction the simulator scans the entire look-up table to find a matching pattern. I wonder if this concept could also be used to simplify the actual instruction decoder of the CPU... 🤔
=> [tracer] update simulation-mode trace logging

CHANGELOG.md, docs/datasheet/cpu_cfu.adoc, docs/datasheet/cpu_csr.adoc, rtl/core/neorv32_cpu_alu.vhd, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_cpu_cp_cfu.vhd, rtl/core/neorv32_package.vhd, rtl/core/neorv32_tracer.vhd, sw/example/demo_cfu/main.c, sw/lib/include/neorv32_cpu_csr.h, sw/openocd/target.cfg
Remove the `cfureg*` CSRs used by the CFU (custom instructions wrapper). CFU-internal state should be accessible only via the according custom instructions.
I am planning to replace the NEORV32 CFU by the RISC-V **Composable Custom Extensions Specification** and this is the first step in the migration. This ISA extension is still in the "planning" phase (https://riscv.atlassian.net/browse/RVS-2611). However, a first draft is already available: https://github.com/grayresearch/CX
=> ⚠️ remove CFU CSRs

CHANGELOG.md, docs/datasheet/cpu.adoc, docs/datasheet/soc.adoc, docs/datasheet/soc_sysinfo.adoc, docs/datasheet/soc_xbus.adoc, rtl/core/neorv32_bus.vhd, rtl/core/neorv32_cpu.vhd, rtl/core/neorv32_cpu_control.vhd, rtl/core/neorv32_package.vhd, rtl/core/neorv32_sysinfo.vhd, rtl/core/neorv32_top.vhd, rtl/system_integration/neorv32_vivado_ip.tcl, rtl/system_integration/neorv32_vivado_ip.vhd, sim/neorv32_tb.vhd, sw/lib/include/neorv32_sysinfo.h, sw/lib/source/neorv32_aux.c, sw/svd/neorv32.svd
Triggered in https://github.com/stnolting/neorv32/discussions/1378 by @alyxazon, this PR adds back the `XBUS_TIMEOUT` generic to configure the time window in which external bus accesses must be acknowledged before the access is terminated and a bus exception is raised.
Optionally, the timeout for external bus accesses can be disabled by setting `XBUS_TIMEOUT = 0`.
⚠️ In this PR, the layout of the `SYSINFO.MISC` register is also revised so that there is space for the values for internal and external bus timeouts.
=> [XBUS] re-add timeout configuration generic

docs/datasheet/software.adoc, sw/common/common.mk, sw/image_gen/image_gen.c
Clean up the code base, remove unnecessary elements, and improve the user interface.
The individual arguments are only mapped via explicit flags instead of their (fixed) position.
```
neorv32/sw/image_gen$ ./image_gen
NEORV32 executable image generator
Usage:    image_gen [options]
Example:  image_gen -i main.elf -o main_exe.bin -t app_bin
Options:
-h             Show this help text and exit
-i file_name   Input ELF file name, mandatory
-o file_name   Output file name, mandatory
-t type        Type of image to generate, default is 'app_bin'
Image type:
app_bin   Application executable for bootloader upload (binary file with header)
app_vhd   Application memory image (IMEM VHDL package file)
bld_vhd   Bootloader memory image (BOOTROM VHDL package file)
raw_hex   ASCII hex file (raw …
```
=> Rework NEORV32 executable image generator
