stnolting/neorv32

.github/generate-job-matrix.py

See https://github.com/stnolting/neorv32/pull/56#issuecomment-861784078.

[ci/generate-job-matrix] fix UPduino_v3 artifact (bitstream) extension

---

setups/osflow/iCESugar/iCESugar.pcf

See https://github.com/hdl/constraints/commit/93e09019b59f3788ed69cc1f701b181cdb7bba5d.

[setups/osflow/iCESugar] update PCF

---

setups/vivado/arty-a7-test-setup/create_project.tcl

In this PR, the TCL script for creation of the Vivado project for Arty boards is updated.
Instead of adding files to libraries directly, filesets are defined. This is for making it easier to understand the similarities with `setups/osflow/filesets.mk`.
BTW, the board and language are explicitly defined in the project.

[setups/vivado] arty-a7-test-setup: define multiple filesets, set board, set language

---

.github/workflows/Windows.yml

[ci/windows] fix RISCV_PREFIX

---

setups/osflow/boards/index.mk

[setup/osflow/boards/index.mk] do not set GHDL_PLUGIN_MODULE unconditionally

---

sim/neorv32_tb.vhd
sim/simple/neorv32_tb.simple.vhd

fix typo wb_mem_a.cyc on sim example

---

setups/README.md

Here I have added my neorv32-exaples project to the examples of boards.

Added neorv32-examples

---

docs/userguide/packaging_vivado.adoc

TRNG and Vivado block designs

---

setups/osflow/README.md

@umarcor @lab-mathias-claussen 
I have started to (finally) update the osflow README.
The first step is to add a tutorial-like sections how to add new FPGAs/board (idea coming from #218).
The other sections also require a makeover.
Help would be highly appreciated! :wink:

[setups/osflow] update README

---

docs/userguide/adding_custom_hw_modules.adoc

https://docs.asciidoctor.org/asciidoc/latest/macros/complex-urls/

Fix the link using an asciidoc trick.

---

CHANGELOG.md
rtl/core/neorv32_cpu_control.vhd
rtl/core/neorv32_neoled.vhd
rtl/core/neorv32_package.vhd

This PR contains minor rtl/VHDL code clean-ups and minor optimizations (CPU core and NEOLED module).

[rtl] minor clean-ups/optimizations

---

README.md
docs/userguide/content.adoc
docs/userguide/litex_support.adoc
docs/userguide/zephyr_support.adoc

Add a new section to the User Guide: How to setup and run LiteX using the NEORV32.

[ug] add new section "LiteX Support"

---

CHANGELOG.md
rtl/core/neorv32_cpu_control.vhd
rtl/core/neorv32_package.vhd

This PR fixes some minor core rtl issues I found while playing with a low-level netlist version of the processor.

[rtl] core cleanup / minor fixes

---

sw/lib/source/neorv32_uart.c

:bug: [sw/lib] fix UART "char_received" function

---

CHANGELOG.md
docs/datasheet/soc_uart.adoc
rtl/core/neorv32_package.vhd
rtl/core/neorv32_uart.vhd

[rtl] Optimize UART RTS behavior

---

CHANGELOG.md
rtl/core/neorv32_package.vhd
rtl/core/neorv32_trng.vhd

[rtl] update TRNG

---

docs/datasheet/software.adoc
docs/userguide/customizing_the_bootloader.adoc
sw/common/common.mk

Fixing #495.
@alpkoyun, what do you think about this?

[sw] add '_zicsr' to default MARCH configuration

---

sw/example/demo_neopixel/main.c
sw/lib/include/neorv32.h
sw/lib/include/neorv32_neoled.h
sw/lib/source/neorv32_neoled.c

Change definition of NEORV32_NEOLED and replace all "NEORV32_NEOLED." by "NEORV32_NEOLED->".
Even make the NEOLED structure volatile.

NEOLED: Change "variable style" by "pointer style"

---

sw/lib/include/neorv32.h
sw/lib/source/neorv32_sdi.c

Change definition of NEORV32_SDI and replace all "NEORV32_SDI." by "NEORV32_SDI->".
Even make the SDI structure volatile.

SDI: Change "variable style" by "pointer style"

---

sw/example/demo_spi/main.c
sw/example/demo_spi_irq/drv/neorv32_spi_irq.c
sw/lib/include/neorv32.h
sw/lib/source/neorv32_spi.c

Change definition of NEORV32_SPI and replace all "NEORV32_SPI." by "NEORV32_SPI->".
Even make the SPI structure volatile.

SPI: Change "variable style" by "pointer style"

---

sw/example/processor_check/main.c
sw/lib/include/neorv32.h
sw/lib/source/neorv32_wdt.c

Change definition of NEORV32_WDT and replace all "NEORV32_WDT." by "NEORV32_WDT->".
Even make the WDT structure volatile.

WDT: Change "variable style" by "pointer style"

---

CHANGELOG.md
docs/datasheet/soc_neoled.adoc
rtl/core/neorv32_neoled.vhd
rtl/core/neorv32_package.vhd
rtl/core/neorv32_top.vhd
sw/example/demo_neopixel/main.c
sw/example/processor_check/main.c
sw/lib/include/neorv32.h
sw/lib/include/neorv32_neoled.h
sw/lib/source/neorv32_neoled.c

* change interrupt configuration flag
* clean-up HDL code

Update NEOLED module

---

CHANGELOG.md
docs/datasheet/cpu.adoc
rtl/core/neorv32_bus_keeper.vhd
rtl/core/neorv32_busswitch.vhd
rtl/core/neorv32_cpu_control.vhd
rtl/core/neorv32_cpu_decompressor.vhd
rtl/core/neorv32_package.vhd
rtl/core/neorv32_wdt.vhd
rtl/core/neorv32_xirq.vhd

* VHDL code edits and cleanups
* improve branch prediction (+2% more performance 😅)

[rtl] minor edits, cleanups and optimization

---

CHANGELOG.md
rtl/core/neorv32_bus_keeper.vhd
rtl/core/neorv32_cpu_cp_cond.vhd
rtl/core/neorv32_cpu_decompressor.vhd
rtl/core/neorv32_fifo.vhd
rtl/core/neorv32_gpio.vhd
rtl/core/neorv32_gptmr.vhd
rtl/core/neorv32_neoled.vhd
rtl/core/neorv32_onewire.vhd
rtl/core/neorv32_package.vhd
rtl/core/neorv32_pwm.vhd
rtl/core/neorv32_sdi.vhd
rtl/core/neorv32_spi.vhd
rtl/core/neorv32_trng.vhd
rtl/core/neorv32_twi.vhd
rtl/core/neorv32_uart.vhd
rtl/core/neorv32_wdt.vhd
rtl/core/neorv32_xirq.vhd

Allows easier debugging (thx @tmeissner for the hint).

[rtl] re-add VHDL process names

---

CHANGELOG.md
docs/datasheet/cpu.adoc
rtl/core/neorv32_cpu_alu.vhd
rtl/core/neorv32_cpu_bus.vhd
rtl/core/neorv32_cpu_control.vhd
rtl/core/neorv32_package.vhd
sw/example/demo_xip/main.c
sw/lib/include/neorv32_xip.h
sw/lib/source/neorv32_xip.c

* 🐛 fix bug in FPU logic (discovered by @Giorgio122 in #577)
* minor code optimizations
* update/rework XIP functions and demo program (fully backwards-compatible)

🐛 FPU bug fix and rtl optimizations

---

.github/workflows/Processor.yml
CHANGELOG.md
do.py
docs/datasheet/soc.adoc
rtl/core/neorv32_cpu.vhd
rtl/core/neorv32_cpu_control.vhd
rtl/core/neorv32_dma.vhd
rtl/core/neorv32_intercon.vhd
rtl/core/neorv32_package.vhd
rtl/core/neorv32_sysinfo.vhd
rtl/core/neorv32_top.vhd
sw/example/processor_check/README.md
sw/example/processor_check/main.c
sw/example/processor_check/run_check.sh
sw/lib/include/neorv32_cpu.h

* add individual port-enable generics for IO switch
* terminate disabled request buses (gateway and IO switch)

[rtl] Optimize bus system and customization options

---

CHANGELOG.md
docs/datasheet/on_chip_debugger.adoc
rtl/core/neorv32_cpu_control.vhd
rtl/core/neorv32_package.vhd
sw/lib/include/neorv32_cpu_csr.h

* removed unused `mcontext` and `scontext` CSRs (`Sdtrig` ISA extension)
* optimization of CPU's control unit; higher f_max and reduced area utilization 🚀

CPU hardware optimization

---

docs/userguide/executable_upload.adoc

Update correct file

---

CHANGELOG.md
rtl/core/neorv32_cpu_control.vhd
rtl/core/neorv32_cpu_lsu.vhd
rtl/core/neorv32_intercon.vhd
rtl/core/neorv32_package.vhd
sim/neorv32_tb.vhd
sw/example/processor_check/main.c

* bus switch: simplify control arbiter
* cpu: minor edits
* processor check: add test case to check the RTE's context access functions

minor edits and optimizations

---

CHANGELOG.md
rtl/core/neorv32_cpu_decompressor.vhd
rtl/core/neorv32_package.vhd

:bug: fix another C-ISA loophole

---

docs/userguide/application_specific_configuration.adoc

Just a little something. Have a great day. :)

[docs] fix spelling

---

CHANGELOG.md
rtl/core/neorv32_cfs.vhd
rtl/core/neorv32_cpu_control.vhd
rtl/core/neorv32_package.vhd
sw/example/demo_cfs/main.c

- cleanup package functions (simplify code and remove unused ones)
- simplify default CFS "functions" (remove binary<->gray functions)
- simplify CSR address and access logic

minor RTL cleanups and optimizations

---

sw/lib/include/neorv32_sysinfo.h

[sw] fix `sysinfo` doxygen header

---

CHANGELOG.md
rtl/core/neorv32_cpu_control.vhd
rtl/core/neorv32_package.vhd

bug introduced in v1.10.3.6 (#1014)

:bug: fix B.CTZ decoding regression bug

---

CHANGELOG.md
rtl/core/neorv32_cache.vhd
rtl/core/neorv32_clockgate.vhd
rtl/core/neorv32_cpu.vhd
rtl/core/neorv32_cpu_control.vhd
rtl/core/neorv32_cpu_cp_cond.vhd
rtl/core/neorv32_cpu_decompressor.vhd
rtl/core/neorv32_cpu_lsu.vhd
rtl/core/neorv32_debug_dm.vhd
rtl/core/neorv32_gpio.vhd
rtl/core/neorv32_mtime.vhd
rtl/core/neorv32_neoled.vhd
rtl/core/neorv32_onewire.vhd
rtl/core/neorv32_package.vhd
rtl/core/neorv32_trng.vhd
rtl/core/neorv32_twi.vhd
rtl/core/neorv32_uart.vhd

* rewrite compressed instructions decompressor
* rewrite machine timer
* remove unused/redundant constants
* remove unused IEEE packages
* minor code cleanups to improve readability

Massive rtl code cleanup

---

CHANGELOG.md
rtl/core/neorv32_cpu_control.vhd
rtl/core/neorv32_cpu_decompressor.vhd
rtl/core/neorv32_debug_dtm.vhd
rtl/core/neorv32_package.vhd
rtl/core/neorv32_top.vhd

Minor HDL edits to make the code more readable.

[rtl] minor RTL edits

---

CHANGELOG.md
docs/datasheet/cpu.adoc
docs/datasheet/cpu_csr.adoc
docs/datasheet/soc.adoc
rtl/core/neorv32_bus.vhd
rtl/core/neorv32_cpu.vhd
rtl/core/neorv32_cpu_control.vhd
rtl/core/neorv32_package.vhd
rtl/core/neorv32_top.vhd
rtl/system_integration/neorv32_vivado_ip.tcl
rtl/system_integration/neorv32_vivado_ip.vhd
sim/neorv32_tb.vhd

* `CLOCK_GATING_EN` -> `CPU_CLOCK_GATING_EN`
* `FAST_MUL_EN` -> `CPU_FAST_MUL_EN`
* `FAST_SHIFT_EN` -> `CPU_FAST_SHIFT_EN`
* `REGFILE_HW_RST` -> `CPU_REGFILE_HW_RST`

⚠️ Rename CPU tuning options / generics

---

.github/workflows/Processor.yml

https://github.com/ghdl/ghdl/issues/2852

[ci] update GHDL setup

---

CHANGELOG.md
rtl/core/neorv32_boot_rom.vhd
rtl/core/neorv32_package.vhd
sw/lib/include/neorv32.h

🐛 fix BOOTROM addressing

---

docs/datasheet/cpu.adoc
docs/datasheet/cpu_csr.adoc
docs/datasheet/cpu_dual_core.adoc
docs/datasheet/soc.adoc
docs/datasheet/soc_neoled.adoc
docs/datasheet/soc_slink.adoc
docs/datasheet/soc_xbus.adoc

* Fix table 'mcounteren' cols
* Remove double words

Doc ds fixes

---

CHANGELOG.md
rtl/core/neorv32_cache.vhd
rtl/core/neorv32_cpu.vhd
rtl/core/neorv32_cpu_control.vhd
rtl/core/neorv32_cpu_icc.vhd
rtl/core/neorv32_package.vhd
rtl/core/neorv32_top.vhd
rtl/system_integration/neorv32_litex_core_complex.vhd

* optimize cache miss logic (less states; saves some cycles)
* fix outdated Litex wrapper generics
* minor cleanups and edits

Minor rtl optimizations and cleanups

---

CHANGELOG.md
rtl/core/neorv32_package.vhd
rtl/core/neorv32_pwm.vhd

Fixing #1221 by @henrikbrixandersen

:bug: fix PWM prescaler

---

CHANGELOG.md
rtl/core/neorv32_cpu_control.vhd
rtl/core/neorv32_package.vhd

* :bug: fix minor bug: an instruction fetch that returns a bus error (= "instruction access fault" exception) might return an instruction word that gets executed
* minor critical path optimization (branch logic)
* code cleanups

[cpu] rework instruction trap logic

---

CHANGELOG.md
docs/datasheet/soc.adoc
docs/datasheet/soc_dmem.adoc
docs/datasheet/soc_imem.adoc
docs/datasheet/soc_sysinfo.adoc
docs/userguide/application_specific_configuration.adoc
docs/userguide/general_hw_setup.adoc
docs/userguide/general_sw_framework_setup.adoc
docs/userguide/installing_an_executable.adoc
rtl/core/neorv32_package.vhd
rtl/core/neorv32_sysinfo.vhd
rtl/core/neorv32_top.vhd
rtl/processor_templates/neorv32_ProcessorTop_Minimal.vhd
rtl/processor_templates/neorv32_ProcessorTop_MinimalBoot.vhd
rtl/processor_templates/neorv32_ProcessorTop_UP5KDemo.vhd
rtl/system_integration/neorv32_litex_core_complex.vhd
rtl/system_integration/neorv32_vivado_ip.tcl
rtl/system_integration/neorv32_vivado_ip.vhd
rtl/test_setups/README.md
rtl/test_setups/neorv32_test_setup_approm.vhd
rtl/test_setups/neorv32_test_setup_bootloader.vhd
rtl/test_setups/neorv32_test_setup_on_chip_debugger.vhd
sim/neorv32_tb.vhd
sw/lib/include/neorv32_sysinfo.h
sw/lib/source/neorv32_aux.c
sw/svd/neorv32.svd

* `MEM_INT_IMEM_EN` -> `IMEM_EN`
* `MEM_INT_IMEM_SIZE` -> `IMEM_SIZE`
* `MEM_INT_DMEM_EN` -> `DMEM_EN`
* `MEM_INT_DMEM_SIZE` -> `DMEM_SIZE`

⚠️ Rename IMEM/DMEM configuration generics

---

CHANGELOG.md
rtl/core/neorv32_cpu_control.vhd
rtl/core/neorv32_cpu_hwtrig.vhd
rtl/core/neorv32_package.vhd
rtl/core/neorv32_top.vhd
rtl/core/neorv32_trng.vhd
rtl/core/neorv32_xbus.vhd

* XBUS: fix synthesis warnings when `TIMEOUT_VAL = 0`
* extend processor configuration sanity checks

minor rtl edits and cleanups

---

docs/datasheet/soc_xbus.adoc

[docs] xbus: fix/clarify CTI values
